"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Brain, CalendarDays, ClipboardCheck, Pill, ShieldCheck, Sparkles, TestTube2 } from "lucide-react";
type Tab="Σύνοψη"|"Συνεδρίες"|"Ιστορικό"|"Αγωγή"|"Κλίμακες";
export default function Kostas(){const [tab,setTab]=useState<Tab>("Σύνοψη");return <main className="clinical-page"><div className="clinical-top"><Link href="/patients" className="back"><ArrowLeft size={17}/> Ασθενείς</Link><span>Κλινικός φάκελος · Υποθετικός ασθενής MVP</span></div><div className="patient-hero"><div><p className="eyebrow">ΕΠΟΜΕΝΗ ΕΠΑΝΕΚΤΙΜΗΣΗ · ΣΕ 2 ΕΒΔΟΜΑΔΕΣ</p><h1>Κώστας Σ.</h1><p>37 ετών · αρχική αξιολόγηση 1 Οκτωβρίου</p></div></div><div className="patient-tabs">{(["Σύνοψη","Συνεδρίες","Ιστορικό","Αγωγή","Κλίμακες"] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?"active":""}>{x}</button>)}</div>
{tab==="Σύνοψη"&&<section className="patient-layout"><div className="patient-main"><div className="card focus-card"><span className="kicker">ΣΥΝΟΨΗ ΜΕΤΑ ΤΗΝ ΑΡΧΙΚΗ ΑΞΙΟΛΟΓΗΣΗ</span><h2><Sparkles size={19}/> Τρέχουσα κλινική εικόνα</h2><div className="memory-lead">Πρώτη αξιολόγηση για <b>επίμονο άγχος και δυσκολία ύπνου</b> περίπου 4 μηνών, με επίδραση κυρίως το βράδυ και πριν από σημαντικές επαγγελματικές συναντήσεις.</div><div className="memory-grid"><div><strong>Κύρια ευρήματα</strong><ul><li>Αγχώδης συμπτωματολογία ~4 μηνών</li><li>Δυσκολία έναρξης ύπνου</li><li>Επηρεασμένη εργασιακή λειτουργικότητα</li></ul></div><div><strong>Επόμενα βήματα</strong><ul><li>Ολοκλήρωση baseline κλιμάκων</li><li>Παρακολούθηση ύπνου και άγχους</li><li>Επανεκτίμηση σε 2 εβδομάδες</li></ul></div></div><div className="risk-strip"><ShieldCheck size={17}/> Αρνείται αυτοκτονικό ιδεασμό, πρόθεση ή σχέδιο.</div></div></div><aside className="patient-side"><div className="card side-card"><span className="kicker">ΚΛΙΝΙΚΗ ΕΙΚΟΝΑ</span><Info icon={<Brain/>} label="Κλινική εκτίμηση" value="Αγχώδης συμπτωματολογία · υπό διερεύνηση"/><Info icon={<Pill/>} label="Αγωγή" value="Δεν έχει καταγραφεί φαρμακευτική αγωγή"/><Info icon={<CalendarDays/>} label="Επανεκτίμηση" value="Σε 2 εβδομάδες"/></div></aside></section>}
{tab==="Συνεδρίες"&&<Simple title="Συνεδρίες" text="01/10 · Αρχική αξιολόγηση — ψυχιατρική συνέντευξη, MSE, risk assessment και αρχικό θεραπευτικό πλάνο."/>}{tab==="Ιστορικό"&&<Simple title="Κλινικό ιστορικό" text="Η αρχική καρτέλα περιλαμβάνει τον λόγο προσέλευσης, ψυχιατρικό και ιατρικό ιστορικό. Θα εμπλουτίζεται μόνο με εγκεκριμένα δεδομένα."/>}{tab==="Αγωγή"&&<Simple title="Αγωγή" text="Δεν υπάρχει ενεργή φαρμακευτική αγωγή καταγεγραμμένη στο demo."/>}{tab==="Κλίμακες"&&<Simple title="Κλίμακες" text="Οι baseline κλίμακες έχουν ζητηθεί και αναμένονται πριν την επανεκτίμηση."/ >}</main>}
function Simple({title,text}:{title:string,text:string}){return <section className="tab-page"><div className="tab-heading"><h2>{title}</h2><p>{text}</p></div></section>}
function Info({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="side-info"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
