'use client';
import PilotProfile from '@/components/PilotProfile';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Activity, Bell, CalendarDays, ChevronRight, FileClock, Home, Menu, Plus, Search, Settings, Stethoscope, Users, X } from 'lucide-react';
import { getDemoTesterId } from '@/lib/demo-tester';

type DiagnosisCode={code:string;label:string};
type Row={id:string;first_name:string;last_name:string;reported_age:number|null;note:string;chief_complaint:string;status:string;created_at:string;updated_at:string;registry_number:number;diagnosis:DiagnosisCode|null;draft?:{id:string}|null;last_session?:{completed_at:string}|null;next_appointment?:{scheduled_start:string}|null};
const normalize=(value:string)=>value.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase('el');
const formatDate=(value?:string|null)=>value?new Intl.DateTimeFormat('el-GR',{day:'2-digit',month:'short'}).format(new Date(value)):'—';

export default function Patients(){
 const [assign,setAssign]=useState<string|null>(null);
 useEffect(()=>{const code=new URLSearchParams(window.location.search).get('assign');if(code==='PHQ-9'||code==='GAD-7')setAssign(code)},[]);
 const [q,setQ]=useState(''); const [filter,setFilter]=useState<'all'|'draft'|'active'>('all'); const [sort,setSort]=useState<'registry'|'name'|'recent'|'next'>('registry'); const [mobileNav,setMobileNav]=useState(false); const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{const tester=getDemoTesterId();fetch(`/api/patients/demo/runtime?tester=${tester}`,{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setRows((data.patients||[]) as Row[])}).catch(()=>setError('Δεν φορτώθηκαν οι δοκιμαστικοί ασθενείς.')).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>{const query=normalize(q.trim());let data=rows.filter(p=>!query||normalize(`${p.first_name} ${p.last_name} ${p.note} ${p.chief_complaint} ${p.diagnosis?.code||''} ${p.diagnosis?.label||''}`).includes(query));if(filter==='draft')data=data.filter(p=>p.draft);if(filter==='active')data=data.filter(p=>p.status==='active');return [...data].sort((x,y)=>sort==='registry'?x.registry_number-y.registry_number:sort==='name'?`${x.last_name}${x.first_name}`.localeCompare(`${y.last_name}${y.first_name}`,'el'):sort==='next'?(new Date(x.next_appointment?.scheduled_start||'9999-12-31').getTime()-new Date(y.next_appointment?.scheduled_start||'9999-12-31').getTime()):new Date(y.last_session?.completed_at||0).getTime()-new Date(x.last_session?.completed_at||0).getTime())},[rows,q,filter,sort]);
 return <main className="app-shell secondary-shell"><aside className={mobileNav?'sidebar mobile-open':'sidebar'}><button className="mobile-nav-close" onClick={()=>setMobileNav(false)} aria-label="Κλείσιμο μενού"><X size={20}/></button><div className="brand"><div className="brand-mark">Ψ</div><div className="brand-copy"><div className="brand-sub">Για μια οργανωμένη κλινική πράξη</div></div></div><nav className="nav"><Link href="/" className="nav-item"><Home size={19}/><span>Επισκόπηση</span></Link><Link href="/calendar" className="nav-item"><CalendarDays size={19}/><span>Ημερολόγιο</span></Link><Link href="/patients" className="nav-item active"><Users size={19}/><span>Ασθενείς</span></Link><Link href="/psychometrics" className="nav-item"><Activity size={19}/><span>Ψυχομετρικά τεστ</span></Link></nav></aside>{mobileNav&&<button className="mobile-nav-backdrop" aria-label="Κλείσιμο μενού" onClick={()=>setMobileNav(false)}/>}<section className="workspace"><header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileNav(true)} aria-label="Άνοιγμα μενού"><Menu size={21}/></button><div className="search"><span>Ψ · μητρώο ασθενών</span></div><PilotProfile/></header><div className="secondary-content registry-page"><section className="registry-wrap">
  <div className="registry-heading"><div><span className="kicker">ΚΛΙΝΙΚΟ ΜΗΤΡΩΟ</span><h1>Ασθενείς</h1><p>Οι φάκελοι του προσωπικού σας χώρου.</p></div><Link href="/patients/new" className="record"><Plus size={18}/> Νέος ασθενής</Link></div>
  {assign&&<p role="status">Επιλέξτε ασθενή για ανάθεση {assign}.</p>}<div className="registry-stats"><div><Users/><span><strong>{rows.length}</strong> ασθενείς</span></div><div><FileClock/><span><strong>{rows.filter(x=>x.draft).length}</strong> εκκρεμή πρόχειρα</span></div></div>
  <div className="registry-tools"><div className="registry-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Αναζήτηση χωρίς διάκριση τόνων..."/></div><div className="registry-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Όλοι</button><button className={filter==='active'?'active':''} onClick={()=>setFilter('active')}>Ενεργοί</button><button className={filter==='draft'?'active':''} onClick={()=>setFilter('draft')}>Με πρόχειρο</button><select value={sort} onChange={e=>setSort(e.target.value as 'registry'|'name'|'recent'|'next')} aria-label="Ταξινόμηση"><option value="registry">Α/Α · πρώτη επίσκεψη</option><option value="name">Όνομα</option><option value="recent">Τελευταία επίσκεψη</option><option value="next">Επόμενη επίσκεψη</option></select></div></div>
  {loading?<div className="registry-state">Φόρτωση ασθενών…</div>:error?<div className="registry-state error" role="alert">{error}</div>:<div className="patient-registry"><div className="registry-row registry-labels"><span>Α/Α</span><span>Ονοματεπώνυμο</span><span>ICD-10</span><span>Τελευταία</span><span>Επόμενη</span><span>Ραντεβού</span><span/></div>{filtered.map(p=><div className="registry-row" key={p.id}><span className="registry-number">{String(p.registry_number).padStart(3,'0')}</span><Link href={`/patients/demo/${p.id}${assign?'?tab=psychometrics&instrument='+encodeURIComponent(assign) :''}`} className="registry-patient registry-patient-link"><span className="registry-avatar">{p.first_name[0]}</span><div><strong>{p.first_name} {p.last_name}</strong><small>{p.reported_age?`${p.reported_age} ετών · `:''}{p.note||p.chief_complaint||'Χωρίς κλινική σύνοψη'}</small></div></Link><span className="registry-diagnosis" title={p.diagnosis?.label||''}>{p.diagnosis?<><strong>{p.diagnosis.code}</strong><small>{p.diagnosis.label}</small></>:'—'}</span><span>{formatDate(p.last_session?.completed_at)}</span><span>{formatDate(p.next_appointment?.scheduled_start)}</span><Link className="registry-appointment" href={`/calendar?patient=${encodeURIComponent(p.id)}`}>+ Νέο</Link><Link className="registry-open" aria-label={`Άνοιγμα φακέλου ${p.first_name} ${p.last_name}`} href={`/patients/demo/${p.id}${assign?'?tab=psychometrics&instrument='+encodeURIComponent(assign) :''}`}><ChevronRight size={17}/></Link></div>)}{!filtered.length&&<div className="registry-state">Δεν βρέθηκαν ασθενείς με αυτά τα φίλτρα.</div>}</div>}
 </section></div></section></main>
}
