import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';import {readFileSync} from 'node:fs';import React from 'react';import * as jsx from 'react/jsx-runtime';import {renderToStaticMarkup} from 'react-dom/server';import * as writing from '../lib/clinical/clinical-writing.ts';import {FieldRecorder} from '../lib/clinical/field-recorder.ts';
const mod={exports:{}};vm.runInNewContext(ts.transpileModule(readFileSync('components/dictation/ClinicalTextField.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{module:mod,exports:mod.exports,Symbol,require:name=>name==='react'?React:name==='react/jsx-runtime'?jsx:name==='lucide-react'?Object.fromEntries(['Check','Mic2','Pause','Play','RotateCcw','Sparkles','Square','X'].map(k=>[k,()=>React.createElement('svg',{'data-icon':k})])):name.includes('clinical-writing')?writing:name.includes('field-recorder')?{FieldRecorder}:{default:{heading:'heading',tools:'tools',field:'field'}}});
const render=(value,fullMicLabel=false)=>renderToStaticMarkup(React.createElement(mod.exports.default,{sessionId:'session',section:'assessment',fieldKey:'impression',title:'Κλινική εκτίμηση',value,placeholder:'Σημερινή κλινική εικόνα…',fullMicLabel,onChange(){},onConfirm:async()=>{},registerFlusher:()=>()=>{},onDirtyChange(){}}));
test('one accessible textarea retains confirmed text and both compact header actions',()=>{
 const html=render('Δεν αναφέρει αϋπνία.');assert.equal((html.match(/<textarea/g)||[]).length,1);assert.equal((html.match(/<button/g)||[]).length,2);assert.match(html,/for="session-assessment-impression"/);assert.match(html,/id="session-assessment-impression"/);assert.match(html,/aria-label="Υπαγόρευση: Κλινική εκτίμηση"/);assert.match(html,/title="Βελτίωση διατύπωσης"/);assert.match(html,/Δεν αναφέρει αϋπνία/);assert.doesNotMatch(html,/<dialog|Πρόταση AI|Επιβεβαίωση/);
});
test('AI is unavailable for blank text; the initial interview may retain its full microphone label',()=>{
 assert.match(render(''),/title="Βελτίωση διατύπωσης"[^>]*disabled=""/);assert.match(render('Κείμενο',true),/Υπαγόρευση<\/button>/);assert.doesNotMatch(render('Κείμενο'),/> Υπαγόρευση<\/button>/);
});
