import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';import {readFileSync} from 'node:fs';
import {isClinicalId} from '../lib/clinical/identity.ts';import * as policy from '../lib/clinical/writing-policy.ts';
const id='10000000-0000-4000-8000-000000000001';
function route(name,{sessions=[{id,status:'draft',session_type:'follow_up'}],providerText='Ο ασθενής δεν αναφέρει αϋπνία.',providerError=false}={}){
 const calls=[];const mod={exports:{}};const code=ts.transpileModule(readFileSync(`app/api/clinical/${name}/route.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 vm.runInNewContext(code,{module:mod,exports:mod.exports,Response,AbortSignal,process:{env:{OPENAI_API_KEY:'fixture',OPENAI_CLINICAL_MODEL:'configured-model'}},fetch:async(url,init)=>{calls.push({provider:JSON.parse(init.body)});return providerError?new Response('bad',{status:500}):Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({text:providerText})}]}]})},require:path=>path.includes('pilot/route')?{withPilot:fn=>async req=>{const body=await req.json();if(!body.signedIn)return Response.json({error:'auth'},{status:401});return fn(new Request(req.url,{method:'POST',body:JSON.stringify({...body,tester:'verified-workspace'})}))}}:path.includes('demo-runtime')?{request:async path=>{calls.push({path});return sessions},rpc:async(name,args)=>{calls.push({rpc:name,args});return {id:'proposal-id'}}}:path.includes('identity')?{isClinicalId}:policy});return {post:mod.exports.POST,calls};
}
const req=(body={})=>new Request('http://local/api/clinical/polish',{method:'POST',body:JSON.stringify({signedIn:true,tester:'forged',session_id:id,section:'assessment',field_key:'impression',text:'Ο ασθενής δεν αναφέρει αϋπνία.',...body})});
test('polishing verifies workspace and draft ownership before contacting a provider, and excludes numeric/coded fields',async()=>{
 for(const override of [{signedIn:false},{field_key:'dose'},{section:'scales'},{session_id:'wrong'}]){const r=route('polish');assert.ok((await r.post(req(override))).status>=400);assert.equal(r.calls.filter(c=>c.provider).length,0)}
 for(const sessions of [[],[{id,status:'completed'}]]){const r=route('polish',{sessions});assert.equal((await r.post(req())).status,404);assert.equal(r.calls.filter(c=>c.provider).length,0)}
 const r=route('polish');const response=await r.post(req());assert.equal(response.status,200);assert.match(r.calls[0].path,/tester_id=eq.verified-workspace/);const payload=r.calls[1].provider;assert.equal(payload.store,false);assert.equal(payload.model,'configured-model');assert.equal(payload.input,'Ο ασθενής δεν αναφέρει αϋπνία.');assert.match(payload.instructions,/negation, uncertainty/);assert.match(payload.instructions,/patient-reported versus clinician-observed/);assert.equal(r.calls.filter(c=>c.rpc).length,0);
});
test('polishing failure and invalid provider output never save any clinical record',async()=>{
 for(const settings of [{providerError:true},{providerText:''},{providerText:'x'.repeat(20001)}]){const r=route('polish',settings);assert.equal((await r.post(req())).status,502);assert.equal(r.calls.filter(c=>c.rpc).length,0)}
});
test('review creates provenance as an unapproved proposal; canonical approval stays in the existing versioned RPC',async()=>{
 const r=route('writing');const response=await r.post(req({section:'interview',kind:'dictation',original:'Original',text:'Reviewed',transcript:'Raw dictated text'}));assert.equal(response.status,200);const call=r.calls.find(c=>c.rpc);assert.equal(call.rpc,'demo_proposal_create');assert.equal(call.args.p_tester,'verified-workspace');assert.equal(call.args.p_model,null);assert.equal(call.args.p_proposal.clinical_text,'Reviewed');assert.equal(call.args.p_transcript,'Raw dictated text');assert.equal(r.calls.filter(c=>c.provider).length,0);
 const unavailable=route('writing',{sessions:[]});assert.equal((await unavailable.post(req({section:'interview',kind:'ai',original:'Source',transcript:'Source'}))).status,404);assert.equal(unavailable.calls.filter(c=>c.rpc).length,0);
});
