'use client';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
import {documentedChanges} from '@/lib/clinical/summary';
export default function ClinicalSummary({bundle,onSessions,onPsychometrics,onMedications,onHistory}:{bundle:PatientBundle;onSessions:(id?:string)=>void;onPsychometrics:()=>void;onMedications:()=>void;onHistory:()=>void}){
 const completed=bundle.sessions.filter(s=>s.status==='completed').sort((a,b)=>Date.parse(b.completed_at!)-Date.parse(a.completed_at!));const latest=completed[0];const changes=documentedChanges(bundle);
 const section=(key:string)=>bundle.sections.find(s=>s.session_id===latest?.id&&s.section_key===key)?.content;
 const next=bundle.appointments.find(a=>new Date(a.scheduled_start)>new Date());
 const active=bundle.medications.filter(m=>m.status==='active');
 const sideEffects=bundle.medicationSideEffects.filter(e=>!e.resolved_on);
 const h=bundle.history; const historyItems=h?[['Ψυχιατρικό',h.psychiatric_history],['Ιατρικό',h.medical_history],['Προηγούμενες θεραπείες',h.previous_treatments],['Νοσηλείες',h.hospitalizations],['Οικογενειακό',h.family_history],['Ουσίες',h.substance_history],['Κοινωνική λειτουργικότητα',h.social_functioning],['Αλλεργίες',h.allergies]].filter(([,value])=>Boolean(value)):[];
 const additions=bundle.addenda.filter(a=>completed.some(s=>s.id===a.session_id));
 const meds=completed[1]?bundle.medicationEvents.filter(e=>!bundle.medicationRevisions.some(r=>r.event_id===e.id)&&e.effective_on>completed[1].completed_at!.slice(0,10)&&e.effective_on<=latest.completed_at!.slice(0,10)):[];
 return <div className="summary-source-grid"><article className="summary-source-card"><h3>Τρέχουσα καταγεγραμμένη εικόνα</h3><p>{section('assessment')||section('interview')||'Δεν υπάρχει ολοκληρωμένη αξιολόγηση.'}</p>{latest&&<button onClick={()=>onSessions(latest.id)}>Πηγή · {new Date(latest.completed_at!).toLocaleDateString('el-GR')}</button>}{additions.length>0&&<div className="review-signal"><strong>Υπάρχουν μεταγενέστερες προσθήκες — διαβάστε μαζί με την αρχική καταγραφή.</strong>{additions.map(a=><details key={a.id}><summary>{a.kind==='correction'?'Διόρθωση':'Προσθήκη'} · {new Date(a.created_at).toLocaleDateString('el-GR')}</summary><p>{a.content}</p><button onClick={()=>onSessions(a.session_id)}>Άνοιγμα πηγής</button></details>)}</div>}</article>
 <article className="summary-source-card"><h3>Τι άλλαξε μεταξύ των δύο τελευταίων συνεδριών</h3>{completed.length<2?<p>Χρειάζονται δύο ολοκληρωμένες συνεδρίες για σύγκριση.</p>:<>{!changes.length&&!meds.length&&<p>Δεν εντοπίστηκαν διαφορές στις συγκρινόμενες καταγραφές.</p>}{changes.map(c=><details key={c.label}><summary>{c.label} · διαφορετική καταγραφή</summary><div className="source-comparison"><div><button onClick={()=>onSessions(c.beforeId)}>Προηγούμενη πηγή</button><p>{c.before}</p></div><div><button onClick={()=>onSessions(c.afterId)}>Νεότερη πηγή</button><p>{c.after}</p></div></div></details>)}{meds.map(e=><p key={e.id}>{bundle.medications.find(m=>m.id===e.medication_id)?.medication_name} · {e.effective_on} · {e.event_type==='stopped'?'Διακοπή':String(e.new_state?.dose)+' '+String(e.new_state?.unit)} <button onClick={onMedications}>Συμβάν αγωγής</button></p>)}</>}</article>
 <article className="summary-source-card"><h3>Τρέχουσα αγωγή</h3>{active.length?active.map(m=><p key={m.id}>{m.medication_name} · {m.dose} {m.unit} · {m.frequency}</p>):<p>Δεν υπάρχει καταγεγραμμένη ενεργή αγωγή.</p>}{sideEffects.length>0&&<div className="review-signal"><strong>Ενεργές καταγεγραμμένες παρενέργειες</strong>{sideEffects.slice(0,3).map(e=><p key={e.id}>{bundle.medications.find(m=>m.id===e.medication_id)?.medication_name||"Αγωγή"} · {e.effect_text}{e.impact?` · ${e.impact}`:""}</p>)}</div>}<button onClick={onMedications}>Πηγή · αγωγή, παρενέργειες και χρονολόγιο</button></article>
 <article className="summary-source-card"><h3>Επόμενα τεκμηριωμένα βήματα</h3><p>{[section('plan'),section('review')].filter(Boolean).join('\n')||'Δεν καταγράφηκαν.'}</p>{latest&&<button onClick={()=>onSessions(latest.id)}>Πηγή · πλάνο συνεδρίας</button>}<p>Επόμενο ραντεβού: {next?new Date(next.scheduled_start).toLocaleString('el-GR'):'Δεν έχει προγραμματιστεί'}</p></article>
 <article className="summary-source-card"><h3>Σχετικό καταγεγραμμένο ιστορικό</h3>{historyItems.length?historyItems.slice(0,4).map(([label,value])=><p key={label}><strong>{label}:</strong> {value}</p>):<p>Δεν υπάρχει συμπληρωμένο γενικό ιστορικό.</p>}<button onClick={onHistory}>Πηγή · πλήρες ιστορικό</button></article>\n <article className="summary-source-card"><h3>Πρόσφατα ψυχομετρικά</h3>{(['PHQ-9','GAD-7'] as const).map(code=>{const a=bundle.assessments.find(a=>a.instrument===code&&a.status==='completed');return <p key={code}>{code}: {a?`${a.score} · ${new Date(a.completed_at!).toLocaleDateString('el-GR')}`:'Δεν υπάρχει αποτέλεσμα'}{a?.item9_review&&<strong> · Λήμμα 9 προς έλεγχο</strong>}</p>})}<button onClick={onPsychometrics}>Πηγή · απαντήσεις και ιστορικό</button></article></div>
}
