'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarDays,ChevronRight,Mic2,Sparkles} from 'lucide-react';
import type {DemoSession,PatientBundle} from '@/lib/patients/demo-runtime';
import {appendDictationText} from '@/lib/clinical/dictation-text';
import {emptyContinuity,validContinuity,mergeContinuityProposal,type ContinuityDraft} from '@/lib/clinical/continuity';
import {mseTimeline,previousMseReference,finalizationBlocker} from '@/lib/clinical/visit-workspace-state';
import {demoPost} from '@/lib/patients/demo-client';
import {getDemoTesterId} from '@/lib/demo-tester';
import {useClinicalDraft} from './useClinicalDraft';
import SectionDictation from '@/components/dictation/SectionDictation';
import RiskEditor from './RiskTreeEditor';
import StructuredVisitEditor from './StructuredVisitEditor';
import {MedicationModal} from './PatientPanels';
import VisitScores from './VisitScores';
import VisitNextAppointment from './VisitNextAppointment';
import {formatClinicDate} from '@/lib/clinic-time';
import {continuityContexts} from '@/lib/clinical/continuity-context';
import StableDetails from './StableDetails';
import styles from './FollowupClosure.module.css';

type Props={bundle:PatientBundle;session:DemoSession;reload:()=>Promise<unknown>;reloadContext:()=>Promise<unknown>;contextReady:boolean;registerFlusher:(key:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(key:string,dirty:boolean)=>void;flushAll:(requireRefresh?:boolean)=>Promise<unknown>;onDetailed:()=>void;onFinalize:(version:number)=>Promise<void>;onFinishLater?:()=>Promise<void>;finalizing:boolean;finalizeError:string};
export default function FollowupClosure(p:Props){
 const {bundle,session,registerFlusher,onDirtyChange}=p;
 const text=(key:string)=>bundle.sections.find(s=>s.session_id===session.id&&s.section_key===key)?.content||'';
 const initial:ContinuityDraft=session.closure_draft||{...emptyContinuity,clinical_state_summary:text('interview'),treatment_decision:text('plan'),next_review_focus:text('review'),adherence:text('adherence')};
 const draft=useClinicalDraft<ContinuityDraft>({storageKey:session.id+':closure',initial,version:session.closure_version||0,write:async(value,version)=>{const result=await demoPost({action:'save_closure',session_id:session.id,value,expected_version:version});return {value:result.session.closure_draft,version:result.session.closure_version}},onSaved:p.reload,onDirty:dirty=>onDirtyChange('closure',dirty)});
 useEffect(()=>registerFlusher('closure',draft.flush),[registerFlusher,draft.flush]);
 const [dictating,setDictating]=useState(false),[extracting,setExtracting]=useState(false),[error,setError]=useState(''),[proposal,setProposal]=useState<ContinuityDraft|null>(null),[includeSuggestedContext,setIncludeSuggestedContext]=useState(false),[busy,setBusy]=useState(false);
 const [contextTarget,setContextTarget]=useState('new');
 const contextRequest=useRef<{key:string;id:string}|null>(null);
 const [proposalRecoveryReady,setProposalRecoveryReady]=useState(false);
 const proposalRecoveryKey='noima-closure-proposal:'+session.id;
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(proposalRecoveryKey)||'null');if(saved&&validContinuity(saved)&&saved.transcript===draft.value.transcript)setProposal(saved)}catch{}setProposalRecoveryReady(true)},[proposalRecoveryKey]);
 useEffect(()=>{if(proposalRecoveryReady)try{if(proposal)sessionStorage.setItem(proposalRecoveryKey,JSON.stringify(proposal));else sessionStorage.removeItem(proposalRecoveryKey)}catch{}},[proposal,proposalRecoveryReady,proposalRecoveryKey]);
 const flight=useRef(false),transcriptInput=useRef<HTMLTextAreaElement>(null),proposalFlight=useRef(false);
 const draftValue=useRef(draft.value);draftValue.current=draft.value;
 const dictatingRef=useRef(dictating);dictatingRef.current=dictating;
 const proposalRef=useRef(proposal);proposalRef.current=proposal;
 useEffect(()=>registerFlusher('closure-review',async()=>{if(dictatingRef.current)throw new Error('Ολοκληρώστε ή κλείστε την υπαγόρευση πριν συνεχίσετε.');if(proposalRef.current)throw new Error('Χρησιμοποιήστε ή απορρίψτε πρώτα την καταγραφή προς έλεγχο.')}),[registerFlusher]);
 const [med,setMed]=useState<{mode:'start'|'change'|'stop'|'side_effect';id?:string}|null>(null);
 useEffect(()=>registerFlusher('closure-medication',async()=>{if(med)throw new Error('Ολοκληρώστε πρώτα την καταχώρηση αγωγής.')}),[registerFlusher,med]);
 function change(key:keyof ContinuityDraft,value:string){draft.change({...draft.value,[key]:value})}
 async function extract(){if(proposalFlight.current)return;proposalFlight.current=true;setExtracting(true);setError('');try{const snapshot=draft.value.transcript;const r=await fetch('/api/clinical/closure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tester:getDemoTesterId(),session_id:session.id,transcript:snapshot})});const result=await r.json();if(!r.ok)throw new Error(result.error);if(!validContinuity(result.proposal))throw new Error('Η πρόταση δεν ήταν έγκυρη.');setIncludeSuggestedContext(false);setContextTarget('new');setProposal(result.proposal)}catch(e){setError(e instanceof Error?e.message:'Δεν δημιουργήθηκε πρόταση.')}finally{proposalFlight.current=false;setExtracting(false)}}
 async function applyProposal(){if(!proposal||proposalFlight.current)return;proposalFlight.current=true;setExtracting(true);setError('');try{if(includeSuggestedContext&&contextTarget!=='new'){const item=continuityContexts(bundle).find(i=>i.id===contextTarget&&i.status==='active');if(!item)throw new Error('Το ενεργό θέμα άλλαξε. Ανανεώστε την καταγραφή.');const key=item.id+':'+proposal.pinned_context;if(contextRequest.current?.key!==key)contextRequest.current={key,id:crypto.randomUUID()};await demoPost({action:'revise_context',source_session_id:item.id,request_id:contextRequest.current.id,context_action:'updated',content:proposal.pinned_context,expected_revision:item.revision});await p.reloadContext()}draft.change(mergeContinuityProposal(draftValue.current,proposal,{includeSuggestedContext:includeSuggestedContext&&contextTarget==='new'}));setProposal(null);setIncludeSuggestedContext(false)}catch(e){setError(e instanceof Error?e.message:'Η καταγραφή προς έλεγχο διατηρείται.')}finally{proposalFlight.current=false;setExtracting(false)}}
 async function finalize(){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{const fresh=await p.flushAll(true) as PatientBundle;const timeline=mseTimeline(fresh,session.id,session.started_at);const sections=fresh.sections.filter(s=>s.session_id===session.id);const blocker=finalizationBlocker([...sections,...['interview','assessment','plan','review'].filter(k=>!sections.some(s=>s.section_key===k&&s.content.trim())).map(k=>({section_key:k,content:'Επιβεβαιωμένη κλινική μνήμη'}))],fresh.risks.find(r=>r.session_id===session.id),{kind:'mse',fields:Object.values(timeline.references).map(r=>r.field)});if(blocker)throw new Error(blocker.message);await p.onFinalize(draft.version()||0)}catch(e){setError(e instanceof Error?e.message:'Δεν ολοκληρώθηκε η επίσκεψη.')}finally{flight.current=false;setBusy(false)}}
 const risk=bundle.risks.find(r=>r.session_id===session.id);
 const mse=bundle.sections.find(s=>s.session_id===session.id&&s.section_key==='mse');
 const reference=previousMseReference(bundle,session.id,session.started_at);
 const contextItems=continuityContexts(bundle).filter(i=>i.status==='active');
 const activeMedications=bundle.medications.filter(m=>m.status==='active');
 const medicationChanges=bundle.medicationEvents.filter(e=>e.session_id===session.id&&e.event_type==='changed'&&!(bundle.medicationRevisions||[]).some(r=>r.event_id===e.id));
 const timeline=p.contextReady?mseTimeline(bundle,session.id,session.started_at):undefined;
 return <section className={styles.closure}>
  <header className={styles.heading}><div><span className="kicker">ΕΠΑΝΕΞΕΤΑΣΗ</span><h2>Σημερινή καταγραφή</h2></div><button type="button" onClick={p.onDetailed} disabled={busy||extracting}>Αναλυτική καταγραφή <ChevronRight size={15} aria-hidden="true"/></button></header>
  <section className={styles.card} aria-label="Υπαγόρευση ή καταγραφή επίσκεψης">
   <div className={styles.cardHeading}><h3>Σημειώσεις επίσκεψης</h3><span className={styles.cardMeta}>Με φωνή ή πληκτρολόγηση</span></div>
   <label className={styles.fieldLabel}><span className={styles.visuallyHidden}>Σημερινές σημειώσεις</span><textarea ref={transcriptInput} maxLength={20000} rows={4} value={draft.value.transcript} disabled={extracting} onChange={e=>change('transcript',e.target.value)} placeholder="Τι ανέφερε ο ασθενής, ποια ήταν η πορεία του, τι άλλαξε σήμερα…"/></label>
   <div className={styles.actions}><button type="button" onClick={()=>setDictating(true)} disabled={extracting}><Mic2 size={16} aria-hidden="true"/> Υπαγόρευση</button><button type="button" disabled={extracting} onClick={()=>transcriptInput.current?.focus()}>Πληκτρολόγηση</button><button type="button" className={styles.actionPrimary} onClick={()=>void extract()} disabled={extracting||draft.value.transcript.trim().length<2}><Sparkles size={16} aria-hidden="true"/>{extracting?'Οργάνωση…':'Οργάνωση με AI'}</button></div>
  </section>
  {proposal&&<section className={styles.proposal}><h3>Καταγραφή προς έλεγχο</h3>{(['clinical_state_summary','treatment_decision','next_review_focus','adherence'] as const).filter(k=>k!=='adherence'||activeMedications.length>0||Boolean(proposal.adherence)).map(k=><label key={k}><strong>{{clinical_state_summary:'Κλινική αποτίμηση',treatment_decision:'Θεραπευτική απόφαση',next_review_focus:'Επόμενος έλεγχος',adherence:'Λήψη αγωγής'}[k]}: </strong><textarea value={proposal[k]} rows={2} placeholder="Δεν αναφέρθηκε — η υπάρχουσα καταγραφή διατηρείται." disabled={extracting} onChange={e=>setProposal({...proposal,[k]:e.target.value})}/></label>)}{proposal.pinned_context.trim()&&<label className={styles.confirm}><input type="checkbox" checked={includeSuggestedContext} disabled={extracting} onChange={e=>setIncludeSuggestedContext(e.target.checked)}/>Να διατηρηθεί ως σημαντικό ενεργό θέμα: {proposal.pinned_context}</label>}{includeSuggestedContext&&<label>Θέμα προς διατήρηση<textarea maxLength={2000} rows={2} disabled={extracting} value={proposal.pinned_context} onChange={e=>setProposal({...proposal,pinned_context:e.target.value})}/></label>}{includeSuggestedContext&&contextItems.length>0&&<label>Σχέση με ενεργό θέμα<select value={contextTarget} disabled={extracting} onChange={e=>setContextTarget(e.target.value)}><option value="new">Νέο ξεχωριστό θέμα</option>{contextItems.map(i=><option key={i.id} value={i.id}>Ενημέρωση: {i.content}</option>)}</select><small>Η ενημέρωση υπάρχοντος θέματος διατηρεί την αρχική πηγή και δεν δημιουργεί δεύτερο pin.</small></label>}<button type="button" disabled={extracting} onClick={()=>void applyProposal()}>{includeSuggestedContext&&contextTarget!=='new'?'Χρήση & ενημέρωση ενεργού θέματος':'Χρήση στην καταγραφή'}</button><button type="button" disabled={extracting} onClick={()=>setProposal(null)}>Απόρριψη</button></section>}
  <section className={styles.card}><div className={styles.cardHeading}><h3>Κλινική καταγραφή</h3></div><div className={styles.fields}>{([['clinical_state_summary','Κλινική εικόνα'],['treatment_decision','Θεραπευτική απόφαση'],['next_review_focus','Στην επόμενη επίσκεψη']] as const).map(([k,label])=><label key={k}>{label}<textarea disabled={extracting} rows={2} value={draft.value[k]} onChange={e=>change(k,e.target.value)} placeholder={{clinical_state_summary:'Συμπτώματα, λειτουργικότητα, μεταβολές…',treatment_decision:'Αγωγή, παρεμβάσεις ή αλλαγές στο πλάνο…',next_review_focus:'Τι χρειάζεται να επανεκτιμηθεί…'}[k]}/>{!draft.value[k].trim()&&k==='treatment_decision'&&<button type="button" onClick={()=>change('treatment_decision','Δεν ελήφθη νέα θεραπευτική απόφαση στη σημερινή επίσκεψη.')}>Δεν ελήφθη νέα απόφαση</button>}{!draft.value[k].trim()&&k==='next_review_focus'&&<button type="button" onClick={()=>change('next_review_focus','Δεν ορίστηκε συγκεκριμένος επόμενος έλεγχος στη σημερινή επίσκεψη.')}>Δεν ορίστηκε επόμενος έλεγχος</button>}</label>)}</div></section>
  {p.contextReady?(activeMedications.length>0||draft.value.adherence.trim()?<section className={styles.card}><h3>Λήψη αγωγής</h3>{!draft.value.adherence&&<div className={styles.actions}>{['Κανονική λήψη','Υπήρξε θέμα','Δεν αξιολογήθηκε'].map(label=><button type="button" key={label} onClick={()=>change('adherence',label)}>{label}</button>)}</div>}<label>Σημερινή ανασκόπηση λήψης<input disabled={extracting} value={draft.value.adherence} onChange={e=>change('adherence',e.target.value)}/></label></section>:null):<p role="status">Φόρτωση αγωγής…</p>}
  <section className={styles.card}><h3>Τρέχουσα αγωγή</h3>{p.contextReady&&activeMedications.length>1&&<button type="button" onClick={()=>change('treatment_decision','Συνέχιση της καταχωρισμένης αγωγής χωρίς αλλαγή: '+activeMedications.map(m=>m.medication_name+' '+m.dose+' '+m.unit+' · '+m.frequency).join('; ')+'.')}>Χωρίς αλλαγή στην καταχωρισμένη αγωγή</button>}{medicationChanges.map(e=><p key={e.id}>Αλλαγή: {String(e.new_state?.medication_name||'Αγωγή')} · {String(e.previous_state?.dose??'—')} {String(e.previous_state?.unit||'')} → {String(e.new_state?.dose??'—')} {String(e.new_state?.unit||'')} · Ισχύει από {formatClinicDate(e.effective_on)}</p>)}{p.contextReady?<>{activeMedications.map(m=><div className={styles.medication} key={m.id}><span>{m.medication_name} · {m.dose} {m.unit} · {m.frequency}</span><button type="button" onClick={()=>change('treatment_decision','Συνέχιση '+m.medication_name+' '+m.dose+' '+m.unit+' · '+m.frequency+' χωρίς αλλαγή.')}>Χωρίς αλλαγή</button><button type="button" onClick={()=>setMed({mode:'change',id:m.id})}>Αλλαγή</button><button type="button" onClick={()=>setMed({mode:'side_effect',id:m.id})}>Παρενέργεια</button></div>)}<button type="button" onClick={()=>setMed({mode:'start'})}>Προσθήκη αγωγής</button></>:<p role="status">Φόρτωση αγωγής…</p>}</section>
  <StableDetails key={session.id+':mse'} className={styles.details} initialOpen={!mse?.content.trim()}><summary>MSE · {mse?.content.trim()?'Καταγεγραμμένο — έλεγχος':'Χρειάζεται σημερινή ανασκόπηση'}</summary>{p.contextReady?<StructuredVisitEditor sessionId={session.id} kind="mse" compact existing={mse} followup baseline={reference?.section} timeline={timeline} onSaved={p.reload} registerFlusher={registerFlusher} onDirtyChange={onDirtyChange}/>:<p>Φόρτωση προηγούμενου MSE…</p>}</StableDetails>
  <StableDetails key={session.id+':risk'} className={styles.details} initialOpen={!risk||risk.suicidal_ideation==='not_assessed'||risk.suicidal_ideation==='positive'}><summary>Κίνδυνος · {risk&&risk.suicidal_ideation!=='not_assessed'?'Σημερινή καταγραφή':'Χρειάζεται σημερινή εκτίμηση'}</summary><RiskEditor sessionId={session.id} existing={risk} onSaved={p.reload} registerFlusher={registerFlusher} onDirtyChange={onDirtyChange}/></StableDetails>
  <details className={styles.details}><summary>Ψυχομετρικές μετρήσεις</summary>{p.contextReady&&<VisitScores bundle={bundle} sessionId={session.id} reload={p.reloadContext}/>}</details>
  <details className={styles.details}><summary>Σημαντικά θέματα για τη συνέχεια{contextItems.length?' · '+contextItems.length:''}</summary>
    {contextItems.map(item=><p className={styles.contextItem} key={item.id}>{item.content}</p>)}
    <label className={styles.fieldLabel}>Τι αξίζει να θυμόμαστε<textarea maxLength={2000} rows={2} value={draft.value.pinned_context} onChange={e=>change('pinned_context',e.target.value)} placeholder="Π.χ. σημαντικό γεγονός, εκκρεμότητα ή προσωπικό θέμα που επηρεάζει την πορεία…"/></label>
  </details>
  {p.contextReady&&<section className={styles.appointmentCard} aria-label="Επόμενο ραντεβού"><div className={styles.appointmentHeading}><CalendarDays size={21} aria-hidden="true"/><h3>Επόμενο ραντεβού</h3></div><VisitNextAppointment bundle={bundle} reload={p.reloadContext} registerFlusher={registerFlusher} onDirtyChange={onDirtyChange}/></section>}
  <p role="status">{draft.saving?'Αποθήκευση προχείρου…':draft.error||(draft.savedAt?'Πρόχειρο αποθηκευμένο · '+draft.savedAt:'')}</p>
  {draft.error&&<button type="button" onClick={()=>void p.reload().then(b=>{const s=(b as PatientBundle).sessions.find(s=>s.id===session.id);if(s){draft.acceptServer(s.closure_draft||emptyContinuity,s.closure_version||0)}}).catch(e=>setError(e.message))}>Φόρτωση αποθηκευμένου προχείρου</button>}
  {(error||p.finalizeError)&&<p role="alert">{error||p.finalizeError}</p>}
  <div className={styles.footerActions}><button type="button" className={styles.actionPrimary} disabled={busy||p.finalizing||extracting||Boolean(med)||!p.contextReady} onClick={()=>void finalize()}>{busy||p.finalizing?'Οριστικοποίηση…':'Ολοκλήρωση καταγραφής'}</button>{p.onFinishLater&&<button type="button" disabled={busy||p.finalizing||extracting||Boolean(med)} onClick={()=>void p.onFinishLater?.()}>Συνέχεια αργότερα</button>}</div>
  {dictating&&<SectionDictation storageKey={session.id+':closure'} title="Σημερινή επίσκεψη" onClose={()=>setDictating(false)} onInsert={t=>{change('transcript',appendDictationText(draftValue.current.transcript,t));setDictating(false)}}/>}
  {med&&<MedicationModal bundle={bundle} sessionId={session.id} initialMode={med.mode} initialMedicationId={med.id} onClose={()=>setMed(null)} onSaved={async()=>{await p.reloadContext();setMed(null)}}/>}
 </section>;
}
