'use client';
import {useState} from 'react';
import type {PatientBundle,DemoMedicationEvent} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
export default function MedicationTimeline({bundle,reload}:{bundle:PatientBundle;reload:()=>Promise<unknown>}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [editing,setEditing]=useState<DemoMedicationEvent|null>(null),[dose,setDose]=useState(''),[unit,setUnit]=useState(''),[frequency,setFrequency]=useState(''),[date,setDate]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function open(e:DemoMedicationEvent){setEditing(e);setDose(String(e.new_state?.dose||''));setUnit(String(e.new_state?.unit||'mg'));setFrequency(String(e.new_state?.frequency||''));setDate(e.effective_on);setReason('');setError('')}
 async function save(cancel:boolean){if(!editing)return;setBusy(true);setError('');try{const m=bundle.medications.find(m=>m.id===editing.medication_id)!;await demoPost({action:'medication_event',medication_id:m.id,event_type:editing.event_type,dose:Number(dose),unit,frequency,effective_on:date,reason,expected_version:m.plan_version,replace_id:editing.id,cancel});await reload();setEditing(null)}catch(e){setError(e instanceof Error?e.message:'Δεν αποθηκεύτηκε')}finally{setBusy(false)}}
 const revised=(id:string)=>bundle.medicationRevisions.find(r=>r.event_id===id);
 function row(e:DemoMedicationEvent){const revision=revised(e.id);const m=bundle.medications.find(m=>m.id===e.medication_id);return <article className="med-event-row" key={e.id}><strong>{m?.medication_name} · {e.effective_on}</strong><p>{e.event_type==='stopped'?'Διακοπή':e.event_type==='started'?'Έναρξη':'Αλλαγή δόσης'} · {String(e.new_state?.dose||'')} {String(e.new_state?.unit||'')} · {String(e.new_state?.frequency||'')}</p><p>{e.reason}</p>{revision?<small>{revision.replacement_id?'Αντικαταστάθηκε':'Ακυρώθηκε'} · {revision.reason}</small>:<button onClick={()=>open(e)}>{e.effective_on>today?'Επεξεργασία / ακύρωση σχεδίου':'Καταχώρηση διόρθωσης'}</button>}</article>}
 return <><section className="med-events"><h3>Προγραμματισμένες αλλαγές</h3>{bundle.medicationEvents.filter(e=>e.effective_on>today&&!revised(e.id)).map(row)}</section><section className="med-events"><h3>Ιστορικό αγωγής</h3>{bundle.medicationEvents.filter(e=>e.effective_on<=today||revised(e.id)).map(row)}</section>
 {editing&&<section className="proposal-review"><h4>{editing.effective_on>today?'Αλλαγή προγραμματισμένου συμβάντος':'Διόρθωση ιστορικού συμβάντος'}</h4><p>Το αρχικό συμβάν διατηρείται στο ιστορικό.</p><label>Ημερομηνία<input disabled={busy} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{editing.event_type!=='stopped'&&<><label>Δόση<input disabled={busy} value={dose} onChange={e=>setDose(e.target.value.replace(',','.'))}/></label><label>Μονάδα<input disabled={busy} value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Συχνότητα<input disabled={busy} value={frequency} onChange={e=>setFrequency(e.target.value)}/></label></>}<label>Αιτία<input disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy||!reason.trim()} onClick={()=>void save(false)}>Επιβεβαίωση αντικατάστασης</button>{editing.effective_on>today&&<button disabled={busy||!reason.trim()} onClick={()=>void save(true)}>Ακύρωση προγραμματισμένου συμβάντος</button>}<button disabled={busy} onClick={()=>setEditing(null)}>Κλείσιμο</button></section>}
 </>
}
