'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {DemoMedication,PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {formatClinicDate} from '@/lib/clinic-time';
type Mode='start'|'history'|'change'|'stop'|'side_effect';
type Tracking={registerFlusher?:(key:string,flush:()=>Promise<void>)=>(()=>void);onDirtyChange?:(key:string,dirty:boolean)=>void};
export default function MedicationTable({bundle,sessionId,onManage,reload,editableEffects=false,registerFlusher,onDirtyChange}:{bundle:PatientBundle;sessionId?:string;onManage?:(mode:Mode,id?:string)=>void;reload:()=>Promise<unknown>;editableEffects?:boolean}&Tracking){
 const today=bundle.clinical_day||new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <div className="clinical-table-wrap"><table className="clinical-lean-table medication-lean-table"><caption>Αγωγή · τρέχουσα και προηγούμενη</caption><thead><tr><th>Φάρμακο</th><th>Δόση</th><th>Συχνότητα</th><th>Περίοδος / διάρκεια</th><th>Κατάσταση</th><th>Παρενέργειες</th>{onManage&&<th><span className="sr-only">Ενέργειες</span></th>}</tr></thead><tbody>{bundle.medications.map(m=>{const start=m.started_at.slice(0,10),end=m.ended_at?.slice(0,10);const days=Math.floor((Date.parse(end||today)-Date.parse(start))/86400000);const effects=bundle.medicationSideEffects.filter(e=>e.medication_id===m.id);return <tr key={m.id}><th scope="row">{m.medication_name}{m.notes&&<small>{m.notes}</small>}</th><td>{m.dose} {m.unit}</td><td>{m.frequency}</td><td><span>{formatClinicDate(start)}{end?' – '+formatClinicDate(end):''}</span><small>{m.status==='planned'?'Προγραμματισμένη έναρξη':days>0?days+(days===1?' ημέρα':' ημέρες'):days===0?'Έναρξη σήμερα':''}</small></td><td><span className={'med-status '+m.status}>{m.status==='active'?'Λαμβάνει':m.status==='stopped'?'Διακοπείσα':'Προγραμματισμένη'}</span></td><td>{effects.map(e=><div className={'med-effect '+(e.resolved_on?'resolved':'')} key={e.id}><span>{e.effect_text}</span><small>{e.severity==='severe'?'Σοβαρή':e.severity==='mild'?'Ήπια':'Μέτρια'} · {formatClinicDate(e.noted_on)}{e.resolved_on?' · επιλύθηκε '+formatClinicDate(e.resolved_on):''}</small></div>)}{!effects.length&&<small>Δεν υπάρχει δομημένη καταγραφή</small>}{editableEffects&&<SideEffectEntry medication={m} sessionId={sessionId} today={today} reload={reload} registerFlusher={registerFlusher} onDirtyChange={onDirtyChange}/>}</td>{onManage&&<td className="med-row-actions">{m.status!=='stopped'&&<><button type="button" onClick={()=>onManage('change',m.id)}>Αλλαγή</button><button type="button" onClick={()=>onManage('stop',m.id)}>Διακοπή</button></>}</td>}</tr>})}{!bundle.medications.length&&<tr><td colSpan={onManage?7:6} className="med-empty">Δεν έχει καταγραφεί αγωγή. Προσθέστε φάρμακο που λαμβάνει τώρα ή προηγούμενη θεραπεία.</td></tr>}</tbody></table></div>;
}
function SideEffectEntry({medication,sessionId,today,reload,registerFlusher,onDirtyChange}:{medication:DemoMedication;sessionId?:string;today:string;reload:()=>Promise<unknown>}&Tracking){
 const [text,setText]=useState(''),[severity,setSeverity]=useState(''),[date,setDate]=useState(today),[saving,setSaving]=useState(false),[error,setError]=useState('');const flight=useRef(false),pending=useRef(false);const key='medication-effect:'+medication.id;pending.current=Boolean(text.trim())||saving;
 const flush=useCallback(async()=>{if(pending.current)throw new Error('Αποθηκεύστε ή ακυρώστε την παρενέργεια του '+medication.medication_name+'.')},[medication.medication_name]);
 useEffect(()=>registerFlusher?.(key,flush),[key,registerFlusher,flush]);
 useEffect(()=>{onDirtyChange?.(key,pending.current);return()=>onDirtyChange?.(key,false)},[key,text,saving,onDirtyChange]);
 async function save(){if(flight.current)return;if(text.trim().length<2||!severity||!date){setError('Συμπληρώστε περιγραφή, βαρύτητα και ημερομηνία.');return}flight.current=true;setSaving(true);setError('');try{await demoPost({action:'medication_side_effect',medication_id:medication.id,session_id:sessionId||null,effect:text,severity,noted_on:date});setText('');setSeverity('');await reload()}catch(e){setError(e instanceof Error?e.message:'Δεν αποθηκεύτηκε η παρενέργεια.')}finally{flight.current=false;setSaving(false)}}
 return <div className="med-inline-effect"><textarea rows={1} aria-label={'Νέα παρενέργεια — '+medication.medication_name} placeholder="＋ Παρενέργεια…" value={text} disabled={saving} onChange={e=>setText(e.target.value)}/>{text&&<><div className="med-effect-controls"><select aria-label={'Βαρύτητα — '+medication.medication_name} value={severity} disabled={saving} onChange={e=>setSeverity(e.target.value)}><option value="">Βαρύτητα</option><option value="mild">Ήπια</option><option value="moderate">Μέτρια</option><option value="severe">Σοβαρή</option></select><input type="date" aria-label={'Ημερομηνία παρενέργειας — '+medication.medication_name} value={date} disabled={saving} onChange={e=>setDate(e.target.value)}/></div><button type="button" disabled={saving} onClick={()=>void save()}>{saving?'Αποθήκευση…':'Αποθήκευση'}</button><button type="button" disabled={saving} onClick={()=>{setText('');setSeverity('');setError('')}}>Ακύρωση</button></>}{error&&<p role="alert">{error}</p>}</div>;
}
