'use client';
import {mseItems,type DocumentField} from '@/lib/clinical/visit-document';
import {mseAxes,axisValues,toggleMseChoice,mseNote,replaceMseNote} from '@/lib/clinical/mse-options';
export default function MseDomain({field,previousField,onChange,onBlur}:{field:DocumentField;previousField?:DocumentField;onChange:(text:string)=>void;onBlur:()=>void}){
 const hint=mseItems.find(([key])=>key===field.key)?.[2];
 const changed=Boolean(previousField&&field.text!==previousField.text);
 const previousValues=(axis:Parameters<typeof axisValues>[1])=>previousField?axisValues(previousField.text,axis):[];
 return <details className={'mse-item '+(field.text?'has-value ':'')+(changed?'mse-changed':'')}><summary><span>{field.label}<b aria-hidden="true">⌄</b></span><small className="mse-guide">{hint}</small>{previousField&&<small className={'mse-delta-label '+(changed?'changed':'same')}>{changed?'1+ αλλαγές':'· ίδιο'}</small>}{field.text&&<small className="mse-preview">{field.text.replaceAll('\n',' · ')}</small>}</summary><div className="mse-body">{(mseAxes[field.key]||[]).map(axis=><fieldset className="mse-axis" key={axis.label}><legend>{axis.label}</legend><div className="mse-options">{axis.options.map(option=>{const current=axisValues(field.text,axis).includes(option),wasPrevious=previousValues(axis).includes(option);return <button type="button" key={option} className={wasPrevious?'was-previous':''} aria-pressed={current} onClick={()=>onChange(toggleMseChoice(field.text,axis,option))}>{option}{wasPrevious&&<small>πριν</small>}</button>})}</div></fieldset>)}{field.key==='thought_content'&&<p>SI / HI: τεκμηρίωση στην ενότητα Risk. Πρόσθετη περιγραφή μπορεί να καταγραφεί εδώ.</p>}{field.key==='cognition'&&<p>Καταγράψτε όσα εξετάστηκαν· εκτελεστικές λειτουργίες και αφαίρεση όπου ενδείκνυται.</p>}<label className="mse-note-label">{field.key==='mood'?'Καταγραφή / διατύπωση ασθενούς':'Καταγραφή & επεξηγήσεις'}<textarea aria-label={field.label+' — καταγραφή'} rows={3} value={mseNote(field.text,field.key)} onChange={e=>onChange(replaceMseNote(field.text,field.key,e.target.value))} onBlur={onBlur} placeholder="Ελεύθερη περιγραφή, παραδείγματα ή διευκρινίσεις…"/></label></div></details>;
}
