'use client';
import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronRight, History, Pill, Plus, TestTube2, X } from 'lucide-react';
import type { PatientBundle } from '@/lib/patients/demo-runtime';
import { demoPost } from '@/lib/patients/demo-client';

const date=(value?:string|null)=>value?new Intl.DateTimeFormat('el-GR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'—';
const section=(bundle:PatientBundle,sessionId:string,key:string)=>bundle.sections.find(x=>x.session_id===sessionId&&x.section_key===key)?.content||'';
export function SummaryPanel({bundle,onStart,onHistory,onSessions}:{bundle:PatientBundle;onStart:()=>void;onHistory:()=>void;onSessions:(sessionId?:string)=>void}){
 const completed=bundle.sessions.filter(x=>x.status==='completed'); const latest=completed[0]; const previous=completed[1]; const active=bundle.medications.filter(x=>x.status==='active');
 if(!latest)return <section className="empty-clinical-state"><span className="kicker">ΣΥΝΟΨΗ</span><h2>Δεν υπάρχει ακόμη ολοκληρωμένη αξιολόγηση</h2><p>Η σύνοψη δεν συμπληρώνεται με στατικό περιεχόμενο. Θα δημιουργηθεί μόνο αποριστικοποιημένη συνεδρία και δομημένη αγωγή.</p><button className="record" onClick={onStart}><Plus size={16}/> Έναρξη αρχικής αξιολόγησης</button><button className="text-button" onClick={onHistory}>Καταχώρηση ιστορικού <ChevronRight size={15}/></button></section>;
 const current=section(bundle,latest.id,'assessment')||section(bundle,latest.id,'interview'); const plan=section(bundle,latest.id,'plan'); const review=section(bundle,latest.id,'review'); const changed=previous?`Νεότερη οριστικοποιημένη συνεδρία σε σχέση με ${date(previous.completed_at)}. Ανοίξτε την πηγή για κλινική σύγκριση.`:'Δεν υπάρχει προηγούμενη ολοκληρωμένη συνεδρία για σύγκριση.';
 return <div className="summary-source-grid"><SummaryCard title="Τρέχουσα εικόνα" text={current||'Δεν καταγράφηκε κλινική εκτίμηση.'} source={`Συνεδρία · ${date(latest.completed_at)}`} onSource={()=>onSessions(latest.id)}/><SummaryCard title="Τι άλλαξε" text={changed} source={previous?`Προηγούμενη συνεδρία · ${date(previous.completed_at)}`:'Χωρίς προηγούμενη πηγή'} onSource={previous?()=>onSessions(previous.id):undefined}/><SummaryCard title="Ενεργή αγωγή" text={active.length?active.map(m=>`${m.medication_name} ${m.dose} ${m.unit} · ${m.frequency}`).join('\n'):'Δεν υπάρχει ενεργή αγωγή.'} source={active.length?`Αγωγή · ενημέρωση ${date(active[0].updated_at)}`:'Αγωγή'} /><SummaryCard title="Επόμενα βήματα" text={[plan,review].filter(Boolean).join('\n')||'Δεν καταγράφηκαν επόμενα βήματα.'} source={`Συνεδρία · ${date(latest.completed_at)}`} onSource={()=>onSessions(latest.id)}/></div>
}
function SummaryCard({title,text,source,onSource}:{title:string;text:string;source:string;onSource?:()=>void}){return <article className="summary-source-card"><h3>{title}</h3><p>{text}</p><button onClick={onSource} disabled={!onSource}><CalendarDays size={13}/>{source}</button></article>}

const historyFields=[['psychiatric_history','Ψυχιατρικό ιστορικό'],['medical_history','Σωματικό ιστορικό'],['previous_treatments','Προηγούμενες θεραπείες'],['hospitalizations','Νοσηλείες'],['family_history','Οικογενειακό ιστορικό'],['substance_history','Ουσίες'],['social_functioning','Κοινωνική λειτουργικότητα'],['allergies','Αλλεργίες']] as const;
export function HistoryPanel({bundle,reload}:{bundle:PatientBundle;reload:()=>Promise<unknown>}){
 const initial=Object.fromEntries(historyFields.map(([key])=>[key,bundle.history?.[key]||''])) as Record<string,string>; const [values,setValues]=useState(initial); const [saving,setSaving]=useState(false); const [state,setState]=useState('');
 useEffect(()=>setValues(Object.fromEntries(historyFields.map(([key])=>[key,bundle.history?.[key]||'']))),[bundle.history]);
 async function save(){setSaving(true);setState('');try{await demoPost({action:'save_history',patient_id:bundle.patient.id,history:values});setState('Αποθηκεύτηκε');await reload()}catch(cause){setState(cause instanceof Error?cause.message:'Αποτυχία αποθήκευσης')}finally{setSaving(false)}}
 return <section className="panel-stack"><div className="panel-heading"><div><span className="kicker">ΙΣΤΟΡΙΚΟ</span><h2>Στοχευμένη καταγραφή ιστορικού</h2><p>Κενό πεδίο σημαίνει «δεν έχει καταγραφεί» — ποτέ αρνητικό εύρημα.</p></div><button className="record compact" onClick={()=>void save()} disabled={saving}>{saving?'Αποθήκευση…':'Αποθήκευση'}</button></div>{state&&<div className={state==='Αποθηκεύτηκε'?'save-state ok':'save-state error'}>{state}</div>}<div className="history-editor-grid">{historyFields.map(([key,label])=><label key={key}>{label}<textarea rows={4} value={values[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} placeholder="Δεν έχει καταγραφεί"/></label>)}</div></section>
}

export function MedicationsPanel({bundle,onAdd}:{bundle:PatientBundle;onAdd:()=>void}){const active=bundle.medications.filter(x=>x.status==='active');return <section className="panel-stack"><div className="panel-heading"><div><span className="kicker">ΑΓΩΓΗ</span><h2>Τρέχουσα αγωγή & ιστορικό αλλαγών</h2></div><button className="record compact" onClick={onAdd}><Plus size={15}/> Νέα / αλλαγή αγωγής</button></div>{active.length?<div className="med-runtime-list">{active.map(m=><article key={m.id}><div><span className="kicker">ΕΝΕΡΓΟ</span><h3>{m.medication_name}</h3></div><strong>{m.dose} {m.unit}</strong><span>{m.frequency}</span><small>Από {date(m.effective_from)}</small></article>)}</div>:<div className="panel-empty">Δεν υπάρχει ενεργή αγωγή.</div>}<div className="med-events"><h3><History size={16}/> Ιστορικό αλλαγών</h3>{bundle.medicationEvents.length?bundle.medicationEvents.map(e=><div key={e.id}><span>{date(e.effective_on)}</span><strong>{e.event_type==='started'?'Έναρξη αγωγής':'Αλλαγή δόσης'}</strong><p>{e.reason||'Χωρίς καταγεγραμμένο λόγο.'}</p></div>):<p>Δεν υπάρχουν αλλαγές αγωγής.</p>}</div></section>}

export function PsychometricsPanel(){return <section className="empty-clinical-state"><TestTube2 size={25}/><span className="kicker">ΨΥΧΟΜΕΤΡΙΚΑ</span><h2>Δεν υπάρχουν ακόμη μετρήσεις για αυτόν τον ασθενή</h2><p>Στο P0 demo δεν εμφανίζουμε ψεύτικη επιτυχία αποστολής. Η ανάθεση, οι απαντήσεις και το server-side scoring θα συνδεθούν στην επόμενη φάση.</p><a className="text-button" href="/psychometrics">Άνοιγμα βιβλιοθήκης τεστ <ChevronRight size={15}/></a></section>}

export function MedicationModal({bundle,onClose,onSaved}:{bundle:PatientBundle;onClose:()=>void;onSaved:()=>Promise<unknown>}){
 const active=bundle.medications.filter(x=>x.status==='active'); const [mode,setMode]=useState<'start'|'change'>(active.length?'change':'start'); const [medId,setMedId]=useState(active[0]?.id||''); const selected=useMemo(()=>active.find(x=>x.id===medId),[active,medId]); const [name,setName]=useState(''); const [dose,setDose]=useState(selected?String(selected.dose):''); const [unit,setUnit]=useState(selected?.unit||'mg'); const [frequency,setFrequency]=useState(selected?.frequency||''); const [effective,setEffective]=useState(new Date().toISOString().slice(0,10)); const [reason,setReason]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(selected){setDose(String(selected.dose));setUnit(selected.unit);setFrequency(selected.frequency)}},[selected]);
 async function save(){if((mode==='start'&&!name.trim())||!dose||!frequency.trim()){setError('Συμπληρώστε φάρμακο, δόση και συχνότητα.');return}setSaving(true);setError('');try{const draft=bundle.sessions.find(x=>x.status==='draft');await demoPost(mode==='start'?{action:'medication_start',patient_id:bundle.patient.id,session_id:draft?.id||null,name,dose:Number(dose),unit,frequency,effective_on:effective,reason}:{action:'medication_change',medication_id:medId,session_id:draft?.id||null,dose:Number(dose),unit,frequency,effective_on:effective,reason});await onSaved();onClose()}catch(cause){setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκε η αλλαγή.')}finally{setSaving(false)}}
 return <div className="entry-modal-backdrop" onClick={onClose}><section className="entry-modal medication-runtime-modal" onClick={e=>e.stopPropagation()}><button className="entry-close" onClick={onClose} aria-label="Κλείσιμο"><X size={19}/></button><span className="kicker">ΓΡΗΓΟΡΗ ΑΛΛΑΓΗ ΑΓΩΓΗΣ</span><h2>{mode==='change'?'Αλλαγή δόσης':'Νέα αγωγή'}</h2><div className="mode-switch"><button className={mode==='change'?'active':''} disabled={!active.length} onClick={()=>setMode('change')}>Αλλαγή δόσης</button><button className={mode==='start'?'active':''} onClick={()=>setMode('start')}>Νέα αγωγή</button></div>{mode==='change'?<><label>Υπάρχον φάρμακο<select value={medId} onChange={e=>setMedId(e.target.value)}>{active.map(m=><option key={m.id} value={m.id}>{m.medication_name}</option>)}</select></label>{selected&&<div className="current-dose">Τρέχουσα δόση <strong>{selected.dose} {selected.unit} · {selected.frequency}</strong></div>}</>:<label>Φάρμακο<input value={name} onChange={e=>setName(e.target.value)} placeholder="π.χ. Sertraline"/></label>}<div className="med-form-grid"><label>Νέα δόση<input inputMode="decimal" value={dose} onChange={e=>setDose(e.target.value.replace(',','.'))}/></label><label>Μονάδα<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Συχνότητα<input value={frequency} onChange={e=>setFrequency(e.target.value)} placeholder="π.χ. 1× πρωί"/></label><label>Έναρξη<input type="date" value={effective} onChange={e=>setEffective(e.target.value)}/></label></div><label>Λόγος αλλαγής<textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Προαιρετική κλινική σημείωση"/></label><div className="med-preview"><span>ΠΡΟΕΠΙΣΚΟΠΗΣΗ</span><p>{mode==='change'&&selected?`${selected.medication_name}: ${selected.dose} ${selected.unit} → ${dose||'—'} ${unit} · ${frequency||'—'} · από ${effective}`:`${name||'Νέα αγωγή'}: ${dose||'—'} ${unit} · ${frequency||'—'} · από ${effective}`}</p></div>{error&&<div className="save-state error" role="alert">{error}</div>}<footer className="entry-footer"><button onClick={onClose}>Ακύρωση</button><button className="entry-primary" onClick={()=>void save()} disabled={saving}><Check size={15}/>{saving?'Αποθήκευση…':'Αποθήκευση αλλαγής'}</button></footer></section></div>
}
