'use client';
import {useEffect,useRef,useState} from 'react';
import AssessmentEmail,{type AssessmentLink} from '@/components/mail/AssessmentEmail';
import IntakeLauncher from '@/components/intake/IntakeLauncher';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
import {assessmentLink,assessmentLinkLabel} from '@/lib/clinical/assessment-link';
import {completedMeasurements} from '@/lib/clinical/patient-record';
import {getDemoTesterId} from '@/lib/demo-tester';
import {instruments,answerLabels} from '@/lib/psychometrics/instruments';
import {formatClinicDate,formatClinicDateTime} from '@/lib/clinic-time';
export default function PatientPsychometrics({bundle,reload,sessionId,selectedAssessmentId}:{bundle:PatientBundle;reload:()=>Promise<unknown>;sessionId?:string;selectedAssessmentId?:string}){
 const [instrument,setInstrument]=useState('PHQ-9'),[appointment,setAppointment]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<{id:string;token:string}|null>(null);
 const [composer,setComposer]=useState(false),[prepared,setPrepared]=useState<AssessmentLink|null>(null),[sent,setSent]=useState(false),[copied,setCopied]=useState(false),[intakeOpen,setIntakeOpen]=useState(false);
 const assignFlight=useRef<Promise<AssessmentLink>|null>(null);
 const actionBusy=useRef(false);
 const resultsRef=useRef<HTMLElement>(null);
 const selectedAvailable=!sessionId&&Boolean(bundle.assessments.some(a=>a.id===selectedAssessmentId));
 useEffect(()=>{if(sessionId||!selectedAssessmentId||!selectedAvailable)return;const result=Array.from(resultsRef.current?.querySelectorAll<HTMLElement>('[data-assessment-id]')||[]).find(element=>element.dataset.assessmentId===selectedAssessmentId);result?.scrollIntoView({block:'center'});result?.focus({preventScroll:true})},[sessionId,selectedAssessmentId,selectedAvailable]);
 useEffect(()=>{if(sessionId)return;const code=new URLSearchParams(window.location.search).get('instrument');if(code==='PHQ-9'||code==='GAD-7')setInstrument(code)},[sessionId]);
 async function call(body:Record<string,unknown>){const r=await fetch('/api/psychometrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,tester:getDemoTesterId()})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function assign():Promise<AssessmentLink>{if(prepared)return prepared;if(assignFlight.current)return assignFlight.current;const task=(async()=>{setBusy(true);setError('');const request=pending||{id:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('')};setPending(request);try{const assigned=await call({action:'assign',...request,patient_id:bundle.patient.id,instrument,appointment_id:sessionId?null:appointment||null,session_id:sessionId||null});const result={...request,link:assigned.assessmentLink||location.origin+'/assessment#'+request.token};setLink(result.link);setPrepared(result);setPending(null);try{await reload()}catch{/* assignment is committed and remains retry-safe by request id */}return result}catch(e){setError(e instanceof Error?e.message:'Αποτυχία');throw e}finally{setBusy(false)}})();assignFlight.current=task;try{return await task}finally{assignFlight.current=null}}
 async function committedAction(body:Record<string,unknown>,afterCommit?:()=>void){if(actionBusy.current)return;actionBusy.current=true;setBusy(true);setError('');let committed=false;try{await call(body);committed=true;afterCommit?.();try{await reload()}catch{/* mutation is committed; the folder can reconcile later */}}catch(e){if(!committed)setError(e instanceof Error?e.message:'Αποτυχία')}finally{actionBusy.current=false;setBusy(false)}}
 async function reviewItem9(id:string){await committedAction({action:'review_item9',id})}
 async function reviewAssessment(id:string){await committedAction({action:'review',id})}
 async function revoke(id:string){await committedAction({action:'revoke',id},()=>{setLink('');setPrepared(null);setSent(false)})}
 const availableMeasurementIds=sessionId?null:new Set(completedMeasurements(bundle).map(a=>a.id));
 const sourceLabel=(provenance?:string|null)=>provenance?.includes('patient_intake:email')?'Από ασθενή · Email':provenance?.includes('patient_intake:tablet')?'Από ασθενή · Tablet':provenance?.includes('patient_intake:scanned_paper')?'Από ασθενή · Έντυπο':provenance?.includes('patient_intake:print')?'Από ασθενή · Έντυπο':provenance?.includes('patient_link')?'Από ασθενή · Σύνδεσμος':'';
 return <section ref={resultsRef} className="panel-stack patient-psychometrics"><h2>Ψυχομετρικά</h2>
 {!sessionId&&selectedAssessmentId&&!selectedAvailable&&<p role="status">Η συγκεκριμένη μέτρηση δεν είναι διαθέσιμη στον φάκελο.</p>}
 {!sessionId?<div className="assessment-assign unified-assessment-assign"><label>Εργαλείο<select disabled={busy} value={instrument} onChange={e=>setInstrument(e.target.value)}><option>PHQ-9</option><option>GAD-7</option></select></label><label>Σύνδεση με προγραμματισμένο ραντεβού (προαιρετικό)<select disabled={busy} value={appointment} onChange={e=>setAppointment(e.target.value)}><option value="">Χωρίς σύνδεση</option>{bundle.appointments.filter(a=>a.status==='scheduled'&&new Date(a.scheduled_start)>new Date()).map(a=><option key={a.id} value={a.id}>{formatClinicDateTime(a.scheduled_start)}</option>)}</select></label><button disabled={busy} className="assessment-primary" onClick={()=>setIntakeOpen(true)}>Συμπλήρωση από ασθενή</button><small>Επιλέξτε Email, Tablet ή Εκτύπωση στο επόμενο βήμα. Το αποτέλεσμα επιστρέφει αυτόματα στον φάκελο.</small></div>:<><div className="assessment-assign"><label>Εργαλείο<select disabled={busy||Boolean(pending)} value={instrument} onChange={e=>{setInstrument(e.target.value);setLink('');setPrepared(null);setSent(false)}}><option>PHQ-9</option><option>GAD-7</option></select></label><span className="visit-hint">Η ανάθεση συνδέεται με αυτή την επίσκεψη.</span><button disabled={busy} className="assessment-primary" onClick={()=>{setComposer(true);setCopied(false)}}>Αποστολή ερωτηματολογίου</button></div>
 {link&&<div className="assessment-share"><span role="status">{sent?'Το email έγινε δεκτό για αποστολή':'Ο σύνδεσμος είναι έτοιμος'} <small>Ισχύει για 14 ημέρες</small></span><div><button onClick={()=>void navigator.clipboard.writeText(link).then(()=>setCopied(true)).catch(()=>setError('Δεν έγινε αντιγραφή. Ανοίξτε την προεπισκόπηση και αντιγράψτε τη διεύθυνση από τον browser.'))}>{copied?'Αντιγράφηκε':'Αντιγραφή'}</button><a href={link} target="_blank" rel="noreferrer">Προεπισκόπηση</a></div></div>}
 {composer&&<AssessmentEmail email={bundle.patient.email} instrument={instrument} prepare={assign} onClose={()=>setComposer(false)} onSent={()=>setSent(true)}/>}</>}
 {intakeOpen&&<IntakeLauncher patientId={bundle.patient.id} appointmentId={appointment||undefined} patientEmail={bundle.patient.email||''} subjectLabel={[bundle.patient.first_name,bundle.patient.last_name].filter(Boolean).join(' ')} defaultTools={[instrument]} lockTools onClose={()=>setIntakeOpen(false)} onDone={()=>void reload()}/>}
 {error&&<p role="alert">{error}</p>}
 <div className="psychometric-trajectories">{(['PHQ-9','GAD-7'] as const).map(code=>{const scores=bundle.assessments.filter(a=>a.instrument===code&&a.status==='completed'&&(!availableMeasurementIds||availableMeasurementIds.has(a.id))).sort((a,b)=>Date.parse(a.completed_at||a.created_at)-Date.parse(b.completed_at||b.created_at));return scores.length?<div key={code}><strong>{code}</strong><p>{scores.map(a=>a.score+' ('+formatClinicDate(a.completed_at||a.created_at)+')').join(' → ')}</p></div>:null})}</div>
 {(['PHQ-9','GAD-7'] as const).map(code=><section key={code}><h3>{code}</h3>{bundle.assessments.filter(a=>a.instrument===code).map(a=>{const expired=!['completed','revoked'].includes(a.status)&&new Date(a.expires_at)<new Date();const label=expired?'Έληξε':({assigned:'Ανατέθηκε',opened:'Ανοίχτηκε',completed:'Ολοκληρώθηκε',revoked:'Ανακλήθηκε'}[a.status]);const source=sourceLabel(a.provenance);const association=assessmentLink(bundle,a);return <article className={'assessment-result'+(source?' patient-submitted-assessment':'')} key={a.id} data-assessment-id={a.id} tabIndex={!sessionId&&a.id===selectedAssessmentId?-1:undefined}><div className="assessment-result-head"><strong>{a.completed_at?formatClinicDateTime(a.completed_at):formatClinicDate(a.created_at)} · {label}{a.score!==null?' · '+a.score+' / '+(code==='PHQ-9'?27:21):''}</strong>{source&&<span className="assessment-source">{source}</span>}</div>{availableMeasurementIds&&a.status==='completed'&&!availableMeasurementIds.has(a.id)&&<p role="status">Η χρονική σήμανση ή το αποτέλεσμα δεν είναι διαθέσιμο για τις τρέχουσες μετρήσεις. Η καταγραφή διατηρείται στο αναλυτικό ιστορικό.</p>}{a.item9_review&&<div className="review-signal"><p>Λήμμα 9: απάντηση μεγαλύτερη από 0 — {a.item9_reviewed_at?'ελέγχθηκε από τον γιατρό':'προς έλεγχο από τον γιατρό'}. Δεν αποτελεί εκτίμηση κινδύνου.</p>{!a.item9_reviewed_at&&<button disabled={busy} onClick={()=>void reviewItem9(a.id)}>Σήμανση ως ελεγμένο</button>}</div>}<small>{assessmentLinkLabel(bundle,a)}{association.appointment&&<> · Ραντεβού: {formatClinicDateTime(association.appointment.scheduled_start)}</>}{association.session&&<> · Έναρξη επίσκεψης: {formatClinicDateTime(association.session.started_at)}</>}</small>{a.answers&&<details open={!sessionId&&a.id===selectedAssessmentId||undefined}><summary>Ερωτήσεις και απαντήσεις</summary>{instruments[code].items.map((q,i)=><p key={i}>{i+1}. {q}<br/><b>{answerLabels[a.answers![i]]} ({a.answers![i]})</b></p>)}<small>Έκδοση {a.instrument_version} · βαθμολόγηση στον server</small></details>}{a.status==='completed'&&<div className="assessment-review-state">{a.reviewed_at?<small>✓ Ελεγμένο</small>:<button disabled={busy} onClick={()=>void reviewAssessment(a.id)}>Σήμανση ως ελεγμένο</button>}</div>}{!['completed','revoked'].includes(a.status)&&<button disabled={busy} onClick={()=>void revoke(a.id)}>Ανάκληση συνδέσμου</button>}</article>})}</section>)}
 </section>
}
