'use client';
import ClinicalSummary from './ClinicalSummary';
import VisitWorkspace from './VisitWorkspace';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Activity, Bell, CalendarDays, ClipboardCheck, FileText, FolderPlus, History as HistoryIcon, Home, Menu, Pill, Plus, Search, Settings, Stethoscope, TestTube2, Users, X } from 'lucide-react';
import { getDemoTesterId } from '@/lib/demo-tester';
import type { PatientBundle } from '@/lib/patients/demo-runtime';
import { demoPost } from '@/lib/patients/demo-client';
import PatientPsychometrics from './PatientPsychometrics';
import PatientSession from '@/components/patients/PatientSession';
import { HistoryPanel, MedicationModal, MedicationsPanel } from '@/components/patients/PatientPanels';
import { formatClinicAppointment } from '@/lib/clinic-time';

type Tab='summary'|'sessions'|'history'|'medications'|'psychometrics'; const tabs:Tab[]=['summary','sessions','history','medications','psychometrics'];
export default function PatientWorkspace({patientRef}:{patientRef:string}){
 const [contextReady,setContextReady]=useState(false); const [visitId,setVisitId]=useState<string|null>(null); const [visitType,setVisitType]=useState<'initial_assessment'|'follow_up'>('initial_assessment'); const [bundle,setBundle]=useState<PatientBundle|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [tab,setTabState]=useState<Tab>('summary'); const [sessionRef,setSessionRef]=useState<string|null>(null); const [mobileNav,setMobileNav]=useState(false); const [starting,setStarting]=useState(false); const [finalizing,setFinalizing]=useState(false); const [finalizeError,setFinalizeError]=useState(''); const [medOpen,setMedOpen]=useState(false); const [appointmentChoices,setAppointmentChoices]=useState<PatientBundle['appointments']>([]);
 async function loadShell(){try{const r=await fetch(`/api/patients/demo/visit?tester=${getDemoTesterId()}&patient=${encodeURIComponent(patientRef)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setBundle(d.bundle);setLoading(false);const params=new URLSearchParams(window.location.search);const id=params.get('session');if(id&&d.bundle.sessions.some((s:{id:string;status:string})=>s.id===id&&s.status==='draft'))setVisitId(id)}catch(e){setError(e instanceof Error?e.message:'Δεν φορτώθηκε ο φάκελος.')}finally{void load()}}
 async function load(){try{const tester=getDemoTesterId();const response=await fetch(`/api/patients/demo/runtime?tester=${tester}&patient=${encodeURIComponent(patientRef)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setBundle(data.bundle);setContextReady(true);setError('');return data.bundle as PatientBundle}catch(cause){setError(cause instanceof Error?cause.message:'Δεν φορτώθηκε η καρτέλα.');return null}finally{setLoading(false)}}
 useEffect(()=>{const read=()=>{const params=new URLSearchParams(window.location.search);const value=params.get('tab') as Tab|null;setTabState(value&&tabs.includes(value)?value:'summary');setSessionRef(params.get('session'))};read();void loadShell();window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[patientRef]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&tab==='summary')void load()};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[patientRef,tab]);
 function setTab(next:Tab,sessionId?:string|null){setVisitId(next==='sessions'&&sessionId&&bundle?.sessions.some(s=>s.id===sessionId&&s.status==='draft')?sessionId:null);setTabState(next);setSessionRef(next==='sessions'?(sessionId||null):null);const url=new URL(window.location.href);if(next==='summary')url.searchParams.delete('tab');else url.searchParams.set('tab',next);if(next==='sessions'&&sessionId)url.searchParams.set('session',sessionId);else url.searchParams.delete('session');window.history.pushState({},'',url)}
 async function startSession(appointmentId?:string,type=visitType){
  setVisitType(type);
  if(!bundle)return;

  const draft=bundle.sessions.find(s=>s.status==='draft');
  const linked=draft?bundle.appointments.find(a=>a.session_id===draft.id):undefined;
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const sameDay=bundle.appointments.filter(a=>a.status==='scheduled'&&!a.session_id&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(a.scheduled_start))===today);
  if(!linked&&!appointmentId&&!new URLSearchParams(window.location.search).get('appointment')&&sameDay.length>1){setAppointmentChoices(sameDay);return}
  const requestedId=appointmentId||new URLSearchParams(window.location.search).get('appointment');
  const requested=requestedId?bundle.appointments.find(a=>a.id===requestedId):undefined;
  if(requestedId&&!requested){setError('Το συγκεκριμένο ραντεβού δεν ανήκει στον φάκελο.');return}
  if(requested?.session_id){setTab('sessions',requested.session_id);return}
  const appointment=requested||linked||(sameDay.length===1?sameDay[0]:undefined);
  setStarting(true);setError('');
  try{
   const result=await demoPost({action:'start_session',patient_id:bundle.patient.id,session_type:appointment?.appointment_type||type,appointment_id:appointment?.id||null}) as {session?:{id?:string}};
   setAppointmentChoices([]);const id=result.session?.id||draft?.id;if(!id)throw new Error('Δεν επιστράφηκε συνεδρία.');setTab('sessions',id);setVisitId(id);void load();
  }catch(cause){setError(cause instanceof Error?cause.message:'Δεν ξεκίνησε η συνεδρία.')}finally{setStarting(false)}
 }
 async function finalize(sessionId:string){setFinalizing(true);setFinalizeError('');try{const fresh=await load();const draft=fresh?.sessions.find(s=>s.id===sessionId&&s.status==='draft');if(!draft)throw new Error('Το συγκεκριμένο πρόχειρο δεν είναι πλέον διαθέσιμο.');await demoPost({action:'finalize_session',session_id:draft.id,expected_version:draft.version});await load();setTab('summary')}catch(cause){setFinalizeError(cause instanceof Error?cause.message:'Δεν ολοκληρώθηκε η συνεδρία.')}finally{setFinalizing(false)}}
 if(loading)return <main className="clinical-page"><div className="record-state">Φόρτωση κλινικού φακέλου…</div></main>; if(error&&!bundle)return <main className="clinical-page"><Link href="/patients" className="back">← Ασθενείς</Link><div className="record-state error" role="alert">{error}</div></main>; if(!bundle)return null;
 async function exportRecord(){try{const r=await fetch('/api/patients/demo/export?tester='+getDemoTesterId()+'&patient='+bundle!.patient.id);if(!r.ok)throw new Error('Δεν έγινε εξαγωγή.');const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download='noima-patient-'+bundle!.patient.id+'.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(cause){setError(cause instanceof Error?cause.message:'Δεν έγινε εξαγωγή.')}}
 const appointmentRef=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('appointment'):null;
 const intended=bundle.appointments.find(a=>a.id===appointmentRef);
 const p=bundle.patient; const draft=bundle.sessions.find(s=>s.status==='draft'); const completed=bundle.sessions.filter(s=>s.status==='completed'); const hasInitial=completed.some(s=>s.session_type==='initial_assessment');
 return <main className="app-shell secondary-shell"><aside className={mobileNav?'sidebar mobile-open':'sidebar'}><button className="mobile-nav-close" onClick={()=>setMobileNav(false)} aria-label="Κλείσιμο μενού"><X size={20}/></button><div className="brand"><div className="brand-mark">Ψ</div><div className="brand-copy"><div className="brand-sub">Για μια οργανωμένη κλινική πράξη</div></div></div><nav className="nav"><Link href="/" className="nav-item"><Home size={19}/><span>Επισκόπηση</span></Link><Link href="/calendar" className="nav-item"><CalendarDays size={19}/><span>Ημερολόγιο</span></Link><Link href="/patients" className="nav-item active"><Users size={19}/><span>Ασθενείς</span></Link><Link href="/psychometrics" className="nav-item"><Activity size={19}/><span>Ψυχομετρικά τεστ</span></Link></nav></aside>{mobileNav&&<button className="mobile-nav-backdrop" aria-label="Κλείσιμο μενού" onClick={()=>setMobileNav(false)}/>}<section className="workspace"><header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileNav(true)} aria-label="Άνοιγμα μενού"><Menu size={21}/></button><div className="search"><span>{p.first_name} {p.last_name} · κλινικός φάκελος</span></div><div className="profile"><div className="avatar">ΚΠ</div><div><strong>Δρ. Κατερίνα Παπαδάκη</strong><span>Ψυχίατρος</span></div></div></header><div className="generic-patient-page">
  <div className="patient-hero compact"><div><span className="kicker">FICTIONAL TEST DATA</span><h1>{p.first_name} {p.last_name}</h1><p>{p.reported_age?`${p.reported_age} ετών · `:''}{p.chief_complaint||p.note||'Χωρίς καταγεγραμμένο λόγο προσέλευσης'}</p></div>{draft||intended?<button className="patient-voice-cta" onClick={()=>void startSession(intended?.id,draft?.session_type==='follow_up'?'follow_up':'initial_assessment')} disabled={starting}><span className="patient-voice-icon"><Plus size={19}/></span><span><strong>{intended?.session_id?'Άνοιγμα συνδεδεμένης επίσκεψης':intended?'Έναρξη επίσκεψης':'Συνέχεια επίσκεψης'}</strong><small>{intended?formatClinicAppointment(intended.scheduled_start):draft?.session_type==='initial_assessment'?'Αρχική αξιολόγηση · Πρόχειρο':'Follow-up · Πρόχειρο'}</small></span></button>:hasInitial?<button className="patient-voice-cta" onClick={()=>void startSession(undefined,'follow_up')} disabled={starting}><span className="patient-voice-icon"><Plus size={19}/></span><span><strong>Νέα επίσκεψη</strong><small>Follow-up · Επανεξέταση</small></span></button>:null}</div>{error&&<div className="record-state error" role="alert">{error}</div>}
  <div className="patient-workspace-shell"><aside className="patient-nav"><span className="patient-nav-label">ΦΑΚΕΛΟΣ</span><Nav active={tab==='summary'} onClick={()=>setTab('summary')} icon={<FileText size={16}/>} label="Σύνοψη"/><Nav active={tab==='sessions'} onClick={()=>setTab('sessions')} icon={<ClipboardCheck size={16}/>} label="Επισκέψεις" badge={draft?'1':undefined}/><Nav active={tab==='history'} onClick={()=>setTab('history')} icon={<HistoryIcon size={16}/>} label="Ιστορικό"/><Nav active={tab==='medications'} onClick={()=>setTab('medications')} icon={<Pill size={16}/>} label="Αγωγή"/><Nav active={tab==='psychometrics'} onClick={()=>setTab('psychometrics')} icon={<TestTube2 size={16}/>} label="Ψυχομετρικά"/><div className="patient-nav-divider"/><button className="patient-action" onClick={()=>void exportRecord()}><FileText size={16}/> Εξαγωγή φακέλου</button></aside>
   <div className="patient-workspace-content">{!contextReady&&<p role="status">Φόρτωση διαχρονικού φακέλου… Μπορείτε να ανοίξετε την επίσκεψη.</p>}{contextReady&&<>{tab==='summary'&&!error&&(hasInitial?<ClinicalSummary bundle={bundle} onSessions={(sessionId)=>setTab('sessions',sessionId)} onPsychometrics={()=>setTab('psychometrics')} onMedications={()=>setTab('medications')} onHistory={()=>setTab('history')}/>:<NewPatientSummary bundle={bundle} onDetails={()=>setTab('history')} onStart={()=>void startSession(undefined,'initial_assessment')}/>) } {tab==='sessions'&&!visitId&&(draft&&!sessionRef?<div className="panel-stack"><button onClick={()=>setTab('sessions',draft.id)}>Συνέχεια πρόχειρου · {draft.session_type==='initial_assessment'?'First Visit':'Follow-up'}</button><PatientSession bundle={{...bundle,sessions:completed}} reload={load} onFinalize={finalize} finalizing={finalizing} finalizeError={finalizeError} selectedSessionId={null} onSelectSession={(id)=>setTab('sessions',id)}/></div>:<PatientSession bundle={bundle} reload={load} onFinalize={finalize} finalizing={finalizing} finalizeError={finalizeError} selectedSessionId={sessionRef} onSelectSession={(id)=>setTab('sessions',id)}/>)} {tab==='history'&&<HistoryPanel bundle={bundle} reload={load}/>} {tab==='medications'&&<MedicationsPanel bundle={bundle} reload={load} onAdd={()=>setMedOpen(true)}/>} {tab==='psychometrics'&&<PatientPsychometrics bundle={bundle} reload={load}/>}</>}</div></div>
 </div></section>{medOpen&&<MedicationModal bundle={bundle} onClose={()=>setMedOpen(false)} onSaved={load}/>}
 {appointmentChoices.length>1&&<div className="entry-modal-backdrop" onClick={()=>setAppointmentChoices([])}><section className="entry-modal appointment-choice-modal" onClick={e=>e.stopPropagation()}><button className="entry-close" onClick={()=>setAppointmentChoices([])} aria-label="Κλείσιμο"><X size={19}/></button><span className="kicker">ΕΝΑΡΞΗ ΣΥΝΕΔΡΙΑΣ</span><h2>Ποιο σημερινό ραντεβού;</h2><p>Υπάρχουν περισσότερα από ένα προγραμματισμένα ραντεβού για τον ίδιο ασθενή. Επιλέξτε ποιο συνδέεται με αυτή τη συνεδρία.</p><div className="appointment-choice-list">{appointmentChoices.map(a=><button key={a.id} disabled={starting} onClick={()=>void startSession(a.id)}><strong>{formatClinicAppointment(a.scheduled_start)}</strong><span>{a.appointment_type==='initial_assessment'?'Αρχική αξιολόγηση':'Follow-up'}</span></button>)}</div><button disabled={starting} onClick={()=>setAppointmentChoices([])}>Ακύρωση</button></section></div>}
 {visitId&&<VisitWorkspace key={visitId} sessionId={visitId} patientId={p.id} context={contextReady?bundle:null} reloadContext={load} onClose={()=>{setTab('sessions');void load()}} onFinalized={()=>{setContextReady(false);setTab('summary');void load()}} onSelect={(id)=>setTab('sessions',id)}/>}
 </main>
}
function Nav({active,onClick,icon,label,badge}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;badge?:string}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span>{badge&&<i>{badge}</i>}</button>}

function NewPatientSummary({bundle,onDetails,onStart}:{bundle:PatientBundle;onDetails:()=>void;onStart:()=>void}){
 return <section className="new-patient-home clinical-start">
  <div className="clinical-start-copy">
   <span className="clinical-start-eyebrow">ΑΡΧΙΚΗ ΕΠΙΣΚΕΨΗ</span>
   <h2>Αρχική αξιολόγηση</h2>
   <p>Η πρώτη επίσκεψη, σε μία ενιαία ροή.</p>
   <button className="clinical-start-cta" onClick={onStart}><span>Έναρξη αξιολόγησης</span><span aria-hidden="true">→</span></button>
   <div className="clinical-start-scope">Λόγος προσέλευσης <i>·</i> MSE <i>·</i> Risk <i>·</i> Ιστορικό <i>·</i> Διάγνωση <i>·</i> Αγωγή <i>·</i> Πλάνο</div>
  </div>
  <button className="patient-details-link" onClick={onDetails}>Στοιχεία ασθενή <span aria-hidden="true">→</span></button>
 </section>
}