'use client';
import PilotProfile from '@/components/PilotProfile';
import AppointmentStartConfirmation from '@/components/calendar/AppointmentStartConfirmation';
import ClinicalSummary from './ClinicalSummary';
import VisitWorkspace from './VisitWorkspace';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import {hasCompletedClinicalHistory,workspaceHeroAction,workspaceLocation,workspaceTransitionSearch,type WorkspaceTab} from '@/lib/clinical/visit-workspace-state';
import { Activity, Bell, CalendarDays, ClipboardCheck, FileText, FolderPlus, History as HistoryIcon, Home, Menu, Pill, Plus, Search, Settings, Stethoscope, TestTube2, Users, X } from 'lucide-react';
import { getDemoTesterId } from '@/lib/demo-tester';
import type { DemoSession, PatientBundle } from '@/lib/patients/demo-runtime';
import { demoPost } from '@/lib/patients/demo-client';
import PatientPsychometrics from './PatientPsychometrics';
import PatientSession from '@/components/patients/PatientSession';
import { HistoryPanel, MedicationModal, MedicationsPanel } from '@/components/patients/PatientPanels';
import { formatClinicAppointment, formatClinicDateTime } from '@/lib/clinic-time';

type Tab=WorkspaceTab;
export default function PatientWorkspace({patientRef}:{patientRef:string}){
 const [pendingStart,setPendingStart]=useState<{appointment:PatientBundle['appointments'][number];type:'initial_assessment'|'follow_up'}|null>(null);
 const beforeNavigate=useRef<(()=>Promise<void>)|null>(null);
 const currentUrl=useRef('');
 const historyRead=useRef<()=>Promise<void>>(async()=>{});
 const navigationSequence=useRef(0);
 const startingRef=useRef(false);
 const activePatientRef=useRef(patientRef);activePatientRef.current=patientRef;
 const [contextReady,setContextReady]=useState(false); const [visitId,setVisitId]=useState<string|null>(null); const [visitType,setVisitType]=useState<'initial_assessment'|'follow_up'>('initial_assessment'); const [bundle,setBundle]=useState<PatientBundle|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [tab,setTabState]=useState<Tab>('summary'); const [sessionRef,setSessionRef]=useState<string|null>(null); const [mobileNav,setMobileNav]=useState(false); const [starting,setStarting]=useState(false); const [finalizing,setFinalizing]=useState(false); const [finalizeError,setFinalizeError]=useState('');
 const [recordNotice,setRecordNotice]=useState(''); const [medOpen,setMedOpen]=useState(false); const [appointmentChoices,setAppointmentChoices]=useState<PatientBundle['appointments']>([]);
 async function loadShell(){try{const requestedPatient=patientRef;const r=await fetch(`/api/patients/demo/visit?tester=${getDemoTesterId()}&patient=${encodeURIComponent(requestedPatient)}`,{cache:'no-store'});const d=await r.json();if(activePatientRef.current!==requestedPatient)return null;if(!r.ok)throw new Error(d.error);setBundle(current=>current?{...current,patient:d.bundle.patient,sessions:d.bundle.sessions,appointments:d.bundle.appointments}:d.bundle);setLoading(false);const location=workspaceLocation(window.location.search);setVisitId(location.tab==='sessions'&&location.sessionId&&d.bundle.sessions.some((s:{id:string;status:string})=>s.id===location.sessionId&&s.status==='draft')?location.sessionId:null);return d.bundle as PatientBundle}catch{return null}}
 async function load(){const requestedPatient=patientRef;try{const tester=getDemoTesterId();const response=await fetch(`/api/patients/demo/runtime?tester=${tester}&patient=${encodeURIComponent(requestedPatient)}`,{cache:'no-store'});const data=await response.json();if(activePatientRef.current!==requestedPatient)return null;if(!response.ok)throw new Error(data.error);setBundle(data.bundle);setContextReady(true);setError('');return data.bundle as PatientBundle}catch(cause){if(activePatientRef.current===requestedPatient)setError(cause instanceof Error?cause.message:'Δεν φορτώθηκε η καρτέλα.');return null}finally{if(activePatientRef.current===requestedPatient)setLoading(false)}}
 function applyLocation(search:string,source:PatientBundle|null=bundle){const location=workspaceLocation(search);setPendingStart(null);setAppointmentChoices([]);setTabState(location.tab);setSessionRef(location.sessionId);setVisitId(location.tab==='sessions'&&location.sessionId&&source?.sessions.some(s=>s.id===location.sessionId&&s.status==='draft')?location.sessionId:null)}
 function applyTab(next:Tab,sessionId?:string|null,source:PatientBundle|null=bundle,options:{clearAppointment?:boolean}={}){setError('');setPendingStart(null);setAppointmentChoices([]);setVisitId(next==='sessions'&&sessionId&&source?.sessions.some(s=>s.id===sessionId&&s.status==='draft')?sessionId:null);setTabState(next);setSessionRef(next==='sessions'?(sessionId||null):null);const search=workspaceTransitionSearch(window.location.search,next,sessionId,options);const target=window.location.pathname+search+window.location.hash;const current=window.location.pathname+window.location.search+window.location.hash;if(target!==current)window.history.pushState({},'',target);currentUrl.current=window.location.href}
 historyRead.current=async()=>{const sequence=++navigationSequence.current;const target=window.location.href;if(medOpen){setError('Ολοκληρώστε ή κλείστε πρώτα την καταχώρηση αγωγής.');window.history.replaceState({},'',currentUrl.current);return}try{await beforeNavigate.current?.();if(sequence!==navigationSequence.current)return;const targetSearch=new URL(target).search;const targetLocation=workspaceLocation(targetSearch);if(visitId&&targetLocation.sessionId!==visitId){await demoPost({action:'finish_session_later',session_id:visitId});setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.')}if(sequence!==navigationSequence.current)return;applyLocation(targetSearch);currentUrl.current=target}catch(cause){if(sequence!==navigationSequence.current)return;setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκε η πρόχειρη καταγραφή.');window.history.replaceState({},'',currentUrl.current)}};
 useEffect(()=>{navigationSequence.current++;beforeNavigate.current=null;setBundle(null);setContextReady(false);setVisitId(null);setSessionRef(null);setTabState('summary');setError('');setRecordNotice('');setLoading(true);currentUrl.current=window.location.href;applyLocation(window.location.search,null);void loadShell();void load();const read=()=>{void historyRead.current()};window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[patientRef]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&tab==='summary')void load()};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[patientRef,tab]);
 useEffect(()=>{if(!medOpen)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[medOpen]);
 async function setTab(next:Tab,sessionId?:string|null){if(medOpen){setError('Ολοκληρώστε ή κλείστε πρώτα την καταχώρηση αγωγής.');return}const sequence=++navigationSequence.current;try{await beforeNavigate.current?.()}catch(cause){if(sequence===navigationSequence.current)setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκαν οι αλλαγές.');return}if(sequence!==navigationSequence.current)return;applyTab(next,sessionId)}
 async function startSession(appointmentId?:string,type=visitType,confirmed=false){
  if(!bundle||startingRef.current)return;
  startingRef.current=true;setStarting(true);setVisitType(type);
  try{
   await beforeNavigate.current?.();
   const activeBundle=await loadShell();
   if(!activeBundle)throw new Error('Δεν ανανεώθηκε ο φάκελος πριν τη δημιουργία της καταγραφής.');
   const draft=activeBundle.sessions.find(s=>s.status==='draft');
   const requestedId=appointmentId||new URLSearchParams(window.location.search).get('appointment');
   const requested=requestedId?activeBundle.appointments.find(a=>a.id===requestedId):undefined;
   if(requestedId&&!requested){const clean=workspaceTransitionSearch(window.location.search,tab,sessionRef,{clearAppointment:true});window.history.replaceState({},'',window.location.pathname+clean+window.location.hash);throw new Error('Το συγκεκριμένο ραντεβού δεν ανήκει πλέον στον φάκελο.');}
   if(requested&&requested.status!=='scheduled'&&!requested.session_id){const clean=workspaceTransitionSearch(window.location.search,tab,sessionRef,{clearAppointment:true});window.history.replaceState({},'',window.location.pathname+clean+window.location.hash);throw new Error('Το συγκεκριμένο ραντεβού δεν είναι πλέον ενεργό.');}
   if(requested?.session_id){navigationSequence.current++;applyTab('sessions',requested.session_id,activeBundle,{clearAppointment:true});return}
   if(draft&&!requested){navigationSequence.current++;applyTab('sessions',draft.id,activeBundle,{clearAppointment:true});return}
   const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
   const sameDay=activeBundle.appointments.filter(a=>a.status==='scheduled'&&!a.session_id&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(a.scheduled_start))===today);
   if(!requestedId&&sameDay.length>1){setAppointmentChoices(sameDay);return}
   const appointment=requested||(sameDay.length===1?sameDay[0]:undefined);
   if(appointment&&!appointment.session_id&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(appointment.scheduled_start))!==today&&!confirmed){setPendingStart({appointment,type});return}
   setError('');
   const result=await demoPost({action:'start_session',patient_id:activeBundle.patient.id,session_type:appointment?.appointment_type||type,appointment_id:appointment?.id||null}) as {session?:{id?:string}};
   setAppointmentChoices([]);const id=result.session?.id;if(!id)throw new Error('Δεν επιστράφηκε συνεδρία.');
   const shell=await loadShell();if(!shell)throw new Error('Η καταγραφή δημιουργήθηκε αλλά ο φάκελος δεν ανανεώθηκε.');const refreshed=bundle?{...bundle,patient:shell.patient,sessions:shell.sessions,appointments:shell.appointments}:shell;setBundle(refreshed);navigationSequence.current++;applyTab('sessions',id,refreshed,{clearAppointment:true});void load();
  }catch(cause){setError(cause instanceof Error?cause.message:'Δεν δημιουργήθηκε η καταγραφή.')}
  finally{startingRef.current=false;setStarting(false)}
 }
 async function finalize(sessionId:string){setFinalizing(true);setFinalizeError('');setRecordNotice('');let committed=false;try{const shell=await loadShell();const draft=shell?.sessions.find(s=>s.id===sessionId&&s.status==='draft');if(!draft)throw new Error('Το συγκεκριμένο πρόχειρο δεν είναι πλέον διαθέσιμο.');const result=await demoPost({action:'finalize_session',session_id:draft.id,expected_version:draft.version}) as {session:DemoSession};committed=true;const optimistic=bundle?{...bundle,sessions:bundle.sessions.map(s=>s.id===result.session.id?result.session:s),appointments:bundle.appointments.map(a=>a.session_id===result.session.id?{...a,status:'completed'}:a)}:null;if(optimistic){setBundle(optimistic);applyTab('sessions',result.session.id,optimistic)}const nextShell=await loadShell();if(nextShell){const refreshed=bundle?{...(optimistic||bundle),patient:nextShell.patient,sessions:nextShell.sessions,appointments:nextShell.appointments}:nextShell;setBundle(refreshed);applyTab('sessions',result.session.id,refreshed)}void load()}catch(cause){setFinalizeError(committed?'Η καταγραφή ολοκληρώθηκε, αλλά η προβολή δεν ανανεώθηκε. Ανανεώστε τον φάκελο.':cause instanceof Error?cause.message:'Δεν ολοκληρώθηκε η καταγραφή.')}finally{setFinalizing(false)}}
 async function finishLater(sessionId:string){setFinalizeError('');try{await demoPost({action:'finish_session_later',session_id:sessionId});setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.');applyTab('sessions',null,bundle)}catch(cause){setFinalizeError(cause instanceof Error?cause.message:'Δεν δημιουργήθηκε το To do.')}}
 if(loading)return <main className="clinical-page"><div className="record-state">Φόρτωση κλινικού φακέλου…</div></main>; if(error&&!bundle)return <main className="clinical-page"><Link href="/patients" className="back">← Ασθενείς</Link><div className="record-state error" role="alert">{error}</div></main>; if(!bundle)return null;
 async function exportRecord(){try{const r=await fetch('/api/patients/demo/export?tester='+getDemoTesterId()+'&patient='+bundle!.patient.id);if(!r.ok)throw new Error('Δεν έγινε εξαγωγή.');const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download='noima-patient-'+bundle!.patient.id+'.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(cause){setError(cause instanceof Error?cause.message:'Δεν έγινε εξαγωγή.')}}
 const appointmentRef=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('appointment'):null;
 const intended=bundle.appointments.find(a=>a.id===appointmentRef&&(a.status==='scheduled'||Boolean(a.session_id)));
 const p=bundle.patient; const draft=bundle.sessions.find(s=>s.status==='draft'); const completed=bundle.sessions.filter(s=>s.status==='completed'); const draftAppointment=draft?bundle.appointments.find(a=>a.session_id===draft.id):undefined; const heroAppointment=draft?draftAppointment:intended; const isEstablished=hasCompletedClinicalHistory(bundle); const heroAction=workspaceHeroAction(isEstablished,Boolean(draft),Boolean(heroAppointment));
 return <main className="app-shell secondary-shell" onClickCapture={e=>{const link=(e.target as HTMLElement).closest('a');if(!link||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||link.target==='_blank'||link.hasAttribute('download'))return;const url=new URL(link.href);if(url.origin!==window.location.origin||(!beforeNavigate.current&&!medOpen))return;e.preventDefault();e.stopPropagation();if(medOpen){setError('Ολοκληρώστε ή κλείστε πρώτα την καταχώρηση αγωγής.');return}const sequence=++navigationSequence.current;void beforeNavigate.current!().then(()=>{if(sequence===navigationSequence.current)window.location.assign(url.href)}).catch(cause=>{if(sequence===navigationSequence.current)setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκαν οι αλλαγές.')})}}><aside className={mobileNav?'sidebar mobile-open':'sidebar'}><button className="mobile-nav-close" onClick={()=>setMobileNav(false)} aria-label="Κλείσιμο μενού"><X size={20}/></button><div className="brand"><div className="brand-mark">Ψ</div><div className="brand-copy"><div className="brand-sub">Για μια οργανωμένη κλινική πράξη</div></div></div><nav className="nav"><Link href="/" className="nav-item"><Home size={19}/><span>Επισκόπηση</span></Link><Link href="/calendar" className="nav-item"><CalendarDays size={19}/><span>Ημερολόγιο</span></Link><Link href="/patients" className="nav-item active"><Users size={19}/><span>Ασθενείς</span></Link><Link href="/psychometrics" className="nav-item"><Activity size={19}/><span>Ψυχομετρικά τεστ</span></Link></nav></aside>{mobileNav&&<button className="mobile-nav-backdrop" aria-label="Κλείσιμο μενού" onClick={()=>setMobileNav(false)}/>}<section className="workspace"><header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileNav(true)} aria-label="Άνοιγμα μενού"><Menu size={21}/></button><div className="search"><span>{p.first_name} {p.last_name} · κλινικός φάκελος</span></div><PilotProfile/></header><div className="generic-patient-page">
  <div className="patient-hero compact"><div><span className="kicker">FICTIONAL TEST DATA</span><h1>{p.first_name} {p.last_name}</h1><p className="patient-record-context">Κλινικός φάκελος{p.reported_age?` · ${p.reported_age} ετών`:``}{!isEstablished?` · Νέος ασθενής`:``}</p></div>{heroAction==='resume'?<button className="patient-voice-cta" onClick={()=>void startSession(heroAppointment?.id,draft?.session_type==='initial_assessment'?'initial_assessment':'follow_up')} disabled={starting}><span className="patient-voice-icon"><Plus size={19}/></span><span><strong>{draft?'Συνέχεια καταγραφής':heroAppointment?.session_id?'Άνοιγμα καταγραφής':heroAppointment?'Νέα καταγραφή':'Συνέχεια καταγραφής'}</strong><small>{draftAppointment?formatClinicAppointment(draftAppointment.scheduled_start):draft?(draft.session_type==='initial_assessment'?'Αρχική αξιολόγηση · Πρόχειρο':'Follow-up · Πρόχειρο'):heroAppointment?formatClinicAppointment(heroAppointment.scheduled_start):''}</small></span></button>:heroAction==='new_follow_up'?<button className="patient-voice-cta" onClick={()=>void startSession(undefined,'follow_up')} disabled={starting}><span className="patient-voice-icon"><Plus size={19}/></span><span><strong>Νέα καταγραφή</strong><small>Follow-up · Επανεξέταση</small></span></button>:null}</div>{error&&<div className="record-state error" role="alert">{error}</div>}
  {recordNotice&&<div className="record-state saved-draft" role="status">{recordNotice}</div>}<div className="patient-workspace-shell"><aside className="patient-nav"><span className="patient-nav-label">ΦΑΚΕΛΟΣ</span><Nav active={tab==='summary'} onClick={()=>setTab('summary')} icon={<FileText size={16}/>} label="Σύνοψη"/><Nav active={tab==='sessions'} onClick={()=>setTab('sessions')} icon={<ClipboardCheck size={16}/>} label="Επισκέψεις" badge={completed.length?String(completed.length):undefined}/><Nav active={tab==='history'} onClick={()=>setTab('history')} icon={<HistoryIcon size={16}/>} label="Ιστορικό"/><Nav active={tab==='medications'} onClick={()=>setTab('medications')} icon={<Pill size={16}/>} label="Αγωγή"/><Nav active={tab==='psychometrics'} onClick={()=>setTab('psychometrics')} icon={<TestTube2 size={16}/>} label="Ψυχομετρικά"/><div className="patient-nav-divider"/><button className="patient-action" onClick={()=>void exportRecord()}><FileText size={16}/> Εξαγωγή φακέλου</button></aside>
   <div className="patient-workspace-content">{!contextReady&&<p role="status">Φόρτωση διαχρονικού φακέλου…</p>}{contextReady&&<>{tab==='summary'&&(isEstablished?<ClinicalSummary bundle={bundle} onSessions={(sessionId)=>setTab('sessions',sessionId)} onPsychometrics={()=>setTab('psychometrics')} onMedications={()=>setTab('medications')} onHistory={()=>setTab('history')}/>:<NewPatientSummary bundle={bundle} onDetails={()=>setTab('history')} onStart={()=>void startSession(undefined,'initial_assessment')}/>) } {tab==='sessions'&&!visitId&&(draft&&!sessionRef?<div className="panel-stack"><div className="pending-session-block"><span className="kicker">ΣΕ ΕΚΚΡΕΜΟΤΗΤΑ · 1</span><button className="pending-session-row" onClick={()=>void startSession(draftAppointment?.id,draft.session_type==='initial_assessment'?'initial_assessment':'follow_up')}><div><strong>{draft.session_type==='initial_assessment'?'Αρχική αξιολόγηση':'Follow-up'}</strong><span>{formatClinicDateTime(draft.started_at)} · Πρόχειρο</span></div><b>Συνέχεια καταγραφής →</b></button></div><div className="completed-session-section"><span className="kicker">ΟΛΟΚΛΗΡΩΜΕΝΕΣ · {completed.length}</span><PatientSession beforeNavigate={beforeNavigate} bundle={{...bundle,sessions:completed}} reload={load} onFinalize={finalize} onFinishLater={finishLater} finalizing={finalizing} finalizeError={finalizeError} selectedSessionId={null} onSelectSession={(id)=>setTab('sessions',id)}/></div></div>:<PatientSession beforeNavigate={beforeNavigate} bundle={bundle} reload={load} onFinalize={finalize} onFinishLater={finishLater} finalizing={finalizing} finalizeError={finalizeError} selectedSessionId={sessionRef} onSelectSession={(id)=>setTab('sessions',id)}/>)} {tab==='history'&&<HistoryPanel bundle={bundle} reload={load} beforeNavigate={beforeNavigate}/>} {tab==='medications'&&<MedicationsPanel bundle={bundle} reload={load} beforeNavigate={beforeNavigate} onAdd={()=>setMedOpen(true)}/>} {tab==='psychometrics'&&<PatientPsychometrics bundle={bundle} reload={load}/>}</>}</div></div>
 </div></section>{medOpen&&<MedicationModal bundle={bundle} onClose={()=>setMedOpen(false)} onSaved={load}/>}
 {pendingStart&&<AppointmentStartConfirmation scheduledStart={pendingStart.appointment.scheduled_start} onCancel={()=>setPendingStart(null)} onConfirm={()=>{const pending=pendingStart;setPendingStart(null);void startSession(pending.appointment.id,pending.type,true)}}/>}
 {appointmentChoices.length>1&&<div className="entry-modal-backdrop" onClick={()=>setAppointmentChoices([])}><section className="entry-modal appointment-choice-modal" onClick={e=>e.stopPropagation()}><button className="entry-close" onClick={()=>setAppointmentChoices([])} aria-label="Κλείσιμο"><X size={19}/></button><span className="kicker">ΝΕΑ ΚΑΤΑΓΡΑΦΗ</span><h2>Ποιο σημερινό ραντεβού;</h2><p>Υπάρχουν περισσότερα από ένα προγραμματισμένα ραντεβού για τον ίδιο ασθενή. Επιλέξτε σε ποιο ραντεβού ανήκει η καταγραφή.</p><div className="appointment-choice-list">{appointmentChoices.map(a=><button key={a.id} disabled={starting} onClick={()=>void startSession(a.id)}><strong>{formatClinicAppointment(a.scheduled_start)}</strong><span>{a.appointment_type==='initial_assessment'?'Αρχική αξιολόγηση':a.appointment_type==='other'?'Άλλο':'Follow-up'}</span></button>)}</div><button disabled={starting} onClick={()=>setAppointmentChoices([])}>Ακύρωση</button></section></div>}
 {visitId&&<VisitWorkspace beforeNavigate={beforeNavigate} key={visitId} sessionId={visitId} patientId={p.id} context={contextReady?bundle:null} reloadContext={load} onClose={()=>{navigationSequence.current++;applyTab('summary',null,bundle,{clearAppointment:true})}} onDeferred={async()=>{navigationSequence.current++;setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.');applyTab('sessions',null,bundle,{clearAppointment:true})}} onFinalized={async session=>{navigationSequence.current++;setRecordNotice('');const optimistic=bundle?{...bundle,sessions:bundle.sessions.map(s=>s.id===session.id?session:s),appointments:bundle.appointments.map(a=>a.session_id===session.id?{...a,status:'completed'}:a)}:null;if(optimistic){setBundle(optimistic);applyTab('sessions',session.id,optimistic,{clearAppointment:true})}else applyTab('sessions',session.id,null,{clearAppointment:true});const shell=await loadShell();if(shell){const refreshed=optimistic?{...optimistic,patient:shell.patient,sessions:shell.sessions,appointments:shell.appointments}:shell;setBundle(refreshed);applyTab('sessions',session.id,refreshed,{clearAppointment:true})}void load()}} onSelect={(id)=>{navigationSequence.current++;applyTab('sessions',id)}}/>}
 </main>
}
function Nav({active,onClick,icon,label,badge}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;badge?:string}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span>{badge&&<i>{badge}</i>}</button>}

function NewPatientSummary({bundle,onDetails,onStart}:{bundle:PatientBundle;onDetails:()=>void;onStart:()=>void}){
 const draft=bundle.sessions.find(s=>s.status==='draft');
 return <section className="new-patient-home clinical-start minimal-start">
  <div className="clinical-start-copy">
   <button className="clinical-start-cta" onClick={onStart}><span>{draft?(draft.session_type==='initial_assessment'?'Συνέχεια καταγραφής αρχικής αξιολόγησης':'Συνέχεια καταγραφής follow-up'):'Νέα καταγραφή αρχικής αξιολόγησης'}</span><span aria-hidden="true">→</span></button>
   <div className="clinical-start-scope">Λόγος προσέλευσης <i>·</i> MSE <i>·</i> Risk <i>·</i> Ιστορικό <i>·</i> Διάγνωση <i>·</i> Αγωγή <i>·</i> Πλάνο</div>
  </div>
  <button className="patient-details-link" onClick={onDetails}>Στοιχεία ασθενή <span aria-hidden="true">→</span></button>
 </section>
}
