'use client';
import PilotProfile from '@/components/PilotProfile';
import AppointmentStartConfirmation from '@/components/calendar/AppointmentStartConfirmation';
import PatientRecordSummary from './PatientRecordSummary';
import PatientTimeline from './PatientTimeline';
import PatientTreatment from './PatientTreatment';
import styles from './PatientRecord.module.css';
import {patientRecord} from '@/lib/clinical/patient-record';
import VisitWorkspace from './VisitWorkspace';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import {hasCompletedClinicalHistory,workspaceHeroAction,workspaceMeasurementSearch,workspaceSelectedAssessment,workspaceMeasurementsRequested,workspaceLocation,workspaceTransitionSearch,type WorkspaceTab} from '@/lib/clinical/visit-workspace-state';
import { BookOpen, CalendarDays, FileText, History as HistoryIcon, Home, Menu, Pill, Plus, Users, X } from 'lucide-react';
import { getDemoTesterId } from '@/lib/demo-tester';
import type { DemoSession, PatientBundle } from '@/lib/patients/demo-runtime';
import { demoPost } from '@/lib/patients/demo-client';
import PatientSession from '@/components/patients/PatientSession';
import { HistoryPanel } from '@/components/patients/PatientPanels';
import { formatClinicAppointment } from '@/lib/clinic-time';

type Tab=WorkspaceTab;
export default function PatientWorkspace({patientRef}:{patientRef:string}){
 const [pendingStart,setPendingStart]=useState<{appointment:PatientBundle['appointments'][number];type:'initial_assessment'|'follow_up'}|null>(null);
 const beforeNavigate=useRef<(()=>Promise<void>)|null>(null);
 const currentUrl=useRef('');
 const historyRead=useRef<()=>Promise<void>>(async()=>{});
 const navigationSequence=useRef(0);
 const startingRef=useRef(false);
 const shellLoadSequence=useRef(0);const fullLoadSequence=useRef(0);
 const activePatientRef=useRef(patientRef);activePatientRef.current=patientRef;
 const [contextReady,setContextReady]=useState(false); const [visitId,setVisitId]=useState<string|null>(null); const [visitType,setVisitType]=useState<'initial_assessment'|'follow_up'>('initial_assessment'); const [bundle,setBundle]=useState<PatientBundle|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [tab,setTabState]=useState<Tab>('summary'); const [sessionRef,setSessionRef]=useState<string|null>(null); const [mobileNav,setMobileNav]=useState(false); const [starting,setStarting]=useState(false); const [finalizing,setFinalizing]=useState(false); const [finalizeError,setFinalizeError]=useState('');
 const [measurementsOpen,setMeasurementsOpen]=useState(false);
 const [selectedAssessmentId,setSelectedAssessmentId]=useState<string|null>(null);
 const [recordNotice,setRecordNotice]=useState(''); const [appointmentChoices,setAppointmentChoices]=useState<PatientBundle['appointments']>([]);
 async function loadShell(){const requestedPatient=patientRef;const sequence=++shellLoadSequence.current;try{const r=await fetch(`/api/patients/demo/visit?tester=${getDemoTesterId()}&patient=${encodeURIComponent(requestedPatient)}`,{cache:'no-store'});const d=await r.json();if(activePatientRef.current!==requestedPatient||sequence!==shellLoadSequence.current)return null;if(!r.ok)throw new Error(d.error);setBundle(current=>current?{...current,patient:d.bundle.patient,sessions:d.bundle.sessions,appointments:d.bundle.appointments}:d.bundle);setLoading(false);const location=workspaceLocation(window.location.search);setVisitId(location.tab==='timeline'&&location.sessionId&&d.bundle.sessions.some((s:{id:string;status:string})=>s.id===location.sessionId&&s.status==='draft')?location.sessionId:null);return d.bundle as PatientBundle}catch(cause){if(activePatientRef.current===requestedPatient&&sequence===shellLoadSequence.current)setError(cause instanceof Error?cause.message:'Δεν φορτώθηκε ο φάκελος.');return null}}
 async function load(){const requestedPatient=patientRef;const sequence=++fullLoadSequence.current;try{const tester=getDemoTesterId();const response=await fetch(`/api/patients/demo/runtime?tester=${tester}&patient=${encodeURIComponent(requestedPatient)}`,{cache:'no-store'});const data=await response.json();if(activePatientRef.current!==requestedPatient||sequence!==fullLoadSequence.current)return null;if(!response.ok)throw new Error(data.error);setBundle(data.bundle);setContextReady(true);setError('');const location=workspaceLocation(window.location.search);if(location.tab==='timeline'&&location.sessionId)setVisitId(data.bundle.sessions.some((row:DemoSession)=>row.id===location.sessionId&&row.status==='draft')?location.sessionId:null);return data.bundle as PatientBundle}catch(cause){if(activePatientRef.current===requestedPatient&&sequence===fullLoadSequence.current)setError(cause instanceof Error?cause.message:'Δεν φορτώθηκε η καρτέλα.');return null}finally{if(activePatientRef.current===requestedPatient&&sequence===fullLoadSequence.current)setLoading(false)}}
 function applyLocation(search:string,source:PatientBundle|null=bundle){const location=workspaceLocation(search);setMeasurementsOpen(workspaceMeasurementsRequested(search));setSelectedAssessmentId(workspaceSelectedAssessment(search));setPendingStart(null);setAppointmentChoices([]);setTabState(location.tab);setSessionRef(location.sessionId);setVisitId(location.tab==='timeline'&&location.sessionId&&source?.sessions.some(s=>s.id===location.sessionId&&s.status==='draft')?location.sessionId:null)}
 function applyTab(next:Tab,sessionId?:string|null,source:PatientBundle|null=bundle,options:{clearAppointment?:boolean}={}){setMeasurementsOpen(false);setSelectedAssessmentId(null);setError('');setPendingStart(null);setAppointmentChoices([]);setVisitId(next==='timeline'&&sessionId&&source?.sessions.some(s=>s.id===sessionId&&s.status==='draft')?sessionId:null);setTabState(next);setSessionRef(next==='timeline'?(sessionId||null):null);const search=workspaceTransitionSearch(window.location.search,next,sessionId,options);const target=window.location.pathname+search+window.location.hash;const current=window.location.pathname+window.location.search+window.location.hash;if(target!==current)window.history.pushState({},'',target);currentUrl.current=window.location.href}
 historyRead.current=async()=>{const sequence=++navigationSequence.current;const target=window.location.href;try{await beforeNavigate.current?.();if(sequence!==navigationSequence.current)return;const targetSearch=new URL(target).search;const targetLocation=workspaceLocation(targetSearch);if(visitId&&targetLocation.sessionId!==visitId){await demoPost({action:'finish_session_later',session_id:visitId});setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.')}if(sequence!==navigationSequence.current)return;applyLocation(targetSearch);currentUrl.current=target}catch(cause){if(sequence!==navigationSequence.current)return;setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκε η πρόχειρη καταγραφή.');window.history.replaceState({},'',currentUrl.current)}};
 useEffect(()=>{navigationSequence.current++;shellLoadSequence.current++;fullLoadSequence.current++;beforeNavigate.current=null;setBundle(null);setContextReady(false);setVisitId(null);setSessionRef(null);setTabState('summary');setError('');setRecordNotice('');setLoading(true);currentUrl.current=window.location.href;applyLocation(window.location.search,null);void loadShell();void load();const read=()=>{void historyRead.current()};window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read)},[patientRef]);
 useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible'&&['summary','history'].includes(tab))void load()};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[patientRef,tab]);
 async function setTab(next:Tab,sessionId?:string|null){const sequence=++navigationSequence.current;try{await beforeNavigate.current?.()}catch(cause){if(sequence===navigationSequence.current)setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκαν οι αλλαγές.');return false}if(sequence!==navigationSequence.current)return false;applyTab(next,sessionId);if(!sessionId)window.scrollTo({top:0});return true}
 async function showMeasurements(assessmentId?:string){if(!await setTab('treatment'))return;const search=workspaceMeasurementSearch(window.location.search,assessmentId);window.history.replaceState({},'',window.location.pathname+search+window.location.hash);currentUrl.current=window.location.href;setSelectedAssessmentId(assessmentId||null);setMeasurementsOpen(true)}
 async function startSession(appointmentId?:string,type=visitType,confirmed=false){
  if(!bundle||startingRef.current)return;
  startingRef.current=true;setStarting(true);setVisitType(type);
  try{
   await beforeNavigate.current?.();
   const activeBundle=await loadShell();
   if(!activeBundle)throw new Error('Δεν ανανεώθηκε ο φάκελος πριν τη δημιουργία της καταγραφής.');
   const draft=activeBundle.sessions.find(s=>s.status==='draft');
   const requestedId=appointmentId||new URLSearchParams(window.location.search).get('appointment');
   const requested=requestedId?activeBundle.appointments.find(a=>a.id===requestedId):undefined;
   if(requestedId&&!requested){const clean=workspaceTransitionSearch(window.location.search,tab,sessionRef,{clearAppointment:true});window.history.replaceState({},'',window.location.pathname+clean+window.location.hash);throw new Error('Το συγκεκριμένο ραντεβού δεν ανήκει πλέον στον φάκελο.');}
   if(requested&&requested.status!=='scheduled'&&!requested.session_id){const clean=workspaceTransitionSearch(window.location.search,tab,sessionRef,{clearAppointment:true});window.history.replaceState({},'',window.location.pathname+clean+window.location.hash);throw new Error('Το συγκεκριμένο ραντεβού δεν είναι πλέον ενεργό.');}
   if(requested?.session_id){navigationSequence.current++;applyTab('timeline',requested.session_id,activeBundle,{clearAppointment:true});return}
   if(draft&&!requested){navigationSequence.current++;applyTab('timeline',draft.id,activeBundle,{clearAppointment:true});return}
   const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
   const sameDay=activeBundle.appointments.filter(a=>a.status==='scheduled'&&!a.session_id&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(a.scheduled_start))===today);
   if(!requestedId&&sameDay.length>1){setAppointmentChoices(sameDay);return}
   const appointment=requested||(sameDay.length===1?sameDay[0]:undefined);
   if(appointment&&!appointment.session_id&&new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Athens',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(appointment.scheduled_start))!==today&&!confirmed){setPendingStart({appointment,type});return}
   setError('');
   const result=await demoPost({action:'start_session',patient_id:activeBundle.patient.id,session_type:appointment?.appointment_type||type,appointment_id:appointment?.id||null}) as {session?:{id?:string}};
   fullLoadSequence.current++;
   setAppointmentChoices([]);const id=result.session?.id;if(!id)throw new Error('Δεν επιστράφηκε συνεδρία.');
   const shell=await loadShell();if(!shell)throw new Error('Η καταγραφή δημιουργήθηκε αλλά ο φάκελος δεν ανανεώθηκε.');const refreshed=bundle?{...bundle,patient:shell.patient,sessions:shell.sessions,appointments:shell.appointments}:shell;setBundle(refreshed);navigationSequence.current++;applyTab('timeline',id,refreshed,{clearAppointment:true});void load();
  }catch(cause){setError(cause instanceof Error?cause.message:'Δεν δημιουργήθηκε η καταγραφή.')}
  finally{startingRef.current=false;setStarting(false)}
 }
 async function finalize(sessionId:string){setFinalizing(true);setFinalizeError('');setRecordNotice('');let committed=false;try{const shell=await loadShell();const draft=shell?.sessions.find(s=>s.id===sessionId&&s.status==='draft');if(!draft)throw new Error('Το συγκεκριμένο πρόχειρο δεν είναι πλέον διαθέσιμο.');const result=await demoPost({action:'finalize_session',session_id:draft.id,expected_version:draft.version}) as {session:DemoSession};committed=true;fullLoadSequence.current++;const optimistic=bundle?{...bundle,sessions:bundle.sessions.map(s=>s.id===result.session.id?result.session:s),appointments:bundle.appointments.map(a=>a.session_id===result.session.id?{...a,status:'completed'}:a)}:null;if(optimistic){setBundle(optimistic);applyTab('timeline',result.session.id,optimistic)}const nextShell=await loadShell();if(nextShell){const refreshed=bundle?{...(optimistic||bundle),patient:nextShell.patient,sessions:nextShell.sessions,appointments:nextShell.appointments}:nextShell;setBundle(refreshed);applyTab('timeline',result.session.id,refreshed)}void load()}catch(cause){setFinalizeError(committed?'Η καταγραφή ολοκληρώθηκε, αλλά η προβολή δεν ανανεώθηκε. Ανανεώστε τον φάκελο.':cause instanceof Error?cause.message:'Δεν ολοκληρώθηκε η καταγραφή.')}finally{setFinalizing(false)}}
 async function finishLater(sessionId:string,reason?:string){setFinalizeError('');try{await demoPost({action:'finish_session_later',session_id:sessionId});setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.'+(reason?' '+reason:''));applyTab('timeline',null,bundle)}catch(cause){setFinalizeError(cause instanceof Error?cause.message:'Δεν δημιουργήθηκε η εκκρεμότητα.')}}
 if(loading)return <main className="clinical-page"><div className="record-state">Φόρτωση κλινικού φακέλου…</div></main>; if(error&&!bundle)return <main className="clinical-page"><Link href="/patients" className="back">← Ασθενείς</Link><div className="record-state error" role="alert">{error}</div></main>; if(!bundle)return null;
 async function exportRecord(){try{const r=await fetch('/api/patients/demo/export?tester='+getDemoTesterId()+'&patient='+bundle!.patient.id);if(!r.ok)throw new Error('Δεν έγινε εξαγωγή.');const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download='noima-patient-'+bundle!.patient.id+'.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(cause){setError(cause instanceof Error?cause.message:'Δεν έγινε εξαγωγή.')}}
 const appointmentRef=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('appointment'):null;
 const intended=bundle.appointments.find(a=>a.id===appointmentRef&&(a.status==='scheduled'||Boolean(a.session_id)));
 const record=patientRecord(bundle); const p=bundle.patient; const draft=bundle.sessions.find(s=>s.status==='draft'); const completed=bundle.sessions.filter(s=>s.status==='completed'); const draftAppointment=draft?bundle.appointments.find(a=>a.session_id===draft.id):undefined; const heroAppointment=draft?draftAppointment:intended; const isEstablished=hasCompletedClinicalHistory(bundle); const heroAction=workspaceHeroAction(isEstablished,Boolean(draft),Boolean(heroAppointment));
 return <main className="app-shell secondary-shell" onClickCapture={e=>{const link=(e.target as HTMLElement).closest('a');if(!link||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||link.target==='_blank'||link.hasAttribute('download'))return;const url=new URL(link.href);if(url.origin!==window.location.origin||!beforeNavigate.current)return;e.preventDefault();e.stopPropagation();const sequence=++navigationSequence.current;void beforeNavigate.current!().then(()=>{if(sequence===navigationSequence.current)window.location.assign(url.href)}).catch(cause=>{if(sequence===navigationSequence.current)setError(cause instanceof Error?cause.message:'Δεν αποθηκεύτηκαν οι αλλαγές.')})}}><aside className={mobileNav?'sidebar mobile-open':'sidebar'}><button className="mobile-nav-close" onClick={()=>setMobileNav(false)} aria-label="Κλείσιμο μενού"><X size={20}/></button><div className="brand"><div className="brand-mark">Ψ</div><div className="brand-copy"><div className="brand-sub">Για μια οργανωμένη κλινική πράξη</div></div></div><nav className="nav"><Link href="/" className="nav-item"><Home size={19}/><span>Επισκόπηση</span></Link><Link href="/calendar" className="nav-item"><CalendarDays size={19}/><span>Ημερολόγιο</span></Link><Link href="/patients" className="nav-item active"><Users size={19}/><span>Ασθενείς</span></Link><Link href="/psychometrics" className="nav-item"><BookOpen size={19}/><span>Βιβλιοθήκη</span></Link></nav></aside>{mobileNav&&<button className="mobile-nav-backdrop" aria-label="Κλείσιμο μενού" onClick={()=>setMobileNav(false)}/>}<section className={`workspace ${styles.workspace}`}><header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileNav(true)} aria-label="Άνοιγμα μενού"><Menu size={21}/></button><PilotProfile/></header><div className="generic-patient-page">
  <div className={`patient-hero compact ${styles.identity} ${styles.hero}`}><div><span className="kicker">FICTIONAL TEST DATA</span><h1>{p.first_name} {p.last_name}</h1><p className="patient-record-context">Κλινικός φάκελος{p.reported_age!==null?` · ${p.reported_age} ετών`:``}{!isEstablished?` · Νέος ασθενής`:``}{p.amka?` · ΑΜΚΑ ••••${p.amka.slice(-4)}`:``}</p>{record.latestVisit&&<p className={styles.headerNote}>Τελευταία επίσκεψη · {formatClinicAppointment(record.latestVisit.started_at)}</p>}{record.nextAppointment&&<p className={styles.headerNote}>Επόμενο ραντεβού · {formatClinicAppointment(record.nextAppointment.scheduled_start)}</p>}</div><button className={`patient-voice-cta ${heroAction==='new_initial'?styles.compactHeroAction:''}`} onClick={()=>void startSession(heroAppointment?.id,draft?(draft.session_type==='initial_assessment'?'initial_assessment':'follow_up'):isEstablished?'follow_up':'initial_assessment')} disabled={starting}><span className="patient-voice-icon"><Plus size={19}/></span><span><strong>{heroAction==='resume'?(draft?'Συνέχεια καταγραφής':heroAppointment?.session_id?'Άνοιγμα καταγραφής':'Νέα καταγραφή'):heroAction==='new_initial'?'Έναρξη αρχικής αξιολόγησης':'Νέα επανεξέταση'}</strong>{heroAction!=='new_initial'&&<small>{draft?'Πρόχειρο · αποθηκευμένο':heroAppointment?formatClinicAppointment(heroAppointment.scheduled_start):isEstablished?'Επανεξέταση':'Αρχική αξιολόγηση'}</small>}</span></button></div>{error&&<div className="record-state error" role="alert">{error}</div>}
  {recordNotice&&<div className="record-state saved-draft" role="status">{recordNotice}</div>}<div className={`patient-workspace-shell ${styles.shell}`}><nav className={styles.tabs} aria-label="Καρτέλες φακέλου"><Nav active={tab==='summary'} onClick={()=>void setTab('summary')} icon={<FileText size={16}/>} label="Συνέχεια φροντίδας"/><Nav active={tab==='timeline'} onClick={()=>void setTab('timeline')} icon={<HistoryIcon size={16}/>} label="Πορεία"/><Nav active={tab==='treatment'} onClick={()=>void setTab('treatment')} icon={<Pill size={16}/>} label="Θεραπεία"/><details className={styles.more}><summary aria-label="Περισσότερες επιλογές φακέλου">⋯</summary><Nav active={tab==='history'} onClick={()=>void setTab('history')} icon={<BookOpen size={16}/>} label="Στοιχεία & ιστορικό"/><button onClick={()=>void exportRecord()} aria-label="Εξαγωγή φακέλου"><FileText size={16}/><span>Εξαγωγή</span></button></details></nav>
   <div className={`patient-workspace-content ${styles.contentSurface}`}>{!contextReady&&<p role="status">Φόρτωση διαχρονικού φακέλου…</p>}{contextReady&&<>
    {tab==='summary'&&<PatientRecordSummary bundle={bundle} reload={load} onVisit={(id)=>void setTab('timeline',id)} onMeasurements={(id)=>void showMeasurements(id)} onTreatment={()=>void setTab('treatment')} onHistory={()=>void setTab('history')}/>}
    {tab==='timeline'&&!visitId&&<PatientTimeline bundle={bundle} selectedSessionId={sessionRef} onVisit={(id)=>void setTab('timeline',id)} onMeasurements={(id)=>void showMeasurements(id)} onTreatment={()=>void setTab('treatment')} viewer={<PatientSession beforeNavigate={beforeNavigate} bundle={{...bundle,sessions:completed}} reload={load} onFinalize={finalize} onFinishLater={finishLater} finalizing={finalizing} finalizeError={finalizeError} selectedSessionId={sessionRef} onSelectSession={(id)=>void setTab('timeline',id)}/>}/>}
    {tab==='treatment'&&<PatientTreatment bundle={bundle} reload={load} beforeNavigate={beforeNavigate} measurementsOpen={measurementsOpen} selectedAssessmentId={selectedAssessmentId}/>}
    {tab==='history'&&<HistoryPanel bundle={bundle} reload={load} beforeNavigate={beforeNavigate}/>}
   </>}</div></div>
 </div></section>
 {pendingStart&&<AppointmentStartConfirmation scheduledStart={pendingStart.appointment.scheduled_start} onCancel={()=>setPendingStart(null)} onConfirm={()=>{const pending=pendingStart;setPendingStart(null);void startSession(pending.appointment.id,pending.type,true)}}/>}
 {appointmentChoices.length>1&&<div className="entry-modal-backdrop" onClick={()=>setAppointmentChoices([])}><section className="entry-modal appointment-choice-modal" onClick={e=>e.stopPropagation()}><button className="entry-close" onClick={()=>setAppointmentChoices([])} aria-label="Κλείσιμο"><X size={19}/></button><span className="kicker">ΝΕΑ ΚΑΤΑΓΡΑΦΗ</span><h2>Ποιο σημερινό ραντεβού;</h2><p>Υπάρχουν περισσότερα από ένα προγραμματισμένα ραντεβού για τον ίδιο ασθενή. Επιλέξτε σε ποιο ραντεβού ανήκει η καταγραφή.</p><div className="appointment-choice-list">{appointmentChoices.map(a=><button key={a.id} disabled={starting} onClick={()=>void startSession(a.id)}><strong>{formatClinicAppointment(a.scheduled_start)}</strong><span>{a.appointment_type==='initial_assessment'?'Αρχική αξιολόγηση':a.appointment_type==='other'?'Άλλο':'Επανεξέταση'}</span></button>)}</div><button disabled={starting} onClick={()=>setAppointmentChoices([])}>Ακύρωση</button></section></div>}
 {visitId&&<VisitWorkspace beforeNavigate={beforeNavigate} key={visitId} sessionId={visitId} patientId={p.id} context={contextReady?bundle:null} reloadContext={load} onClose={()=>{navigationSequence.current++;applyTab('summary',null,bundle,{clearAppointment:true})}} onDeferred={async(_,reason)=>{navigationSequence.current++;setRecordNotice('Η καταγραφή αποθηκεύτηκε ως πρόχειρη και προστέθηκε στις εκκρεμότητές σας.'+(reason?' '+reason:''));applyTab('timeline',null,bundle,{clearAppointment:true})}} onFinalized={async session=>{navigationSequence.current++;setRecordNotice('');const destination=session.continuity?'summary':'timeline';const selectedId=session.continuity?null:session.id;const optimistic=bundle?{...bundle,sessions:bundle.sessions.map(s=>s.id===session.id?session:s),appointments:bundle.appointments.map(a=>a.session_id===session.id?{...a,status:'completed'}:a)}:null;if(optimistic){setBundle(optimistic);applyTab(destination,selectedId,optimistic,{clearAppointment:true})}else applyTab(destination,selectedId,null,{clearAppointment:true});const shell=await loadShell();if(shell){const refreshed=optimistic?{...optimistic,patient:shell.patient,sessions:shell.sessions,appointments:shell.appointments}:shell;setBundle(refreshed);applyTab(destination,selectedId,refreshed,{clearAppointment:true})}void load()}} onSelect={(id)=>{navigationSequence.current++;applyTab('timeline',id)}}/>}
 </main>
}
function Nav({active,onClick,icon,label,badge}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;badge?:string}){return <button aria-current={active?'page':undefined} onClick={onClick}>{icon}<span>{label}</span>{badge&&<i>{badge}</i>}</button>}
