'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Check, CheckCircle2, Mic2, ShieldCheck } from 'lucide-react';
import SectionDictation from '@/components/dictation/SectionDictation';
import type { DemoRisk, DemoSection, PatientBundle } from '@/lib/patients/demo-runtime';
import { demoPost } from '@/lib/patients/demo-client';

const definitions=[
 ['interview','Ψυχιατρική συνέντευξη / συμπτώματα','Αίτημα, συμπτώματα, πορεία και τι άλλαξε.'],
 ['functioning','Λειτουργικότητα','Εργασία, σχέσεις, καθημερινότητα και ύπνος.'],
 ['effects','Παρενέργειες','Ανεπιθύμητες ενέργειες και επίδρασή τους.'],
 ['adherence','Συμμόρφωση','Λήψη αγωγής, παραλείψεις και δυσκολίες.'],
 ['mse','Εξέταση ψυχικής κατάστασης (MSE)','Στοχευμένα ευρήματα της σημερινής εξέτασης.'],
 ['assessment','Κλινική εκτίμηση','Διάγνωση / διαφορική, formulation και κλινική αποτίμηση.'],
 ['plan','Θεραπευτικό πλάνο','Αγωγή, παρεμβάσεις, παραπομπές και οδηγίες.'],
 ['review','Επανεκτίμηση','Χρονικός ορίζοντας και τι πρέπει να ελεγχθεί στην επίσκεψη.'],
] as const;
const required=new Set(['interview','mse','assessment','plan','review']);
const fmt=(value?:string|null)=>value?new Intl.DateTimeFormat('el-GR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';

export default function PatientSession({bundle,reload,onFinalize,finalizing,finalizeError}:{bundle:PatientBundle;reload:()=>Promise<unknown>;onFinalize:()=>Promise<void>;finalizing:boolean;finalizeError:string}){
 const draft=bundle.sessions.find(s=>s.status==='draft'); const completed=bundle.sessions.filter(s=>s.status==='completed');
 if(!draft)return <section className="panel-stack"><div className="panel-heading"><div><span className="kicker">ΣΥΝΕΔΡΙΕΣ</span><h2>Ολοκληρωμένες συνεδρίες</h2><p>Δεν υπάρχει ανοιχτό πρόχειρο.</p></div></div>{completed.length?<div className="completed-session-list">{completed.map(s=><article key={s.id}><CheckCircle2 size={18}/><div><strong>{s.session_type==='initial_assessment'?'Αρχική αξιολόγηση':'Επαναληπτική συνεδρία'}</strong><span>Οριστικοποιήθηκε {fmt(s.completed_at)}</span></div></article>)}</div>:<div className="panel-empty">Δεν υπάρχει ακόμη συνεδρία.</div>}</section>;
 const risk=bundle.risks.find(x=>x.session_id===draft.id); const sections=bundle.sections.filter(x=>x.session_id===draft.id); const completeKeys=new Set(sections.filter(x=>x.content.trim()).map(x=>x.section_key)); const ready=[...required].every(x=>completeKeys.has(x))&&risk?.suicidal_ideation!=='not_assessed'&&Boolean(risk);
 return <section className="session-workspace runtime-session"><div className="session-work-head"><div><span className="visit-label"><span>ΠΡΟΧΕΙΡΟ</span><i/> {draft.session_type==='initial_assessment'?'ΑΡΧΙΚΗ ΑΞΙΟΛΟΓΗΣΗ':'FOLLOW-UP'}</span><h2>{draft.session_type==='initial_assessment'?'Αρχική αξιολόγηση':'Επαναληπτική συνεδρία'}</h2><p>Η καταγραφή αποθηκεύεται ανά ενότητα. Η οριστικοποίηση είναι ξεχωριστή ενέργεια και κλειδώνει αυτή την έκδοση.</p></div><span className="draft-updated">Έναρξη {fmt(draft.started_at)}</span></div>
  <div className="sections-label"><span className="kicker">ΚΛΙΝΙΚΗ ΚΑΤΑΓΡΑΦΗ</span><span>* απαιτείται για ολοκλήρωση</span></div><div className="clinical-sections">{definitions.map(([key,title,hint])=><SectionEditor key={`${draft.id}:${key}`} sessionId={draft.id} definition={{key,title,hint}} existing={sections.find(x=>x.section_key===key)} onSaved={reload}/>)}<RiskEditor sessionId={draft.id} existing={risk} onSaved={reload}/></div>
  <div className="finalize-bar"><div><strong>{ready?'Έτοιμη για ολοκλήρωση':'Χρειάζεται έλεγχο'}</strong><span>{ready?'Όλες οι βασικές ενότητες και η εκτίμηση κινδύνου έχουν καταγραφεί.':'Συμπληρώστε τις ενότητες με * και εκτιμήστε αυτοκτονικό ιδεασμό.'}</span></div><button onClick={()=>void onFinalize()} disabled={finalizing||!ready}><Check size={16}/>{finalizing?'Ολοκλήρωση…':'Έλεγχος & ολοκλήρωση'}</button></div>{finalizeError&&<div className="save-state error" role="alert">{finalizeError}</div>}
  {completed.length>0&&<div className="previous-visits"><span className="kicker">ΠΡΟΗΓΟΥΜΕΝΕΣ</span>{completed.map(s=><article className="completed-source" key={s.id}><strong>{s.session_type==='initial_assessment'?'Αρχική αξιολόγηση':'Follow-up'}</strong><span>{fmt(s.completed_at)}</span></article>)}</div>}
 </section>
}

function SectionEditor({sessionId,definition,existing,onSaved}:{sessionId:string;definition:{key:string;title:string;hint:string};existing?:DemoSection;onSaved:()=>Promise<unknown>}){
 const [value,setValue]=useState(existing?.content||''); const [status,setStatus]=useState(existing?.content?'Αποθηκεύτηκε':''); const [dictating,setDictating]=useState(false); const [pending,setPending]=useState(''); const lastSaved=useRef(existing?.content||''); const versionRef=useRef<number|null>(existing?.version??null); const timer=useRef<ReturnType<typeof setTimeout>|null>(null); const inFlight=useRef(false); const queued=useRef<string|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{if(value===lastSaved.current)return;if(timer.current)clearTimeout(timer.current);setStatus('Αποθηκεύεται…');timer.current=setTimeout(()=>{void save(value)},700)},[value]);
 async function save(content:string){if(inFlight.current){queued.current=content;return}inFlight.current=true;try{const data=await demoPost({action:'save_section',session_id:sessionId,section_key:definition.key,content,source:'manual',expected_version:versionRef.current});versionRef.current=data.section.version;lastSaved.current=content;setStatus(`Αποθηκεύτηκε ${new Date().toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit'})}`);await onSaved()}catch(cause){setStatus(cause instanceof Error?cause.message:'Αποτυχία αποθήκευσης')}finally{inFlight.current=false;const next=queued.current;queued.current=null;if(next!==null&&next!==lastSaved.current)void save(next)}}
 function acceptDictation(text:string){setDictating(false);if(value.trim())setPending(text);else setValue(text)}
 return <div className={value.trim()?'clinical-section populated':'clinical-section'}><div className="clinical-section-head"><div><h3>{definition.title}{required.has(definition.key)&&' *'}</h3><span>{definition.hint}</span></div><button className="section-mic" onClick={()=>setDictating(true)}><Mic2 size={15}/> Υπαγόρευση</button></div><textarea className="section-editor" rows={value.length>280?7:4} value={value} onChange={e=>setValue(e.target.value)} placeholder="Γράψτε ή υπαγορεύστε. Κενό = δεν έχει καταγραφεί."/><div className={status.startsWith('Αποτυχία')||status.includes('άλλαξε')?'section-save-state error':'section-save-state'}>{status||'Δεν έχει αποθηκευτεί ακόμη'}</div>{dictating&&<SectionDictation title={definition.title} onClose={()=>setDictating(false)} onInsert={acceptDictation}/>} {pending&&<div className="dictation-insert-choice"><div><strong>Υπάρχει ήδη κείμενο</strong><span>Πώς θέλετε να χρησιμοποιηθεί η νέα μεταγραφή;</span></div><button onClick={()=>{setValue(v=>`${v.trim()}\n\n${pending}`.trim());setPending('')}}>Προσθήκη</button><button onClick={()=>{setValue(pending);setPending('')}}>Αντικατάσταση</button><button onClick={()=>setPending('')}>Ακύρωση</button></div>}</div>
}

const riskOptions=[['not_assessed','Δεν διερευνήθηκε'],['unknown','Άγνωστο'],['negative','Αρνητικό'],['positive','Θετικό']] as const;
function RiskEditor({sessionId,existing,onSaved}:{sessionId:string;existing?:DemoRisk;onSaved:()=>Promise<unknown>}){
 const [risk,setRisk]=useState({suicidal_ideation:existing?.suicidal_ideation||'not_assessed',intent:existing?.intent||'not_assessed',plan:existing?.plan||'not_assessed',self_harm:existing?.self_harm||'not_assessed',attempt_history:existing?.attempt_history||'not_assessed',protective_factors:existing?.protective_factors||'',clinical_note:existing?.clinical_note||''}); const [version,setVersion]=useState<number|null>(existing?.version??null); const [state,setState]=useState(existing?'Αποθηκεύτηκε':''); const [saving,setSaving]=useState(false);
 async function save(){setSaving(true);setState('');try{const data=await demoPost({action:'save_risk',session_id:sessionId,risk,expected_version:version});setVersion(data.risk.version);setState(`Αποθηκεύτηκε ${new Date().toLocaleTimeString('el-GR',{hour:'2-digit',minute:'2-digit'})}`);await onSaved()}catch(cause){setState(cause instanceof Error?cause.message:'Αποτυχία αποθήκευσης')}finally{setSaving(false)}}
 return <div className="clinical-section risk-editor"><div className="clinical-section-head"><div><h3>Εκτίμηση κινδύνου *</h3><span>Το «Δεν διερευνήθηκε» διαφέρει από αρνητικό εύρημα.</span></div><ShieldCheck size={18}/></div><div className="risk-grid">{[['suicidal_ideation','Αυτοκτονικός ιδεασμός'],['intent','Πρόθεση'],['plan','Σχέδιο'],['self_harm','Αυτοτραυματισμός'],['attempt_history','Ιστορικό απόπειρας']].map(([key,label])=><label key={key}>{label}<select value={risk[key as keyof typeof risk]} onChange={e=>setRisk(v=>({...v,[key]:e.target.value}))}>{riskOptions.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}</div><label className="risk-note">Προστατευτικοί παράγοντες<textarea rows={2} value={risk.protective_factors} onChange={e=>setRisk(v=>({...v,protective_factors:e.target.value}))}/></label><label className="risk-note">Κλινική σημείωση<textarea rows={2} value={risk.clinical_note} onChange={e=>setRisk(v=>({...v,clinical_note:e.target.value}))}/></label><div className="risk-save"><span>{state||'Δεν έχει αποθηκευτεί'}</span><button onClick={()=>void save()} disabled={saving}>{saving?'Αποθήκευση…':'Αποθήκευση risk'}</button></div></div>
}
