'use client';
import {useState} from 'react';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
import {getDemoTesterId} from '@/lib/demo-tester';
import {instruments,answerLabels} from '@/lib/psychometrics/instruments';
import {formatClinicDate,formatClinicDateTime} from '@/lib/clinic-time';
export default function PatientPsychometrics({bundle,reload,sessionId}:{bundle:PatientBundle;reload:()=>Promise<unknown>;sessionId?:string}){
 const [instrument,setInstrument]=useState('PHQ-9'),[appointment,setAppointment]=useState(''),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<{id:string;token:string}|null>(null);
 async function call(body:Record<string,unknown>){const r=await fetch('/api/psychometrics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,tester:getDemoTesterId()})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function assign(){setBusy(true);setError('');const request=pending||{id:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('')};setPending(request);try{await call({action:'assign',...request,patient_id:bundle.patient.id,instrument,appointment_id:sessionId?null:appointment||null,session_id:sessionId||null});setLink(location.origin+'/assessment#'+request.token);setPending(null);await reload()}catch(e){setError(e instanceof Error?e.message:'Αποτυχία')}finally{setBusy(false)}}
 async function reviewItem9(id:string){setBusy(true);setError('');try{await call({action:'review_item9',id});await reload()}catch(e){setError(e instanceof Error?e.message:'Αποτυχία')}finally{setBusy(false)}}
 async function revoke(id:string){setBusy(true);setError('');try{await call({action:'revoke',id});setLink('');await reload()}catch(e){setError(e instanceof Error?e.message:'Αποτυχία')}finally{setBusy(false)}}
 return <section className="panel-stack"><h2>Ψυχομετρικά</h2><div className="assessment-assign"><label>Εργαλείο<select disabled={busy||Boolean(pending)} value={instrument} onChange={e=>setInstrument(e.target.value)}><option>PHQ-9</option><option>GAD-7</option></select></label>{!sessionId&&<label>Σύνδεση με προγραμματισμένο ραντεβού (προαιρετικό)<select disabled={busy||Boolean(pending)} value={appointment} onChange={e=>setAppointment(e.target.value)}><option value="">Χωρίς σύνδεση</option>{bundle.appointments.filter(a=>a.status==='scheduled'&&new Date(a.scheduled_start)>new Date()).map(a=><option key={a.id} value={a.id}>{formatClinicDateTime(a.scheduled_start)}</option>)}</select></label>}{sessionId&&<span className="visit-hint">Η ανάθεση συνδέεται με αυτή την επίσκεψη.</span>}<button disabled={busy} onClick={()=>void assign()}>{pending?'Επανάληψη ίδιας ανάθεσης':'Δημιουργία συνδέσμου'}</button></div>
 {link&&<div className="assessment-link"><strong>Δημιουργήθηκε σύνδεσμος · δεν στάλθηκε email</strong><input readOnly value={link} aria-label="Σύνδεσμος συμπλήρωσης"/><button onClick={()=>void navigator.clipboard.writeText(link).catch(()=>setError('Αντιγράψτε τον σύνδεσμο από το πεδίο.'))}>Αντιγραφή</button><a href={link} target="_blank" rel="noreferrer">Άνοιγμα</a><small>Ισχύει για 14 ημέρες. Μετά το κλείσιμο δεν ανακτάται· μπορείτε να ανακαλέσετε και να δημιουργήσετε νέο.</small></div>}
 {error&&<p role="alert">{error}</p>}
 <div className="psychometric-trajectories">{(['PHQ-9','GAD-7'] as const).map(code=>{const scores=bundle.assessments.filter(a=>a.instrument===code&&a.status==='completed').sort((a,b)=>Date.parse(a.completed_at||a.created_at)-Date.parse(b.completed_at||b.created_at));return scores.length?<div key={code}><strong>{code}</strong><p>{scores.map(a=>a.score+' ('+formatClinicDate(a.completed_at||a.created_at)+')').join(' → ')}</p></div>:null})}</div>
 {(['PHQ-9','GAD-7'] as const).map(code=><section key={code}><h3>{code}</h3>{bundle.assessments.filter(a=>a.instrument===code).map(a=>{const expired=!['completed','revoked'].includes(a.status)&&new Date(a.expires_at)<new Date();const label=expired?'Έληξε':({assigned:'Ανατέθηκε',opened:'Ανοίχτηκε',completed:'Ολοκληρώθηκε',revoked:'Ανακλήθηκε'}[a.status]);return <article className="assessment-result" key={a.id}><strong>{formatClinicDate(a.completed_at||a.created_at)} · {label}{a.score!==null?' · '+a.score+' / '+(code==='PHQ-9'?27:21):''}</strong>{a.item9_review&&<div className="review-signal"><p>Λήμμα 9: απάντηση μεγαλύτερη από 0 — {a.item9_reviewed_at?'ελέγχθηκε από τον γιατρό':'προς έλεγχο από τον γιατρό'}. Δεν αποτελεί εκτίμηση κινδύνου.</p>{!a.item9_reviewed_at&&<button disabled={busy} onClick={()=>void reviewItem9(a.id)}>Σήμανση ως ελεγμένο</button>}</div>}{a.appointment_id&&<small>Σύνδεση επίσκεψης: {a.session_id?'συνδέθηκε με κλινική συνεδρία':'ραντεβού χωρίς συνδεδεμένη συνεδρία'}</small>}{a.answers&&<details><summary>Ερωτήσεις και απαντήσεις</summary>{instruments[code].items.map((q,i)=><p key={i}>{i+1}. {q}<br/><b>{answerLabels[a.answers![i]]} ({a.answers![i]})</b></p>)}<small>Έκδοση {a.instrument_version} · βαθμολόγηση στον server</small></details>}{!['completed','revoked'].includes(a.status)&&<button disabled={busy} onClick={()=>void revoke(a.id)}>Ανάκληση συνδέσμου</button>}</article>})}</section>)}
 </section>
}
