'use client';
import {useEffect,useRef,useState} from 'react';
import ClinicalTextField from '@/components/dictation/ClinicalTextField';
import type {DemoRisk,PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {useClinicalDraft} from './useClinicalDraft';
import StableDetails from './StableDetails';
import {riskTreeChoices,riskTreePath,riskTreeHidden,riskTreeQuestions,riskTreeLabel,type RiskTree} from '@/lib/clinical/risk-tree';
function shape(r?:DemoRisk){return {suicidal_ideation:r?.suicidal_ideation||'not_assessed',intent:r?.intent||'not_assessed',plan:r?.plan||'not_assessed',self_harm:r?.self_harm||'not_assessed',attempt_history:r?.attempt_history||'not_assessed',harm_to_others:r?.harm_to_others||'not_assessed',protective_factors:r?.protective_factors||'',clinical_note:r?.clinical_note||'',tree:r?.tree||{version:1 as const,answers:{wish:r?.suicidal_ideation||'not_assessed',intent:r?.intent||'not_assessed',plan:r?.plan||'not_assessed',others:r?.harm_to_others||'not_assessed'},notes:{}}};}
type Props={sessionId:string;existing?:DemoRisk;onSaved:()=>Promise<unknown>;registerFlusher:(key:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(key:string,d:boolean)=>void};
export default function RiskTreeEditor({sessionId,existing,onSaved,registerFlusher,onDirtyChange}:Props){
 const [noteOpen,setNoteOpen]=useState<Record<string,boolean>>({}),[conflict,setConflict]=useState<DemoRisk|null|undefined>();
 const draft=useClinicalDraft({storageKey:sessionId+':risk-tree-v1',initial:shape(existing),version:existing?.version??null,write:async(risk,version)=>{const d=await demoPost({action:'save_risk',session_id:sessionId,risk,expected_version:version});return {value:shape(d.risk),version:d.risk.version as number}},onSaved,onDirty:d=>onDirtyChange('risk',d)});
 useEffect(()=>registerFlusher('risk',draft.flush),[registerFlusher,draft.flush]);
 const current=useRef(draft);current.current=draft;
 const [writing,setWriting]=useState<Record<string,boolean>>({});const writingPending=Object.values(writing).some(Boolean);
 function writingField(fieldKey:string,title:string,value:string){
  const apply=(text:string)=>{const d=current.current.currentValue();return fieldKey.startsWith('note-')?{...d,tree:{...d.tree,notes:{...d.tree.notes,[fieldKey.slice(5)]:text}}}:{...d,[fieldKey]:text}};
  return <ClinicalTextField sessionId={sessionId} section="risk" fieldKey={fieldKey} title={title} value={value} onPendingChange={pending=>setWriting(v=>v[fieldKey]===pending?v:{...v,[fieldKey]:pending})} onChange={text=>current.current.change(apply(text))} onBlur={()=>void draft.flush().catch(()=>{})} registerFlusher={registerFlusher} onDirtyChange={onDirtyChange} onConfirm={async(text,{provenance})=>{
   await current.current.flush();const d=current.current.currentValue();const original=fieldKey.startsWith('note-')?d.tree.notes[fieldKey.slice(5)]||'':d[fieldKey as 'protective_factors'|'clinical_note'];if(original!==provenance.original)throw new Error('Η αρχική σημείωση άλλαξε. Ελέγξτε τη νεότερη έκδοση.');const next=apply(text);current.current.change({...next,tree:{...next.tree,writing_provenance:{...next.tree.writing_provenance,[fieldKey]:provenance}}});await current.current.flush().catch(()=>{});
  }}/>;
 }
 const tree=draft.value.tree;const path=riskTreePath(tree.answers),hidden=riskTreeHidden(tree);
 function answer(id:string,value:string){const fields:Record<string,string>={selfacted:'self_harm',wish:'suicidal_ideation',intent:'intent',plan:'plan',others:'harm_to_others'};draft.change({...draft.value,...(fields[id]?{[fields[id]]:value}:{}),tree:{...tree,answers:{...tree.answers,[id]:value}}});}
 function question(id:string,nested=false){const q=riskTreeQuestions[id];return <section key={id} className={'risk-tree-question '+(nested?'nested':'')} aria-label={q.title}><div className="risk-tree-qhead"><strong>{q.title}</strong><button type="button" className="risk-tree-note-toggle" disabled={writing['note-'+id]} aria-expanded={Boolean(noteOpen[id])} onClick={()=>setNoteOpen(v=>({...v,[id]:!v[id]}))}>{tree.notes[id]?'Σημείωση ●':'＋ Σημείωση'}</button></div>{q.hint&&<p className="risk-tree-hint">{q.hint}</p>}<div className="risk-tree-choices">{q.choices.map(([v,t])=><button type="button" key={v} aria-label={q.title+' '+t} disabled={writingPending} aria-pressed={tree.answers[id]===v} onClick={()=>answer(id,v)}>{t}</button>)}</div>{noteOpen[id]&&<div className="risk-tree-note">{writingField('note-'+id,'Σημείωση: '+q.title,tree.notes[id]||'')}</div>}</section>}
 return <div className="risk-tree-editor"><p className="risk-tree-hint">Καταγράψτε ό,τι διερευνήθηκε σήμερα. Οι επόμενες ερωτήσεις εμφανίζονται ανάλογα με τις απαντήσεις.</p><div className="risk-tree-layout"><div>{path.map((id,i)=>question(id,i>0))}<details className="risk-tree-other"><summary>Κίνδυνος προς άλλους{tree.answers.others&&tree.answers.others!=='not_assessed'?' · '+riskTreeLabel('others',tree.answers.others):''}</summary>{question('others')}</details><StableDetails key={sessionId+':history'} className="risk-tree-other" initialOpen={Boolean(draft.value.self_harm!=='not_assessed'||draft.value.attempt_history!=='not_assessed')}><summary>Πράξη αυτοτραυματισμού & ιστορικό απόπειρας</summary>{(['self_harm','attempt_history'] as const).filter(k=>k!=='self_harm'||!path.some(id=>id==='selfacted'&&tree.answers[id]&&tree.answers[id]!=='not_assessed')).map(k=><div className="risk-tree-question" key={k}><strong>{k==='self_harm'?'Πράξη αυτοτραυματισμού — σημερινή γενική εκτίμηση':'Ιστορικό απόπειρας'}</strong><div className="risk-tree-choices">{riskTreeChoices.map(([v,t])=><button type="button" key={v} aria-label={k+' '+t} disabled={writingPending} aria-pressed={draft.value[k]===v} onClick={()=>draft.change({...draft.value,[k]:v})}>{t}</button>)}</div></div>)}</StableDetails>{(['protective_factors','clinical_note'] as const).map(k=><div className="risk-tree-clinical" key={k}>{writingField(k,k==='protective_factors'?'Προστατευτικοί παράγοντες':'Κλινική αποτίμηση & ενέργειες',draft.value[k])}</div>)}</div><aside className="risk-tree-summary"><h4>ΚΑΤΑΓΡΑΦΗ ΚΙΝΔΥΝΟΥ</h4><RiskTreeRead tree={tree} includeHidden={false}/>{hidden.length>0&&<div className="risk-tree-review"><strong>{hidden.length} προηγούμενες καταγραφές προς επανέλεγχο</strong><p>Αλλάξατε κλάδο. Οι προηγούμενες απαντήσεις διατηρήθηκαν.</p>{hidden.map(id=><p key={id}>{riskTreeQuestions[id].title}<br/><b>{riskTreeLabel(id,tree.answers[id]||'')}</b>{tree.notes[id]&&<><br/>{tree.notes[id]}</>}</p>)}</div>}</aside></div><p role="status">{draft.saving?'Αποθήκευση στο πρόχειρο…':draft.error||(draft.savedAt?'Το πρόχειρο αποθηκεύτηκε '+draft.savedAt:'')}</p>{draft.error&&<><button type="button" onClick={()=>void draft.flush().catch(()=>{})}>Επανάληψη</button><button type="button" onClick={()=>void onSaved().then(b=>{if(b)setConflict((b as PatientBundle).risks.find(r=>r.session_id===sessionId)||null)})}>Σύγκριση με αποθηκευμένο</button></>}{conflict!==undefined&&<div className="conflict-review"><h4>Αποθηκευμένη εκτίμηση</h4><pre>{JSON.stringify(shape(conflict||undefined),null,2)}</pre><button type="button" disabled={writingPending} onClick={()=>{draft.acceptServer(shape(conflict||undefined),conflict?.version??null);setConflict(undefined)}}>Χρήση αποθηκευμένου</button><button type="button" disabled={writingPending} onClick={()=>{draft.resolve(draft.value,shape(conflict||undefined),conflict?.version??null);setConflict(undefined)}}>Ρητή αντικατάσταση με τις επιλογές μου</button></div>}</div>;
}
export function RiskTreeRead({tree,includeHidden=true}:{tree:RiskTree;includeHidden?:boolean}){const hidden=riskTreeHidden(tree);const keys=[...riskTreePath(tree.answers),'others',...(includeHidden?hidden:[])];const recorded=keys.filter(id=>tree.answers[id]&&tree.answers[id]!=='not_assessed'||tree.notes[id]?.trim());return <>{recorded.length?<ul>{recorded.map(id=><li key={id}>{hidden.includes(id)&&<small>Προηγούμενος κλάδος · προς επανέλεγχο<br/></small>}{riskTreeQuestions[id].title}<br/><b>{riskTreeLabel(id,tree.answers[id]||'Μόνο σημείωση')}</b>{tree.notes[id]&&<p>{tree.notes[id]}</p>}</li>)}</ul>:<p>Οι απαντήσεις θα εμφανίζονται εδώ.</p>}</>}
