'use client';
import {useEffect,useState} from 'react';
import type {DemoRisk,PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {useClinicalDraft} from './useClinicalDraft';
import {riskTreeChoices,riskTreePath,riskTreeHidden,riskTreeQuestions,riskTreeLabel,type RiskTree} from '@/lib/clinical/risk-tree';
function shape(r?:DemoRisk){return {suicidal_ideation:r?.suicidal_ideation||'not_assessed',intent:r?.intent||'not_assessed',plan:r?.plan||'not_assessed',self_harm:r?.self_harm||'not_assessed',attempt_history:r?.attempt_history||'not_assessed',harm_to_others:r?.harm_to_others||'not_assessed',protective_factors:r?.protective_factors||'',clinical_note:r?.clinical_note||'',tree:r?.tree||{version:1 as const,answers:{wish:r?.suicidal_ideation||'not_assessed',intent:r?.intent||'not_assessed',plan:r?.plan||'not_assessed',others:r?.harm_to_others||'not_assessed'},notes:{}}};}
type Props={sessionId:string;existing?:DemoRisk;onSaved:()=>Promise<unknown>;registerFlusher:(key:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(key:string,d:boolean)=>void};
export default function RiskTreeEditor({sessionId,existing,onSaved,registerFlusher,onDirtyChange}:Props){
 const [noteOpen,setNoteOpen]=useState<Record<string,boolean>>({}),[conflict,setConflict]=useState<DemoRisk|null|undefined>();
 const draft=useClinicalDraft({storageKey:sessionId+':risk-tree-v1',initial:shape(existing),version:existing?.version??null,write:async(risk,version)=>{const d=await demoPost({action:'save_risk',session_id:sessionId,risk,expected_version:version});return {value:shape(d.risk),version:d.risk.version as number}},onSaved,onDirty:d=>onDirtyChange('risk',d)});
 useEffect(()=>registerFlusher('risk',draft.flush),[registerFlusher,draft.flush]);
 const tree=draft.value.tree;const path=riskTreePath(tree.answers),hidden=riskTreeHidden(tree);
 function answer(id:string,value:string){const fields:Record<string,string>={wish:'suicidal_ideation',intent:'intent',plan:'plan',others:'harm_to_others'};draft.change({...draft.value,...(fields[id]?{[fields[id]]:value}:{}),tree:{...tree,answers:{...tree.answers,[id]:value}}});}
 function question(id:string,nested=false){const q=riskTreeQuestions[id];return <section key={id} className={'risk-tree-question '+(nested?'nested':'')} aria-label={q.title}><div className="risk-tree-qhead"><strong>{q.title}</strong><button type="button" className="risk-tree-note-toggle" aria-expanded={Boolean(noteOpen[id])} onClick={()=>setNoteOpen(v=>({...v,[id]:!v[id]}))}>{tree.notes[id]?'Σημείωση ●':'＋ Σημείωση'}</button></div>{q.hint&&<p className="risk-tree-hint">{q.hint}</p>}<div className="risk-tree-choices">{q.choices.map(([v,t])=><button type="button" key={v} aria-label={q.title+' '+t} aria-pressed={tree.answers[id]===v} onClick={()=>answer(id,v)}>{t}</button>)}</div>{noteOpen[id]&&<label className="risk-tree-note">Επεξήγηση<textarea rows={2} aria-label={'Σημείωση: '+q.title} value={tree.notes[id]||''} onChange={e=>draft.change({...draft.value,tree:{...tree,notes:{...tree.notes,[id]:e.target.value}}})}/></label>}</section>}
 return <div className="risk-tree-editor"><p className="risk-tree-hint">Καταγράψτε ό,τι διερευνήθηκε σήμερα. Οι επόμενες ερωτήσεις εμφανίζονται ανάλογα με τις απαντήσεις.</p><div className="risk-tree-layout"><div>{path.map((id,i)=>question(id,i>0))}<details className="risk-tree-other"><summary>Κίνδυνος προς άλλους{tree.answers.others&&tree.answers.others!=='not_assessed'?' · '+riskTreeLabel('others',tree.answers.others):''}</summary>{question('others')}</details><details className="risk-tree-other" open={Boolean(draft.value.self_harm!=='not_assessed'||draft.value.attempt_history!=='not_assessed')}><summary>Αυτοτραυματισμός & ιστορικό απόπειρας</summary>{(['self_harm','attempt_history'] as const).map(k=><div className="risk-tree-question" key={k}><strong>{k==='self_harm'?'Αυτοτραυματισμός':'Ιστορικό απόπειρας'}</strong><div className="risk-tree-choices">{riskTreeChoices.map(([v,t])=><button type="button" key={v} aria-label={k+' '+t} aria-pressed={draft.value[k]===v} onClick={()=>draft.change({...draft.value,[k]:v})}>{t}</button>)}</div></div>)}</details>{(['protective_factors','clinical_note'] as const).map(k=><label className="risk-tree-clinical" key={k}>{k==='protective_factors'?'Προστατευτικοί παράγοντες':'Κλινική αποτίμηση & ενέργειες'}<textarea rows={2} value={draft.value[k]} onChange={e=>draft.change({...draft.value,[k]:e.target.value})}/></label>)}</div><aside className="risk-tree-summary"><h4>ΚΑΤΑΓΡΑΦΗ ΚΙΝΔΥΝΟΥ</h4><RiskTreeRead tree={tree} includeHidden={false}/>{hidden.length>0&&<div className="risk-tree-review"><strong>{hidden.length} προηγούμενες καταγραφές προς επανέλεγχο</strong><p>Αλλάξατε κλάδο. Οι προηγούμενες απαντήσεις διατηρήθηκαν.</p>{hidden.map(id=><p key={id}>{riskTreeQuestions[id].title}<br/><b>{riskTreeLabel(id,tree.answers[id]||'')}</b>{tree.notes[id]&&<><br/>{tree.notes[id]}</>}</p>)}</div>}</aside></div><p role="status">{draft.saving?'Αποθήκευση στο πρόχειρο…':draft.error||(draft.savedAt?'Το πρόχειρο αποθηκεύτηκε '+draft.savedAt:'')}</p>{draft.error&&<><button type="button" onClick={()=>void draft.flush().catch(()=>{})}>Επανάληψη</button><button type="button" onClick={()=>void onSaved().then(b=>{if(b)setConflict((b as PatientBundle).risks.find(r=>r.session_id===sessionId)||null)})}>Σύγκριση με αποθηκευμένο</button></>}{conflict!==undefined&&<div className="conflict-review"><h4>Αποθηκευμένη εκτίμηση</h4><pre>{JSON.stringify(shape(conflict||undefined),null,2)}</pre><button type="button" onClick={()=>{draft.acceptServer(shape(conflict||undefined),conflict?.version??null);setConflict(undefined)}}>Χρήση αποθηκευμένου</button><button type="button" onClick={()=>{draft.resolve(draft.value,shape(conflict||undefined),conflict?.version??null);setConflict(undefined)}}>Ρητή αντικατάσταση με τις επιλογές μου</button></div>}</div>;
}
export function RiskTreeRead({tree,includeHidden=true}:{tree:RiskTree;includeHidden?:boolean}){const hidden=riskTreeHidden(tree);const keys=[...riskTreePath(tree.answers),'others',...(includeHidden?hidden:[])];const recorded=keys.filter(id=>tree.answers[id]&&tree.answers[id]!=='not_assessed'||tree.notes[id]?.trim());return <>{recorded.length?<ul>{recorded.map(id=><li key={id}>{hidden.includes(id)&&<small>Προηγούμενος κλάδος · προς επανέλεγχο<br/></small>}{riskTreeQuestions[id].title}<br/><b>{riskTreeLabel(id,tree.answers[id]||'Μόνο σημείωση')}</b>{tree.notes[id]&&<p>{tree.notes[id]}</p>}</li>)}</ul>:<p>Οι απαντήσεις θα εμφανίζονται εδώ.</p>}</>}
