'use client';
import {useEffect,useState} from 'react';
import {initialDocument,mseItems,type VisitDocument,type DocumentField} from '@/lib/clinical/visit-document';
import type {DemoSection,PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {useClinicalDraft} from './useClinicalDraft';
import ICD10Picker from './ICD10Picker';
import MseDomain from './MseDomain';
const assessmentLabels:Record<string,string>={diagnosis:'Διάγνωση',formulation:'Διατύπωση περίπτωσης',impression:'Κλινική αποτίμηση'};
export default function StructuredVisitEditor({sessionId,kind,existing,followup,baseline,onSaved,registerFlusher,onDirtyChange}:{sessionId:string;kind:'mse'|'assessment';existing?:DemoSection;followup:boolean;baseline?:DemoSection|null;onSaved:()=>Promise<unknown>;registerFlusher:(key:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(key:string,dirty:boolean)=>void}){
 const key='section:'+kind;const [conflict,setConflict]=useState<DemoSection|null|undefined>();
 const baselineDocument=kind==='mse'&&baseline?initialDocument('mse',baseline.content,baseline.document):null;
 const initialValue=initialDocument(kind,existing?.content,existing?.document);if(kind==='mse'&&followup&&baselineDocument&&!existing)initialValue.fields=initialValue.fields.map(field=>({...field,text:baselineDocument.fields.find(item=>item.key===field.key)?.text||field.text}));
 const draft=useClinicalDraft<VisitDocument>({storageKey:sessionId+':structured:'+kind,initial:initialValue,version:existing?.version??null,write:async(document,version)=>{const d=await demoPost({action:'save_document',session_id:sessionId,section_key:kind,document,expected_version:version});return {value:d.section.document,version:d.section.version}},onSaved,onDirty:dirty=>onDirtyChange(key,dirty)});
 useEffect(()=>registerFlusher(key,draft.flush),[key,registerFlusher,draft.flush]);
 function change(index:number,field:Partial<DocumentField>){draft.change({...draft.value,fields:draft.value.fields.map((f,i)=>i===index?{...f,...field}:f)})}
 const mseChanges=kind==='mse'&&baselineDocument?draft.value.fields.filter(field=>field.key!=='legacy'&&field.text!==(baselineDocument.fields.find(item=>item.key===field.key)?.text||'')).length:0;
 return <div className={'visit-structured '+kind}>
 {kind==='mse'&&followup&&baselineDocument&&<div className="mse-compare-head"><span>Σε σύγκριση με την αμέσως προηγούμενη καταγραφή</span><strong className={mseChanges?'changed':'same'}>{mseChanges?mseChanges+' '+(mseChanges===1?'αλλαγή':'αλλαγές'):'Χωρίς αλλαγές'}</strong></div>}
 {kind==='mse'?<><div className="mse-columns">{[mseItems.slice(0,6),mseItems.slice(6)].map((items,column)=><div className="mse-column" key={column}>{items.map(([key])=>{const index=draft.value.fields.findIndex(field=>field.key===key);if(index<0)return null;const field=draft.value.fields[index];const previous=baselineDocument?.fields.find(item=>item.key===field.key);return <MseDomain key={field.key} field={field} previousField={followup?previous:undefined} onChange={text=>change(index,{text})} onBlur={()=>void draft.flush().catch(()=>{})}/>})}</div>)}</div>{draft.value.fields.map((field,index)=>field.key==='legacy'?<MseDomain key={field.key} field={field} onChange={text=>change(index,{text})} onBlur={()=>void draft.flush().catch(()=>{})}/>:null)}</>:draft.value.fields.map((field,index)=><div className="visit-assessment-field" key={field.key}><label>{assessmentLabels[field.key]||(field.key.startsWith('differential-')?'Διαφορική διάγνωση':field.label)}<textarea rows={2} value={field.text} onChange={e=>change(index,{text:e.target.value})} onBlur={()=>void draft.flush().catch(()=>{})}/></label>{(field.key.startsWith('differential-')||field.key==='diagnosis')&&<label className="diagnosis-certainty">Βεβαιότητα<select value={field.status||''} onChange={e=>change(index,{status:(e.target.value||undefined) as DocumentField['status']})}><option value="">Δεν ορίστηκε</option><option value="under_investigation">Υπό διερεύνηση</option><option value="provisional">Προσωρινή</option><option value="confirmed">Επιβεβαιωμένη</option></select></label>}{(field.key.startsWith('differential-')||field.key==='diagnosis')&&<div className="assessment-coding"><div className="visit-code-values">{field.codes?.map(c=><span key={c.code} title={c.label}><strong>{c.code}</strong><button type="button" aria-label={'Αφαίρεση '+c.code} onClick={()=>change(index,{codes:field.codes?.filter(x=>x.code!==c.code)})}>×</button></span>)}</div><details><summary>＋ ICD-10</summary><ICD10Picker showValues={false} value={field.codes||[]} onChange={codes=>change(index,{codes})}/></details></div>}{field.key.startsWith('differential-')&&<button type="button" className="assessment-remove" aria-label="Αφαίρεση διαφορικής διάγνωσης" onClick={()=>{if(!field.text.trim()&&!field.codes?.length||window.confirm('Αφαίρεση αυτής της διαφορικής διάγνωσης;'))draft.change({...draft.value,fields:draft.value.fields.filter((_,i)=>i!==index)})}}>×</button>}</div>)}
 {kind==='assessment'&&<button type="button" className="visit-text-button" onClick={()=>draft.change({...draft.value,fields:[...draft.value.fields,{key:'differential-'+crypto.randomUUID(),label:'Differential Diagnosis',text:'',status:'under_investigation',codes:[]}]})}>+ Διαφορική διάγνωση</button>}
 <p role="status" className={draft.error?'save-state error':'visit-save'}>{draft.saving?'Αποθήκευση…':draft.error|| (draft.savedAt?'Αποθηκεύτηκε '+draft.savedAt:existing?'Αποθηκευμένο':'')}</p>
 {draft.error&&<><button onClick={()=>void draft.flush().catch(()=>{})}>Επανάληψη</button><button onClick={()=>void onSaved().then(b=>{if(b)setConflict((b as PatientBundle).sections.find(s=>s.session_id===sessionId&&s.section_key===kind)||null)})}>Σύγκριση εκδόσεων</button></>}
 {conflict!==undefined&&<div className="conflict-review"><h4>Αποθηκευμένη έκδοση</h4><pre>{conflict?.content||'Κενή'}</pre><button onClick={()=>{draft.acceptServer(initialDocument(kind,conflict?.content,conflict?.document),conflict?.version??null);setConflict(undefined)}}>Χρήση αποθηκευμένου</button><button onClick={()=>{draft.resolve(draft.value,initialDocument(kind,conflict?.content,conflict?.document),conflict?.version??null);setConflict(undefined)}}>Ρητή αντικατάσταση με τη δική μου</button></div>}
 </div>;
}
