'use client';
import {useEffect,useState} from 'react';
import {getDemoTesterId} from '@/lib/demo-tester';
import {formatClinicAppointment} from '@/lib/clinic-time';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
function toIso(date:string,time:string){const guess=new Date(date+'T'+time+':00Z');const offset=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Athens',timeZoneName:'shortOffset'}).formatToParts(guess).find(x=>x.type==='timeZoneName')?.value.match(/GMT([+-])(\d+)(?::(\d+))?/);if(!offset)throw new Error('Μη έγκυρη ώρα');return new Date(guess.getTime()-(offset[1]==='-'?-1:1)*(Number(offset[2])*60+Number(offset[3]||0))*60000).toISOString()}
export default function VisitNextAppointment({bundle,reload,registerFlusher,onDirtyChange}:{bundle:PatientBundle;reload:()=>Promise<unknown>;registerFlusher:(k:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(k:string,d:boolean)=>void}){
 const [date,setDate]=useState(''),[time,setTime]=useState('09:00'),[duration,setDuration]=useState('50'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{onDirtyChange('appointment',Boolean(date));return()=>onDirtyChange('appointment',false)},[date,onDirtyChange]);
 useEffect(()=>registerFlusher('appointment',async()=>{if(date||busy)throw new Error('Αποθηκεύστε ή ακυρώστε το επόμενο ραντεβού πριν ολοκληρώσετε.')}),[registerFlusher,date,busy]);
 async function save(){setBusy(true);setError('');try{const start=toIso(date,time);const r=await fetch('/api/calendar/command/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tester:getDemoTesterId(),action:'create',patient_id:bundle.patient.id,start_iso:start,end_iso:new Date(Date.parse(start)+Number(duration)*60000).toISOString(),appointment_type:'follow_up'})});const d=await r.json();if(!r.ok)throw new Error(d.error);setDate('');await reload()}catch(e){setError(e instanceof Error?e.message:'Δεν αποθηκεύτηκε το ραντεβού')}finally{setBusy(false)}}
 return <div className="visit-next"><div className="visit-next-heading"><strong>Επόμενη συνεδρία</strong></div>{bundle.appointments.filter(a=>a.status==='scheduled'&&!a.session_id&&Date.parse(a.scheduled_start)>Date.now()).map(a=><p key={a.id}><strong>{formatClinicAppointment(a.scheduled_start)}</strong> · Προγραμματισμένο</p>)}<div className="visit-inline-fields"><label>Ημερομηνία<input type="date" value={date} onChange={e=>setDate(e.target.value)} disabled={busy}/></label><label>Ώρα Αθήνας<input type="time" value={time} onChange={e=>setTime(e.target.value)} disabled={busy}/></label><label>Διάρκεια<select value={duration} onChange={e=>setDuration(e.target.value)} disabled={busy}><option value="30">30′</option><option value="50">50′</option><option value="60">60′</option></select></label><button disabled={!date||busy} onClick={()=>void save()}>{busy?'Αποθήκευση…':'Προγραμματισμός'}</button>{date&&<button disabled={busy} onClick={()=>setDate('')}>Ακύρωση</button>}</div>{error&&<p role="alert">{error}</p>}</div>;
}
