'use client';
import {useEffect,useState} from 'react';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {useClinicalDraft} from './useClinicalDraft';
const fields=[['psychiatric_history','Ψυχιατρικό ιστορικό'],['medical_history','Σωματικό ιστορικό'],['previous_treatments','Προηγούμενες θεραπείες'],['hospitalizations','Νοσηλείες'],['family_history','Οικογενειακό ιστορικό'],['substance_history','Ουσίες'],['social_functioning','Κοινωνική λειτουργικότητα'],['allergies','Αλλεργίες']] as const;
export default function VisitHistory({bundle,sessionId,reload,registerFlusher,onDirtyChange}:{bundle:PatientBundle;sessionId:string;reload:()=>Promise<unknown>;registerFlusher:(k:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(k:string,d:boolean)=>void}){
 const shape=(b:PatientBundle)=>Object.fromEntries(fields.map(([k])=>[k,b.history?.[k]||'']));const [conflict,setConflict]=useState<PatientBundle|null>(null);
 const draft=useClinicalDraft({storageKey:sessionId+':history',initial:shape(bundle),version:bundle.history?.version??0,write:async(history,version)=>{const d=await demoPost({action:'save_history',patient_id:bundle.patient.id,history,expected_version:version});return {value:Object.fromEntries(fields.map(([k])=>[k,d.history[k]||''])),version:d.history.version}},onSaved:reload,onDirty:d=>onDirtyChange('history',d)});
 useEffect(()=>registerFlusher('history',draft.flush),[registerFlusher,draft.flush]);
 return <div className="visit-history">{fields.map(([key,label])=><details key={key} open={key==='allergies'||undefined}><summary>{label}<small>{draft.value[key]?draft.value[key].slice(0,70):'Δεν καταγράφηκε'}</small></summary><label>{label}<textarea rows={2} value={draft.value[key]} onChange={e=>draft.change({...draft.value,[key]:e.target.value})} onBlur={()=>void draft.flush().catch(()=>{})}/></label></details>)}<p role="status">{draft.saving?'Αποθήκευση ιστορικού…':draft.error|| (draft.savedAt?'Αποθηκεύτηκε '+draft.savedAt:'')}</p>{draft.error&&<><button onClick={()=>void draft.flush().catch(()=>{})}>Επανάληψη</button><button onClick={()=>void reload().then(b=>setConflict(b as PatientBundle))}>Σύγκριση ιστορικού</button></>}{conflict&&<div className="conflict-review"><pre>{JSON.stringify(shape(conflict),null,2)}</pre><button onClick={()=>{draft.acceptServer(shape(conflict),conflict.history?.version??0);setConflict(null)}}>Χρήση αποθηκευμένου</button><button onClick={()=>{draft.resolve(draft.value,shape(conflict),conflict.history?.version??0);setConflict(null)}}>Ρητή αντικατάσταση</button></div>}</div>;
}
