'use client';
import {useEffect,useState} from 'react';
import type {PatientBundle} from '@/lib/patients/demo-runtime';
import {demoPost} from '@/lib/patients/demo-client';
import {useClinicalDraft} from './useClinicalDraft';
const fields=[['psychiatric_history','Ψυχιατρικό ιστορικό'],['medical_history','Σωματικό ιστορικό'],['previous_treatments','Προηγούμενες θεραπείες'],['hospitalizations','Νοσηλείες'],['family_history','Οικογενειακό ιστορικό'],['substance_history','Ουσίες'],['social_functioning','Κοινωνική λειτουργικότητα'],['allergies','Αλλεργίες']] as const;
const questions:Record<(typeof fields)[number][0],string>={psychiatric_history:'Έχετε επισκεφθεί στο παρελθόν ψυχίατρο ή ψυχολόγο; Έχετε λάβει κάποια ψυχιατρική διάγνωση;',medical_history:'Υπάρχουν σημαντικά προβλήματα σωματικής υγείας, χρόνιες παθήσεις ή επεμβάσεις;',previous_treatments:'Έχετε λάβει στο παρελθόν ψυχιατρική αγωγή ή ψυχοθεραπεία; Τι βοήθησε και τι όχι;',hospitalizations:'Έχει υπάρξει νοσηλεία για λόγους ψυχικής υγείας; Πότε και για ποιο λόγο;',family_history:'Υπάρχει στην οικογένεια ιστορικό ψυχικής νόσου, εξάρτησης ή αυτοκτονικής συμπεριφοράς;',substance_history:'Χρησιμοποιείτε αλκοόλ, κάνναβη, άλλες ουσίες ή καπνό; Πόσο συχνά;',social_functioning:'Πώς είναι αυτή την περίοδο η εργασία ή οι σπουδές, οι σχέσεις, η οικογένεια και η καθημερινή λειτουργικότητά σας;',allergies:'Έχετε γνωστές αλλεργίες ή σοβαρές αντιδράσεις σε φάρμακα;'};
export default function VisitHistory({bundle,sessionId,reload,registerFlusher,onDirtyChange}:{bundle:PatientBundle;sessionId:string;reload:()=>Promise<unknown>;registerFlusher:(k:string,f:()=>Promise<void>)=>(()=>void);onDirtyChange:(k:string,d:boolean)=>void}){
 const initialAssessment=bundle.sessions.some(session=>session.id===sessionId&&session.session_type==='initial_assessment');
 const shape=(b:PatientBundle)=>Object.fromEntries(fields.map(([k])=>[k,b.history?.[k]||'']));const [conflict,setConflict]=useState<PatientBundle|null>(null);
 const draft=useClinicalDraft({storageKey:sessionId+':history',initial:shape(bundle),version:bundle.history?.version??0,write:async(history,version)=>{const d=await demoPost({action:'save_history',patient_id:bundle.patient.id,history,expected_version:version});return {value:Object.fromEntries(fields.map(([k])=>[k,d.history[k]||''])),version:d.history.version}},onSaved:reload,onDirty:d=>onDirtyChange('history',d)});
 useEffect(()=>registerFlusher('history',draft.flush),[registerFlusher,draft.flush]);
 return <div className="visit-history-shell"><div className="visit-history-intro"><strong>{initialAssessment?'Κλινική καταγραφή ιστορικού':'Ιστορικό ασθενούς'}</strong><span>{initialAssessment?'Σημειώσεις κλινικού · αποθηκεύονται στον φάκελο. Οι απαντήσεις του ασθενούς βρίσκονται στην καρτέλα «Ιστορικό».':'Αφορά ολόκληρο τον φάκελο. Οι αλλαγές αποθηκεύονται καθώς γράφεις, ανεξάρτητα από την ολοκλήρωση της επίσκεψης.'}</span></div><div className="visit-history-scroll">{fields.map(([key,label])=><label className="history-question" key={key}><strong>{label}</strong><span className="history-prompt">{questions[key]}</span><textarea rows={2} value={draft.value[key]} onChange={e=>draft.change({...draft.value,[key]:e.target.value})} onBlur={()=>void draft.flush().catch(()=>{})} placeholder={initialAssessment?'Δεν έχει καταγραφεί · σημειώσεις από τη συνέντευξη…':'Καταγραφή από τη συνέντευξη…'}/></label>)}</div><p role="status">{draft.saving?'Αποθήκευση ιστορικού…':draft.error|| (draft.savedAt?'Αποθηκεύτηκε '+draft.savedAt:'')}</p>{draft.error&&<><button onClick={()=>void draft.flush().catch(()=>{})}>Επανάληψη</button><button onClick={()=>void reload().then(b=>setConflict(b as PatientBundle))}>Σύγκριση ιστορικού</button></>}{conflict&&<div className="conflict-review"><pre>{JSON.stringify(shape(conflict),null,2)}</pre><button onClick={()=>{draft.acceptServer(shape(conflict),conflict.history?.version??0);setConflict(null)}}>Χρήση αποθηκευμένου</button><button onClick={()=>{draft.resolve(draft.value,shape(conflict),conflict.history?.version??0);setConflict(null)}}>Ρητή αντικατάσταση</button></div>}</div>;
}
