'use client';
import Link from 'next/link';import {useCallback,useEffect,useRef,useState} from 'react';import PatientIntakeForm,{type IntakePayload} from '@/components/intake/PatientIntakeForm';
export default function TabletPage(){const [deviceToken,setDeviceToken]=useState(''),[payload,setPayload]=useState<IntakePayload|null>(null),[error,setError]=useState(''),[pairing,setPairing]=useState(false),busy=useRef(false);
 useEffect(()=>{try{setDeviceToken(localStorage.getItem('noima-tablet-token')||'')}catch{}},[]);
 const publicCall=useCallback(async(body:Record<string,unknown>)=>{const r=await fetch('/api/intake/public',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d},[]);
 useEffect(()=>{if(!deviceToken)return;let active=true;const poll=async()=>{if(busy.current)return;busy.current=true;try{const d=await publicCall({action:'device_poll',deviceToken});if(!active)return;if(d.status==='waiting')setPayload(null);else setPayload(d);setError('')}catch(e){if(active)setError(e instanceof Error?e.message:'Το tablet δεν συνδέθηκε.')}finally{busy.current=false}};void poll();const timer=setInterval(()=>void poll(),3500);return()=>{active=false;clearInterval(timer)}},[deviceToken,publicCall]);
 async function pair(){setPairing(true);setError('');try{const r=await fetch('/api/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'register_device',label:'Tablet Υποδοχής'})});const d=await r.json();if(!r.ok)throw new Error(d.error);localStorage.setItem('noima-tablet-token',d.deviceToken);setDeviceToken(d.deviceToken)}catch(e){setError(e instanceof Error?e.message:'Δεν έγινε σύνδεση.')}finally{setPairing(false)}}
 if(!deviceToken)return <main className="tablet-wait"><div className="brand-mark">Ψ</div><h1>Tablet Υποδοχής</h1><p>Συνδέστε αυτό το tablet μία φορά με τον χώρο του ιατρείου.</p><button disabled={pairing} onClick={()=>void pair()}>{pairing?'Σύνδεση…':'Σύνδεση αυτού του tablet'}</button>{error&&<p role="alert">{error}</p>}<small>Αν ζητηθεί σύνδεση, <Link href="/login">συνδεθείτε στο Noima</Link> και επιστρέψτε εδώ.</small></main>;
 if(payload)return <PatientIntakeForm payload={payload} onSubmit={async(identity,history,psychometrics)=>{const d=await publicCall({action:'device_submit',deviceToken,intakeId:payload.id,identity,history,psychometrics});setPayload(null);return d}}/>;
 return <main className="tablet-wait"><div className="brand-mark">Ψ</div><span className="kicker">ΣΥΝΔΕΔΕΜΕΝΟ</span><h1>Tablet Υποδοχής</h1><p>{error||'Περιμένει νέο ερωτηματολόγιο από τον γιατρό…'}</p><div className="tablet-pulse"/><button className="tablet-unpair" onClick={()=>{localStorage.removeItem('noima-tablet-token');setDeviceToken('')}}>Αποσύνδεση tablet</button></main>}
