export type Provider='google'|'microsoft';
export type Tokens={access_token:string;refresh_token:string;expires_at:number};
export function config(provider:Provider){const prefix=provider==='google'?'GOOGLE_MAIL':'MICROSOFT_MAIL';return {id:process.env[prefix+'_CLIENT_ID']||'',secret:process.env[prefix+'_CLIENT_SECRET']||'',token:provider==='google'?'https://oauth2.googleapis.com/token':'https://login.microsoftonline.com/common/oauth2/v2.0/token',scope:provider==='google'?'openid email profile https://www.googleapis.com/auth/gmail.send':'openid email profile offline_access User.Read Mail.Send'}}
export function ready(provider:Provider){const c=config(provider);return Boolean(c.id&&c.secret&&process.env.MAILBOX_ENCRYPTION_KEY&&process.env.NOIMA_APP_ORIGIN)}
export function callback(){return new URL('/api/mailbox/callback',process.env.NOIMA_APP_ORIGIN).href}
export function authorization(provider:Provider,state:string,challenge:string){const c=config(provider);const url=new URL(provider==='google'?'https://accounts.google.com/o/oauth2/v2/auth':'https://login.microsoftonline.com/common/oauth2/v2.0/authorize');url.search=new URLSearchParams({client_id:c.id,redirect_uri:callback(),response_type:'code',scope:c.scope,state,code_challenge:challenge,code_challenge_method:'S256',...(provider==='google'?{access_type:'offline',prompt:'consent'}:{prompt:'select_account'})}).toString();return url.href}
export async function tokens(provider:Provider,params:Record<string,string>){const c=config(provider);const r=await fetch(c.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.id,client_secret:c.secret,...params}),signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw new Error('mail_reconnect');const d=await r.json();if(!d.access_token)throw new Error('mail_reconnect');return {access_token:d.access_token as string,refresh_token:d.refresh_token as string|undefined,expires_at:Date.now()+Number(d.expires_in||3600)*1000}}
export async function mailboxEmail(provider:Provider,access:string){const r=await fetch(provider==='google'?'https://openidconnect.googleapis.com/v1/userinfo':'https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName',{headers:{Authorization:'Bearer '+access},signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw new Error('mail_reconnect');const d=await r.json();const email=provider==='google'?(d.email_verified?d.email:null):(d.mail||d.userPrincipalName);if(!validEmail(email))throw new Error('mail_reconnect');return email as string}
export function validEmail(value:unknown):value is string{return typeof value==='string'&&value.length<=254&&/^[^\s<>\r\n@]+@[^\s<>\r\n@]+\.[^\s<>\r\n@]+$/.test(value)}
export function mime(from:string,to:string,subject:string,body:string){if(!validEmail(from)||!validEmail(to)||/[\r\n]/.test(subject))throw new Error('invalid_message');return Buffer.from(['From: '+from,'To: '+to,'Subject: =?UTF-8?B?'+Buffer.from(subject).toString('base64')+'?=','MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',Buffer.from(body).toString('base64').match(/.{1,76}/g)?.join('\r\n')||''].join('\r\n')).toString('base64url')}
export async function send(provider:Provider,access:string,from:string,to:string,subject:string,body:string){
 const payload=provider==='google'?{raw:mime(from,to,subject,body)}:{message:{subject,body:{contentType:'Text',content:body},toRecipients:[{emailAddress:{address:to}}]},saveToSentItems:true};
 const r=await fetch(provider==='google'?'https://gmail.googleapis.com/gmail/v1/users/me/messages/send':'https://graph.microsoft.com/v1.0/me/sendMail',{method:'POST',headers:{Authorization:'Bearer '+access,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(20000)});
 if(!r.ok)throw new Error(r.status>=500?'mail_unknown':r.status===401?'mail_reconnect':'mail_rejected');
 return provider==='google'?String((await r.json()).id||''):r.headers.get('request-id')||'';
}
