'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import MailboxSettings from '@/components/mail/MailboxSettings';
import {PasswordChangeForm} from '@/components/PasswordForms';
export default function Account(){
 const [identity,setIdentity]=useState<{full_name:string;can_restore:boolean;can_invite:boolean}|null>(null),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('bug'),[feedback,setFeedback]=useState(''),[confirm,setConfirm]=useState(false);
 useEffect(()=>{void fetch('/api/pilot').then(r=>r.json()).then(d=>{setIdentity(d.identity);setEmail(d.email||'')}).catch(()=>setError('Δεν φορτώθηκε ο λογαριασμός.'))},[]);
 async function action(name:string,extra:Record<string,unknown>={}){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/pilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(name==='feedback'){setMessage('Η αναφορά αποθηκεύτηκε. Ευχαριστούμε.');setFeedback('')}else window.location.assign(name==='logout'?'/login':'/');}catch(e){setError(e instanceof Error?e.message:'Δεν ολοκληρώθηκε.')}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void action('feedback',{category,message:feedback,page:location.pathname})}
 return <main className="pilot-page"><section className="pilot-card pilot-account"><Link href="/">← Επιστροφή στην εφαρμογή</Link><h1>{identity?.full_name||'Ο λογαριασμός μου'}</h1><p>{email}</p><button disabled={busy} onClick={()=>void action('logout')}>Αποσύνδεση</button>{identity&&<><hr/><h2>Αλλαγή κωδικού</h2><PasswordChangeForm/><hr/><MailboxSettings/><hr/><h2>Πώς πήγε η δοκιμή;</h2><p>Περιγράψτε τι προσπαθήσατε να κάνετε και τι συνέβη. Μην συμπεριλάβετε προσωπικά στοιχεία πραγματικών ασθενών.</p><form onSubmit={submit}><fieldset disabled={busy}><label>Τύπος αναφοράς<select value={category} onChange={e=>setCategory(e.target.value)}><option value="bug">Κάτι δεν λειτουργεί</option><option value="experience">Εμπειρία χρήσης</option><option value="idea">Πρόταση</option></select></label><label>Η αναφορά σας<textarea required minLength={5} maxLength={4000} rows={5} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="pilot-primary" type="submit">Αποθήκευση αναφοράς</button></fieldset></form><hr/><h2>Νέα δοκιμή</h2><p>Ξεκινήστε ξανά με έναν άδειο χώρο. Ο τωρινός χώρος αρχειοθετείται και μπορείτε να επιστρέψετε σε αυτόν.</p><label className="pilot-check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Επιβεβαιώνω την αλλαγή δοκιμαστικού χώρου</label><div className="pilot-actions"><button disabled={busy||!confirm} onClick={()=>void action('reset',{confirm:true})}>Εκκίνηση νέας δοκιμής</button>{identity.can_restore&&<button disabled={busy||!confirm} onClick={()=>void action('restore',{confirm:true})}>Επιστροφή στον προηγούμενο χώρο</button>}</div></>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="pilot-error">{error}</p>}</section></main>;
}
