'use client';
import {useState,type FormEvent} from 'react';
import Link from 'next/link';
import MailboxSettings from '@/components/mail/MailboxSettings';
import {PasswordChangeForm} from '@/components/PasswordForms';
import {useAccountSession} from '@/components/AccountSessionBoundary';
import {notifyAccountChange} from '@/lib/pilot/browser-session';
export default function Account(){
 const account=useAccountSession(),identity=account?.identity,email=account?.email,hasPassword=account?.has_password;
 const [message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('bug'),[feedback,setFeedback]=useState(''),[confirm,setConfirm]=useState(false);
 async function action(name:string,extra:Record<string,unknown>={}){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/pilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(name==='feedback'){setMessage('Η αναφορά αποθηκεύτηκε. Ευχαριστούμε.');setFeedback('')}else {notifyAccountChange();window.location.replace(name==='logout'?'/login':'/');}}catch(e){setError(e instanceof Error?e.message:'Δεν ολοκληρώθηκε.')}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void action('feedback',{category,message:feedback,page:location.pathname})}
 return <main className="pilot-page"><section className="pilot-card pilot-account"><Link href="/">← Επιστροφή στην εφαρμογή</Link><h1>{identity?.full_name||'Ο λογαριασμός μου'}</h1><p className="account-email">{email}</p><p>Οι φάκελοι και τα ραντεβού σας ανήκουν σε αυτόν τον λογαριασμό. Επιστρέφετε στον ίδιο χώρο όταν συνδέεστε με το ίδιο email.</p><button disabled={busy} onClick={()=>void action('logout')}>Αποσύνδεση</button>{identity&&<>{hasPassword&&<><hr/><details className="account-details"><summary>Αλλαγή κωδικού</summary><PasswordChangeForm/></details></>}<hr/><MailboxSettings/><hr/><h2>Πώς πήγε η δοκιμή;</h2><p>Περιγράψτε τι προσπαθήσατε να κάνετε και τι συνέβη. Μην συμπεριλάβετε προσωπικά στοιχεία πραγματικών ασθενών.</p><form onSubmit={submit}><fieldset disabled={busy}><label>Τύπος αναφοράς<select value={category} onChange={e=>setCategory(e.target.value)}><option value="bug">Κάτι δεν λειτουργεί</option><option value="experience">Εμπειρία χρήσης</option><option value="idea">Πρόταση</option></select></label><label>Η αναφορά σας<textarea required minLength={5} maxLength={4000} rows={5} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="pilot-primary" type="submit">Αποθήκευση αναφοράς</button></fieldset></form><hr/><details className="account-details"><summary>Διαχείριση δοκιμαστικού χώρου</summary><p>Ξεκινήστε ξανά με έναν άδειο χώρο. Ο τωρινός χώρος αρχειοθετείται και μπορείτε να επιστρέψετε σε αυτόν. Δεν χρειάζεται για να προσθέσετε νέο ασθενή.</p><label className="pilot-check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Επιβεβαιώνω την αλλαγή δοκιμαστικού χώρου</label><div className="pilot-actions"><button disabled={busy||!confirm} onClick={()=>void action('reset',{confirm:true})}>Εκκίνηση νέας δοκιμής</button>{identity.can_restore&&<button disabled={busy||!confirm} onClick={()=>void action('restore',{confirm:true})}>Επιστροφή στον προηγούμενο χώρο</button>}</div></details></>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="pilot-error">{error}</p>}</section></main>;
}
