'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Mail,X,ExternalLink} from 'lucide-react';
import type {MailboxStatus} from './MailboxSettings';
export type AssessmentLink={id:string;token:string;link:string};
export default function AssessmentEmail({email,instrument,prepare,onClose,onSent}:{email:string;instrument:string;prepare:()=>Promise<AssessmentLink>;onClose:()=>void;onSent:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[to,setTo]=useState(email),[subject,setSubject]=useState('Συμπλήρωση ερωτηματολογίου'),[body,setBody]=useState('Καλησπέρα σας,\n\nΠαρακαλώ συμπληρώστε το ερωτηματολόγιο από τον παρακάτω σύνδεσμο:\n[Σύνδεσμος ερωτηματολογίου]\n\nΟ σύνδεσμος ισχύει για 14 ημέρες.\n\nΣας ευχαριστώ.'),[status,setStatus]=useState<MailboxStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal();void fetch('/api/mailbox',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();setStatus(await r.json())}).catch(()=>setError('Δεν φορτώθηκε το email αποστολής. Μπορείτε να ανοίξετε το μήνυμα στο mailbox σας.'))},[]);
 async function deliver(e:FormEvent,external=false){e.preventDefault();setBusy(true);setError('');try{const a=await prepare();const message=body.includes('[Σύνδεσμος ερωτηματολογίου]')?body.replaceAll('[Σύνδεσμος ερωτηματολογίου]',a.link):body+'\n\n'+a.link;
 if(external){window.location.href='mailto:'+encodeURIComponent(to)+'?'+new URLSearchParams({subject,body:message}).toString().replaceAll('+','%20');setBusy(false);return}
 const r=await fetch('/api/mailbox/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment_id:a.id,token:a.token,to,subject,body:message})});const d=await r.json();if(!r.ok)throw new Error(d.error);onSent();onClose();
 }catch(e){setError(e instanceof Error?e.message:'Η αποστολή δεν ολοκληρώθηκε.')}finally{setBusy(false)}}
 return <dialog ref={dialog} className="assessment-email-dialog" aria-label="Αποστολή ερωτηματολογίου" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><header><div><span className="kicker">{instrument} · ΕΡΩΤΗΜΑΤΟΛΟΓΙΟ</span><h2><Mail size={20}/> Αποστολή email</h2></div><button type="button" className="mail-close" aria-label="Κλείσιμο" disabled={busy} onClick={onClose}><X size={20}/></button></header><form onSubmit={e=>void deliver(e,!status?.mailbox)}><fieldset disabled={busy}><label>Από<div className="mail-sender">{status?.mailbox?.email||'Το mailbox σας'}{!status?.mailbox&&<small>Η αποστολή θα γίνει από το email που χρησιμοποιείτε στο mailbox.</small>}</div></label><label>Προς<input autoFocus={!email} type="email" required maxLength={254} autoComplete="email" value={to} onChange={e=>setTo(e.target.value)} placeholder="Email παραλήπτη"/></label><label>Θέμα<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Μήνυμα<textarea required maxLength={9000} rows={7} value={body} onChange={e=>setBody(e.target.value)}/></label><small>Ο σύνδεσμος θα προστεθεί αυτόματα στο μήνυμα.</small>{error&&<p role="alert" className="mail-error">{error}</p>}<footer>{!status?.mailbox&&<a href="/account">Σύνδεση email αποστολής</a>}<button type={status?.mailbox?'button':'submit'} className={status?.mailbox?'mail-secondary':'mail-primary'} onClick={status?.mailbox?e=>{const form=e.currentTarget.form;if(form?.reportValidity())void deliver(e,true)}:undefined}>{!status?.mailbox?<ExternalLink size={16}/>:null}{status?.mailbox?'Άνοιγμα στο mailbox':busy?'Προετοιμασία…':'Άνοιγμα στο mailbox'}</button>{status?.mailbox&&<button type="submit" className="mail-primary">{busy?'Αποστολή…':'Αποστολή'}</button>}</footer></fieldset></form></dialog>
}
