'use client';
import {useEffect,useState} from 'react';
export type MailboxStatus={mailbox:{provider:string;email:string}|null;providers:{google:boolean;microsoft:boolean}};
export default function MailboxSettings(){const [status,setStatus]=useState<MailboxStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[connected,setConnected]=useState<string|null>(null);
 async function load(){const r=await fetch('/api/mailbox',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setStatus(d)}
 useEffect(()=>{setConnected(new URLSearchParams(window.location.search).get('mail'));void load().catch(()=>setError('Δεν φορτώθηκε το email αποστολής.'))},[]);
 async function action(action:string,provider?:string){setBusy(true);setError('');try{const r=await fetch('/api/mailbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,provider})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.url)location.assign(d.url);else await load()}catch(e){setError(e instanceof Error?e.message:'Δεν ολοκληρώθηκε.')}finally{setBusy(false)}}

 return <section className="mailbox-settings"><h2>Email αποστολής</h2><p>Συνδέστε μία φορά το προσωπικό σας email για αποστολή ερωτηματολογίων μέσα από το Noima.</p>{status?.mailbox&&<p className="mailbox-connected">Συνδεδεμένο: <strong>{status.mailbox.email}</strong></p>}<div className="pilot-actions"><button disabled={busy||!status?.providers.google} onClick={()=>void action('connect','google')}>Σύνδεση Google</button><button disabled={busy||!status?.providers.microsoft} onClick={()=>void action('connect','microsoft')}>Σύνδεση Microsoft</button>{status?.mailbox&&<button disabled={busy} onClick={()=>void action('disconnect')}>Αποσύνδεση email</button>}</div>{status&&(!status.providers.google||!status.providers.microsoft)&&<small>Οι μη διαθέσιμοι πάροχοι χρειάζονται ενεργοποίηση από το Noima. Μπορείτε ήδη να ανοίγετε έτοιμο μήνυμα στο mailbox σας.</small>}{connected==='connected'&&<p role="status">Το email αποστολής συνδέθηκε.</p>}{(error||connected==='error')&&<p role="alert">{error||'Η σύνδεση email δεν ολοκληρώθηκε. Δοκιμάστε ξανά.'}</p>}</section>
}
