'use client';
import {useEffect,useState} from 'react';import {X} from 'lucide-react';import {getDemoTesterId} from '@/lib/demo-tester';
type Patient={id:string;first_name:string;last_name:string;amka?:string;phone?:string;email?:string};
export default function IntakeConflictResolver({intakeId,onClose,onDone}:{intakeId:string;onClose:()=>void;onDone:(patientId:string)=>void}){
 const [patients,setPatients]=useState<Patient[]>([]),[selected,setSelected]=useState(''),[type,setType]=useState('possible_match'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let live=true;void Promise.all([
  fetch('/api/patients/demo/runtime?tester='+encodeURIComponent(getDemoTesterId()),{cache:'no-store'}).then(r=>r.json()),
  fetch('/api/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'list',tester:getDemoTesterId()})}).then(r=>r.json())
 ]).then(([p,i])=>{if(!live)return;setPatients(p.patients||[]);const row=(i.intakes||[]).find((x:{id:string})=>x.id===intakeId);setType(row?.conflict?.type||'possible_match')}).catch(()=>{if(live)setError('Δεν φορτώθηκαν οι επιλογές επίλυσης.')});return()=>{live=false}},[intakeId]);
 async function resolve(createNew:boolean){if(!createNew&&!selected){setError('Επιλέξτε τον υπάρχοντα φάκελο.');return}setBusy(true);setError('');try{const r=await fetch('/api/intake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'resolve',tester:getDemoTesterId(),id:intakeId,patient_id:createNew?null:selected,create_new:createNew})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Δεν επιλύθηκε η ταυτότητα.');onDone(d.patient_id)}catch(e){setError(e instanceof Error?e.message:'Δεν επιλύθηκε η ταυτότητα.')}finally{setBusy(false)}}
 return <div className="intake-launcher-backdrop" onClick={()=>!busy&&onClose()}><section className="intake-launcher" onClick={e=>e.stopPropagation()}><button className="intake-launcher-close" onClick={onClose}><X size={18}/></button><span className="kicker">ΕΛΕΓΧΟΣ ΤΑΥΤΟΤΗΤΑΣ</span><h2>{type==='amka'?'Υπάρχει ήδη αυτός ο ΑΜΚΑ':'Πιθανός υπάρχων ασθενής'}</h2><p>{type==='amka'?'Για λόγους ασφάλειας δεν δημιουργείται δεύτερος φάκελος με τον ίδιο ΑΜΚΑ. Επιλέξτε τον σωστό υπάρχοντα φάκελο.':'Βρέθηκε ίδιο τηλέφωνο ή email. Επιλέξτε υπάρχοντα φάκελο ή επιβεβαιώστε ότι πρόκειται για νέο άτομο.'}</p><label>Υπάρχων φάκελος<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Επιλέξτε…</option>{patients.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}{p.amka?' · ΑΜΚΑ '+p.amka:''}</option>)}</select></label>{error&&<p className="intake-error">{error}</p>}<footer>{type!=='amka'&&<button disabled={busy} onClick={()=>void resolve(true)}>Είναι νέο άτομο</button>}<button className="intake-primary" disabled={busy||!selected} onClick={()=>void resolve(false)}>{busy?'Σύνδεση…':'Σύνδεση με φάκελο'}</button></footer></section></div>
}
