'use client';
import {useEffect,useState} from 'react';
import {answerLabels,instruments} from '@/lib/psychometrics/instruments';
import {diagnosisOptions,emptyHistory,emptyIdentity,familyConditions,familyRelations,medicalOptions,reasonOptions,substanceOptions,type HistoryAnswers,type IntakeIdentity} from '@/lib/intake/history';

export type IntakePayload={id:string;status:string;tools:string[];channel:string;expires_at:string;needs_identity:boolean;prefill:Record<string,unknown>;device_label?:string};
const yn:[string,string][]=[['yes','Ναι'],['no','Όχι']];
const ynUnknown:[string,string][]=[['yes','Ναι'],['no','Όχι'],['unknown','Δεν θυμάμαι']];
const ynPrefer:[string,string][]=[['yes','Ναι'],['no','Όχι'],['prefer','Προτιμώ να το συζητήσω με τον γιατρό']];
const ynPreferOnly:[string,string][]=[['yes','Ναι'],['no','Όχι'],['prefer','Προτιμώ να το συζητήσω μόνο με τον γιατρό']];
function Choice({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:readonly (readonly [string,string])[]}){return <div className="intake-choices">{options.map(([v,l])=><button type="button" key={v} className={value===v?'selected':''} onClick={()=>onChange(v)}>{l}</button>)}</div>}
function Multi({values,onChange,options}:{values:string[];onChange:(v:string[])=>void;options:string[]}){return <div className="intake-multi">{options.map(o=><label key={o}><input type="checkbox" checked={values.includes(o)} onChange={e=>onChange(e.target.checked?[...values,o]:values.filter(x=>x!==o))}/><span>{o}</span></label>)}</div>}
export default function PatientIntakeForm({payload,onSubmit,printMode=false}:{payload:IntakePayload;onSubmit:(identity:IntakeIdentity|null,history:HistoryAnswers|null,psychometrics:Record<string,number[]>)=>Promise<{status?:string}>;printMode?:boolean}){
 const tools=payload.tools;const hasHistory=tools.includes('history');const [identity,setIdentity]=useState<IntakeIdentity>(emptyIdentity),[history,setHistory]=useState<HistoryAnswers>(emptyHistory),[psych,setPsych]=useState<Record<string,Record<number,number>>>({}),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[conflict,setConflict]=useState(false);
 useEffect(()=>{const p=payload.prefill||{};const display=String(p.display_name||'').trim().split(/\s+/);setIdentity(v=>({...v,first_name:String(p.first_name||display[0]||''),last_name:String(p.last_name||display.slice(1).join(' ')||''),age:p.age==null?'':String(p.age),phone:String(p.phone||''),email:String(p.email||''),amka:String(p.amka||''),address:String(p.address||''),contact_phone:String(p.contact_phone||'')}));try{const saved=sessionStorage.getItem('noima-intake:'+payload.id);if(saved){const d=JSON.parse(saved);if(d.identity)setIdentity(d.identity);if(d.history)setHistory(d.history);if(d.psych)setPsych(d.psych);if(Number.isInteger(d.step))setStep(d.step)}}catch{}},[payload.id]);
 useEffect(()=>{if(printMode)return;try{sessionStorage.setItem('noima-intake:'+payload.id,JSON.stringify({identity,history,psych,step}))}catch{}},[payload.id,identity,history,psych,step,printMode]);
 const steps:string[]=[];if(payload.needs_identity)steps.push('Στοιχεία');if(hasHistory)steps.push('Λόγος επίσκεψης','Προηγούμενο ιστορικό','Αγωγή & νοσηλείες','Σωματική υγεία & ουσίες','Οικογένεια & καθημερινότητα');if(tools.includes('PHQ-9'))steps.push('PHQ-9');if(tools.includes('GAD-7'))steps.push('GAD-7');
 const current=steps[Math.min(step,steps.length-1)]||'Ολοκλήρωση';
 function setH<K extends keyof HistoryAnswers>(key:K,value:HistoryAnswers[K]){setHistory(h=>({...h,[key]:value}))}
 function valid(){if(current==='Στοιχεία'&&!identity.first_name.trim())return 'Συμπληρώστε το όνομα.';if(current==='PHQ-9'&&Object.keys(psych['PHQ-9']||{}).length!==9)return 'Απαντήστε σε όλες τις ερωτήσεις.';if(current==='GAD-7'&&Object.keys(psych['GAD-7']||{}).length!==7)return 'Απαντήστε σε όλες τις ερωτήσεις.';return ''}
 async function next(){const problem=valid();if(problem){setError(problem);return}setError('');if(step<steps.length-1){setStep(x=>x+1);window.scrollTo({top:0,behavior:'smooth'});return}setBusy(true);try{const p:Record<string,number[]>={};for(const code of ['PHQ-9','GAD-7'])if(tools.includes(code))p[code]=instruments[code as keyof typeof instruments].items.map((_,i)=>psych[code]?.[i]);const r=await onSubmit(payload.needs_identity?identity:null,hasHistory?history:null,p);if(r.status==='conflict')setConflict(true);else setDone(true);try{sessionStorage.removeItem('noima-intake:'+payload.id)}catch{}}catch(e){setError(e instanceof Error?e.message:'Η υποβολή δεν ολοκληρώθηκε.')}finally{setBusy(false)}}
 if(done||conflict)return <div className="intake-finished"><div className="brand-mark">Ψ</div><h1>{conflict?'Η συμπλήρωση παραλήφθηκε':'Η συμπλήρωση ολοκληρώθηκε.'}</h1><p>{conflict?'Το ιατρείο θα ελέγξει τα στοιχεία σας πριν δημιουργηθεί ή συνδεθεί ο φάκελος.':'Ευχαριστούμε. Παρακαλούμε επιστρέψτε το tablet στον γιατρό ή στη γραμματεία.'}</p></div>;
 if(printMode)return <Printable payload={payload}/>;
 return <div className="intake-shell"><header><div className="brand-mark">Ψ</div><div><strong>Noima</strong><span>Ασφαλής συμπλήρωση πριν την επίσκεψη</span></div></header><div className="intake-progress"><div style={{width:((step+1)/Math.max(1,steps.length))*100+'%'}}/><span>{step+1} / {steps.length}</span></div><main className="intake-card"><span className="kicker">{current}</span>
 {current==='Στοιχεία'&&<><h1>Τα στοιχεία σας</h1><p>Τα στοιχεία αυτά θα χρησιμοποιηθούν για τη δημιουργία του φακέλου σας.</p><div className="intake-fields"><label>Όνομα *<input value={identity.first_name} onChange={e=>setIdentity(v=>({...v,first_name:e.target.value}))}/></label><label>Επώνυμο<input value={identity.last_name} onChange={e=>setIdentity(v=>({...v,last_name:e.target.value}))}/></label><label>Ηλικία<input inputMode="numeric" value={identity.age} onChange={e=>setIdentity(v=>({...v,age:e.target.value.replace(/\D/g,'').slice(0,3)}))}/></label><label>Κινητό<input value={identity.phone} onChange={e=>setIdentity(v=>({...v,phone:e.target.value}))}/></label><label>Email<input type="email" value={identity.email} onChange={e=>setIdentity(v=>({...v,email:e.target.value}))}/></label><label>ΑΜΚΑ<input inputMode="numeric" value={identity.amka} onChange={e=>setIdentity(v=>({...v,amka:e.target.value.replace(/\D/g,'').slice(0,11)}))}/></label><label className="span-two">Διεύθυνση<input value={identity.address} onChange={e=>setIdentity(v=>({...v,address:e.target.value}))}/></label></div></>}
 {current==='Λόγος επίσκεψης'&&<><h1>Τι σας φέρνει σήμερα;</h1><p>Μπορείτε να επιλέξετε περισσότερα από ένα.</p><Multi values={history.reasons} onChange={v=>setH('reasons',v)} options={reasonOptions}/><h3>Πόσο καιρό περίπου σας απασχολεί;</h3><Choice value={history.duration} onChange={v=>setH('duration',v)} options={[['lt1m','Λιγότερο από 1 μήνα'],['1-6m','1–6 μήνες'],['6-12m','6–12 μήνες'],['gt1y','Πάνω από 1 χρόνο']]}/><label className="intake-optional">Αν θέλετε, με λίγα λόγια τι σας φέρνει σήμερα <span>προαιρετικό</span><textarea rows={2} value={history.reason_note} onChange={e=>setH('reason_note',e.target.value.slice(0,600))}/></label></>}
 {current==='Προηγούμενο ιστορικό'&&<><h1>Προηγούμενη φροντίδα</h1><Question title="Έχετε επισκεφθεί στο παρελθόν ψυχίατρο;"><Choice value={history.psychiatrist} onChange={v=>setH('psychiatrist',v)} options={yn}/>{history.psychiatrist==='yes'&&<Choice value={history.psychiatrist_recent} onChange={v=>setH('psychiatrist_recent',v)} options={[['lt1y','Μέσα στον τελευταίο χρόνο'],['1-5y','1–5 χρόνια πριν'],['gt5y','Πάνω από 5 χρόνια'],['unknown','Δεν θυμάμαι']]}/>}</Question><Question title="Έχετε κάνει ψυχοθεραπεία ή παρακολούθηση από ψυχολόγο;"><Choice value={history.psychotherapy} onChange={v=>setH('psychotherapy',v)} options={yn}/>{history.psychotherapy==='yes'&&<Choice value={history.therapy_help} onChange={v=>setH('therapy_help',v)} options={[['very','Πολύ'],['enough','Αρκετά'],['little','Λίγο'],['none','Καθόλου'],['unknown','Δεν γνωρίζω']]}/>}</Question><Question title="Σας έχει δοθεί ποτέ ψυχιατρική διάγνωση;"><Choice value={history.diagnosis_status} onChange={v=>setH('diagnosis_status',v)} options={[['yes','Ναι'],['no','Όχι'],['unknown','Δεν γνωρίζω']]}/>{history.diagnosis_status==='yes'&&<Multi values={history.diagnoses} onChange={v=>setH('diagnoses',v)} options={diagnosisOptions}/>}</Question></>}
 {current==='Αγωγή & νοσηλείες'&&<><h1>Αγωγή & σοβαρό προηγούμενο ιστορικό</h1><Question title="Έχετε πάρει στο παρελθόν φάρμακα για την ψυχική υγεία;"><Choice value={history.past_meds} onChange={v=>setH('past_meds',v)} options={ynUnknown}/>{history.past_meds==='yes'&&<><label>Όνομα φαρμάκου, αν το θυμάστε<input value={history.past_medication_name} onChange={e=>setH('past_medication_name',e.target.value.slice(0,200))}/></label><Choice value={history.past_med_help} onChange={v=>setH('past_med_help',v)} options={[['very','Βοήθησε πολύ'],['enough','Αρκετά'],['little','Λίγο'],['none','Καθόλου'],['unknown','Δεν γνωρίζω']]}/><p>Είχατε σημαντικές παρενέργειες;</p><Choice value={history.past_med_side_effects} onChange={v=>setH('past_med_side_effects',v)} options={yn}/></>}</Question><Question title="Παίρνετε αυτή τη στιγμή φάρμακα;"><Choice value={history.current_meds} onChange={v=>setH('current_meds',v)} options={yn}/>{history.current_meds==='yes'&&<label>Ονόματα φαρμάκων<input value={history.current_medication_name} onChange={e=>setH('current_medication_name',e.target.value.slice(0,300))}/></label>}</Question><Question title="Έχετε νοσηλευτεί ποτέ για λόγους ψυχικής υγείας;"><Choice value={history.hospitalised} onChange={v=>setH('hospitalised',v)} options={yn}/>{history.hospitalised==='yes'&&<><Choice value={history.hospital_count} onChange={v=>setH('hospital_count',v)} options={[['1','1 φορά'],['2','2 φορές'],['3','3 φορές'],['4+','4+ φορές']]}/><Choice value={history.hospital_recent} onChange={v=>setH('hospital_recent',v)} options={[['lt1y','< 1 έτος'],['1-5y','1–5 έτη'],['gt5y','> 5 έτη'],['unknown','Δεν θυμάμαι']]}/></>}</Question><Question title="Έχετε αυτοτραυματιστεί ποτέ;"><Choice value={history.self_harm} onChange={v=>setH('self_harm',v)} options={ynPrefer}/></Question><Question title="Έχετε κάνει ποτέ απόπειρα αυτοκτονίας;"><Choice value={history.suicide_attempt} onChange={v=>setH('suicide_attempt',v)} options={ynPrefer}/></Question><div className="intake-safety-note">Οι ερωτήσεις αυτές αφορούν ιστορικό και δεν αντικαθιστούν την αξιολόγηση του γιατρού.</div></>}
 {current==='Σωματική υγεία & ουσίες'&&<><h1>Σωματική υγεία & ουσίες</h1><p>Για κάθε κατηγορία επιλέξτε Ναι ή Όχι.</p>{medicalOptions.map(m=><div className="intake-matrix-row" key={m}><span>{m}</span><Choice value={history.medical[m]||''} onChange={v=>setH('medical',{...history.medical,[m]:v})} options={yn}/></div>)}{(history.medical['Γνωστές αλλεργίες']==='yes'||history.medical['Αλλεργία σε φάρμακο']==='yes')&&<label>Ποια αλλεργία / αντίδραση;<input value={history.allergy_detail} onChange={e=>setH('allergy_detail',e.target.value.slice(0,300))}/></label>}<h3>Χρήση ουσιών</h3>{substanceOptions.map(s=><div className="intake-substance" key={s}><strong>{s}</strong><Choice value={history.substances[s]||''} onChange={v=>setH('substances',{...history.substances,[s]:v})} options={[['never','Ποτέ'],['past','Παλαιότερα'],['current','Τώρα']]}/>{history.substances[s]==='current'&&<Choice value={history.substance_frequency[s]||''} onChange={v=>setH('substance_frequency',{...history.substance_frequency,[s]:v})} options={[['rare','Σπάνια'],['monthly','1–3 φορές/μήνα'],['weekly','1–3 φορές/εβδομάδα'],['daily','Καθημερινά']]}/>}</div>)}</>}
 {current==='Οικογένεια & καθημερινότητα'&&<><h1>Οικογένεια & καθημερινότητα</h1><p>Οικογενειακό ψυχιατρικό ιστορικό</p>{familyConditions.map(c=><div className="intake-family" key={c}><strong>{c}</strong><Multi values={history.family[c]||[]} onChange={v=>setH('family',{...history.family,[c]:v})} options={familyRelations}/></div>)}<div className="intake-fields"><label>Σχέση / οικογενειακή κατάσταση<select value={history.relationship_status} onChange={e=>setH('relationship_status',e.target.value)}><option value="">Επιλέξτε</option><option>Μόνος/η</option><option>Σε σχέση</option><option>Έγγαμος/η / σύμφωνο</option><option>Χωρισμένος/η</option><option>Χήρος/α</option></select></label><label>Παιδιά<select value={history.children} onChange={e=>setH('children',e.target.value)}><option value="">Επιλέξτε</option><option>Όχι</option><option>Ναι</option></select></label><label>Με ποιον μένετε;<select value={history.living} onChange={e=>setH('living',e.target.value)}><option value="">Επιλέξτε</option><option>Μόνος/η</option><option>Με σύντροφο</option><option>Με οικογένεια</option><option>Με συγκατοίκους</option><option>Άλλο</option></select></label><label>Εργασία / σπουδές<select value={history.work} onChange={e=>setH('work',e.target.value)}><option value="">Επιλέξτε</option><option>Εργάζομαι</option><option>Σπουδάζω</option><option>Άνεργος/η</option><option>Άδεια / αναρρωτική</option><option>Συνταξιούχος</option><option>Άλλο</option></select></label></div><Question title="Υπάρχουν σημαντικές δυσκολίες στην εργασία ή στις σπουδές;"><Choice value={history.work_difficulty} onChange={v=>setH('work_difficulty',v)} options={yn}/></Question><Question title="Έχετε ανθρώπους που σας στηρίζουν;"><Choice value={history.support} onChange={v=>setH('support',v)} options={yn}/></Question><Question title="Υπάρχουν τρέχοντα νομικά προβλήματα;"><Choice value={history.legal} onChange={v=>setH('legal',v)} options={yn}/></Question><Question title="Έχετε βιώσει γεγονός που θεωρείτε σοβαρά τραυματικό;"><Choice value={history.trauma} onChange={v=>setH('trauma',v)} options={ynPreferOnly}/>{history.trauma==='yes'&&<label className="intake-optional">Σύντομη περιγραφή <span>προαιρετικό</span><textarea rows={2} value={history.trauma_note} onChange={e=>setH('trauma_note',e.target.value.slice(0,600))}/></label>}</Question><label className="intake-optional">Υπάρχει κάτι άλλο σημαντικό που θέλετε να γνωρίζει ο γιατρός; <span>προαιρετικό</span><textarea rows={3} value={history.other_note} onChange={e=>setH('other_note',e.target.value.slice(0,1000))}/></label></>}
 {(current==='PHQ-9'||current==='GAD-7')&&<Psychometric code={current} values={psych[current]||{}} onChange={(i,v)=>setPsych(p=>({...p,[current]:{...(p[current]||{}),[i]:v}}))}/>}
 {error&&<p className="intake-error" role="alert">{error}</p>}<footer>{step>0?<button type="button" onClick={()=>{setError('');setStep(x=>x-1)}}>Προηγούμενο</button>:<span/>}<button className="intake-primary" disabled={busy} onClick={()=>void next()}>{busy?'Υποβολή…':step===steps.length-1?'Υποβολή':'Συνέχεια'}</button></footer></main><small className="intake-private">Οι απαντήσεις σας συνδέονται μόνο με αυτή τη συμπλήρωση και θα ελεγχθούν από τον γιατρό.</small></div>
}
function Question({title,children}:{title:string;children:React.ReactNode}){return <section className="intake-question"><h3>{title}</h3>{children}</section>}
function Psychometric({code,values,onChange}:{code:'PHQ-9'|'GAD-7';values:Record<number,number>;onChange:(i:number,v:number)=>void}){const tool=instruments[code];return <><h1>{code}</h1><p>Τις τελευταίες 2 εβδομάδες, πόσο συχνά σας ενόχλησαν τα παρακάτω προβλήματα;</p>{tool.items.map((q,i)=><fieldset className="intake-psych-q" key={i}><legend>{i+1}. {q}</legend>{answerLabels.map((label,n)=><label key={n}><input type="radio" name={code+i} checked={values[i]===n} onChange={()=>onChange(i,n)}/><span>{label}</span></label>)}</fieldset>)}</>}
function Printable({payload}:{payload:IntakePayload}){return <div className="intake-print"><header><strong>Noima · Έντυπο συμπλήρωσης</strong><span>Κωδικός: {payload.id.slice(0,8).toUpperCase()}</span></header><h1>{payload.tools.includes('history')?'Ερωτηματολόγιο αρχικού ιστορικού':payload.tools.join(' · ')}</h1><p>Σημειώστε καθαρά μία επιλογή ανά ερώτηση. Τα ανοιχτά πεδία είναι προαιρετικά.</p>{payload.tools.includes('history')&&<><h2>Βασικά στοιχεία</h2><p>Όνομα ____________________ Επώνυμο ____________________</p><p>Ηλικία ____ Κινητό __________________ Email __________________</p><p>ΑΜΚΑ __________________ Διεύθυνση ______________________________</p><h2>Λόγος επίσκεψης</h2>{reasonOptions.map(x=><p key={x}>□ {x}</p>)}<h2>Προηγούμενο ιστορικό</h2>{['Έχετε επισκεφθεί στο παρελθόν ψυχίατρο;','Έχετε κάνει ψυχοθεραπεία ή παρακολούθηση από ψυχολόγο;','Σας έχει δοθεί ποτέ ψυχιατρική διάγνωση;','Έχετε πάρει στο παρελθόν φάρμακα για την ψυχική υγεία;','Παίρνετε αυτή τη στιγμή φάρμακα;','Έχετε νοσηλευτεί ποτέ για λόγους ψυχικής υγείας;','Έχετε αυτοτραυματιστεί ποτέ;','Έχετε κάνει ποτέ απόπειρα αυτοκτονίας;'].map(q=><p key={q}>{q} &nbsp; □ Ναι &nbsp; □ Όχι</p>)}<h2>Σωματική υγεία</h2>{medicalOptions.map(q=><p key={q}>{q} &nbsp; □ Ναι &nbsp; □ Όχι</p>)}<h2>Ουσίες</h2>{substanceOptions.map(q=><p key={q}>{q} &nbsp; □ Ποτέ &nbsp; □ Παλαιότερα &nbsp; □ Τώρα</p>)}</>}{(['PHQ-9','GAD-7'] as const).filter(c=>payload.tools.includes(c)).map(code=><section key={code}><h2>{code}</h2>{instruments[code].items.map((q,i)=><p className="print-question" key={q}><strong>{i+1}. {q}</strong><br/>□ Καθόλου &nbsp; □ Μερικές μέρες &nbsp; □ Περισσότερες από τις μισές μέρες &nbsp; □ Σχεδόν κάθε μέρα</p>)}</section>)}<button className="no-print" onClick={()=>window.print()}>Εκτύπωση</button></div>}
