"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, ChevronRight, Clock3, Mail, Plus, Search, ShieldCheck, Trash2, X, Printer, UserRound, ChevronDown, UploadCloud, FileText, Sparkles, Bell, Activity, Home, Settings, Stethoscope, Users, CalendarDays, Menu } from "lucide-react";

type Instrument={code:string;title:string;area:string;minutes:string;source:string;period:string;items:string[];options:{label:string;score:number}[];interpret:(n:number)=>string};
const frequency=[{label:"Καθόλου",score:0},{label:"Μερικές μέρες",score:1},{label:"Περισσότερες από τις μισές μέρες",score:2},{label:"Σχεδόν κάθε μέρα",score:3}];
const phq=["Είχατε μικρό ενδιαφέρον για δραστηριότητες ή λίγη ευχαρίστηση από δραστηριότητες","Νιώσατε πεσμένος(η), καταθλιμμένος(η) ή απελπισμένος(η)","Είχατε πρόβλημα να αποκοιμηθείτε ή να συνεχίσετε τον ύπνο σας ή κοιμόσασταν υπερβολικά","Νιώθατε κουρασμένος(η) ή είχατε λίγη ενέργεια","Είχατε μειωμένη όρεξη ή τρώγατε υπερβολικά","Νιώθατε άσχημα για τον εαυτό σας ή ότι έχετε αποτύχει ή ότι έχετε απογοητεύσει τον εαυτό σας ή την οικογένειά σας.","Είχατε πρόβλημα συγκέντρωσης σε κάποιες δραστηριότητες, όπως όταν διαβάζατε εφημερίδα ή όταν παρακολουθούσατε τηλεόραση","Κινιόσασταν ή μιλάγατε τόσο αργά που άλλοι άνθρωποι το παρατηρούσαν ή το αντίθετο, είσαστε τόσο ανήσυχος(η) ή νευρικός(ή), που κινιόσασταν πολύ περισσότερο από ότι συνήθως","Σκεπτόσασταν ότι θα ήταν καλύτερα αν είχατε πεθάνει ή σκεπτόσασταν να προκαλέσετε κακό στον εαυτό σας με κάποιο τρόπο"];
const gad=["Αισθανθήκατε νεύρα, άγχος ή ένταση","Δεν μπορούσατε να σταματήσετε ή να ελέγξετε το άγχος σας","Ανησυχούσατε υπερβολικά για διάφορα πράγματα","Δυσκολευόσασταν να χαλαρώσετε","Είχατε τόσο μεγάλη ανησυχία που δεν μπορούσατε να καθίσετε ακίνητος(η)","Νιώθατε εύκολα ενόχληση ή εκνευρισμό","Φοβόσασταν ότι κάτι φρικτό μπορεί να συμβεί"];
const pclOptions=[{label:"Not at all",score:0},{label:"A little bit",score:1},{label:"Moderately",score:2},{label:"Quite a bit",score:3},{label:"Extremely",score:4}];
const pcl=["Repeated, disturbing, and unwanted memories of the stressful experience?","Repeated, disturbing dreams of the stressful experience?","Suddenly feeling or acting as if the stressful experience were actually happening again (as if you were actually back there reliving it)?","Feeling very upset when something reminded you of the stressful experience?","Having strong physical reactions when something reminded you of the stressful experience (for example, heart pounding, trouble breathing, sweating)?","Avoiding memories, thoughts, or feelings related to the stressful experience?","Avoiding external reminders of the stressful experience (for example, people, places, conversations, activities, objects, or situations)?","Trouble remembering important parts of the stressful experience?","Having strong negative beliefs about yourself, other people, or the world (for example, having thoughts such as: I am bad, there is something seriously wrong with me, no one can be trusted, the world is completely dangerous)?","Blaming yourself or someone else for the stressful experience or what happened after it?","Having strong negative feelings such as fear, horror, anger, guilt, or shame?","Loss of interest in activities that you used to enjoy?","Feeling distant or cut off from other people?","Trouble experiencing positive feelings (for example, being unable to feel happiness or have loving feelings for people close to you)?","Irritable behavior, angry outbursts, or acting aggressively?","Taking too many risks or doing things that could cause you harm?","Being “superalert” or watchful or on guard?","Feeling jumpy or easily startled?","Having difficulty concentrating?","Trouble falling or staying asleep?"];
const categories=["Όλα","Κατάθλιψη","Άγχος"] as const;
const instruments:Instrument[]=[
 {code:"PHQ-9",title:"Ερωτηματολόγιο Υγείας Ασθενούς",area:"Κατάθλιψη",minutes:"2–5 λεπτά",source:"Επίσημη ελληνική έκδοση PHQ",period:"Τις τελευταίες 2 εβδομάδες",items:phq,options:frequency,interpret:n=>n<5?"Ελάχιστη συμπτωματολογία":n<10?"Ήπια":n<15?"Μέτρια":n<20?"Μετρίως σοβαρή":"Σοβαρή"},
 {code:"GAD-7",title:"Generalized Anxiety Disorder",area:"Άγχος",minutes:"2–3 λεπτά",source:"Επίσημη ελληνική έκδοση GAD-7",period:"Τις τελευταίες 2 εβδομάδες",items:gad,options:frequency,interpret:n=>n<5?"Ελάχιστη συμπτωματολογία":n<10?"Ήπια":n<15?"Μέτρια":"Σοβαρή"},
 {code:"PHQ-4",title:"Patient Health Questionnaire-4",area:"Κατάθλιψη / Άγχος",minutes:"1–2 λεπτά",source:"Ελληνικά επικυρωμένο ultra-short screening",period:"Τις τελευταίες 2 εβδομάδες",items:[phq[0],phq[1],gad[0],gad[1]],options:frequency,interpret:n=>n<3?"Φυσιολογικό εύρος":n<6?"Ήπια επιβάρυνση":n<9?"Μέτρια επιβάρυνση":"Σοβαρή επιβάρυνση"},
 {code:"PHQ-2",title:"Patient Health Questionnaire-2",area:"Κατάθλιψη",minutes:"< 1 λεπτό",source:"2 πρώτα λήμματα του PHQ-9",period:"Τις τελευταίες 2 εβδομάδες",items:[phq[0],phq[1]],options:frequency,interpret:n=>n>=3?"Θετικό screening — χρειάζεται περαιτέρω αξιολόγηση":"Αρνητικό screening"},
 {code:"GAD-2",title:"Generalized Anxiety Disorder-2",area:"Άγχος",minutes:"< 1 λεπτό",source:"2 πρώτα λήμματα του GAD-7",period:"Τις τελευταίες 2 εβδομάδες",items:[gad[0],gad[1]],options:frequency,interpret:n=>n>=3?"Θετικό screening — χρειάζεται περαιτέρω αξιολόγηση":"Αρνητικό screening"},
 {code:"PCL-5",title:"PTSD Checklist for DSM-5",area:"PTSD",minutes:"5–10 λεπτά",source:"U.S. National Center for PTSD · Public domain",period:"In the past month",items:pcl,options:pclOptions,interpret:n=>n>=33?"Score ≥33 — warrants clinical PTSD assessment":n>=31?"Score 31–32 — within suggested provisional cutoff range":"Below suggested provisional cutoff range"}
];

export default function Psychometrics(){
 const [mobileNav,setMobileNav]=useState(false);
 const [query,setQuery]=useState(""); const [category,setCategory]=useState<string>("Όλα"); const [active,setActive]=useState<Instrument|null>(null); const [answers,setAnswers]=useState<Record<number,number>>({});
 const visible=useMemo(()=>instruments.filter(x=>["PHQ-9","GAD-7"].includes(x.code)).filter(x=>{const categoryMatch=category==="Όλα"||(category==="Άγχος"&&x.area.includes("Άγχος"))||(category==="Κατάθλιψη"&&x.area.includes("Κατάθλιψη"));return categoryMatch&&(x.code+" "+x.area+" "+x.title).toLowerCase().includes(query.toLowerCase())}),[query,category]);
 const open=(i:Instrument)=>{setActive(i);setAnswers({})}; const score=Object.values(answers).reduce((a,b)=>a+b,0); const complete=active?Object.keys(answers).length===active.items.length:false;
 return <main className="app-shell secondary-shell"><aside className={mobileNav?"sidebar mobile-open":"sidebar"}><button className="mobile-nav-close" onClick={()=>setMobileNav(false)} aria-label="Κλείσιμο μενού"><X size={20}/></button><div className="brand"><div className="brand-mark">Ψ</div><div className="brand-copy"><div className="brand-sub">Για μια οργανωμένη κλινική πράξη</div></div></div><nav className="nav"><Link href="/" className="nav-item"><Home size={19}/><span>Επισκόπηση</span></Link><Link href="/calendar" className="nav-item"><CalendarDays size={19}/><span>Ημερολόγιο</span></Link><Link href="/patients" className="nav-item"><Users size={19}/><span>Ασθενείς</span></Link><Link href="/psychometrics" className="nav-item active"><Activity size={19}/><span>Ψυχομετρικά τεστ</span></Link></nav></aside>{mobileNav&&<button className="mobile-nav-backdrop" aria-label="Κλείσιμο μενού" onClick={()=>setMobileNav(false)}/>}<section className="workspace"><header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileNav(true)} aria-label="Άνοιγμα μενού"><Menu size={21}/></button><div className="search"><span>Ψ · ψυχομετρικά</span></div><div className="profile"><div className="avatar">ΚΠ</div><div><strong>Δρ. Κατερίνα Παπαδάκη</strong><span>Ψυχίατρος</span></div></div></header><div className="secondary-content psy-page"><div className="psy-content"><div className="psy-heading"><div><span className="kicker">ΚΛΙΝΙΚΗ ΒΙΒΛΙΟΘΗΚΗ</span><h1>Ψυχομετρικά τεστ</h1><p>Στο pilot είναι ενεργά τα PHQ-9 και GAD-7. Η πραγματική ανάθεση, βαθμολόγηση και αποθήκευση γίνεται από τον φάκελο ασθενούς.</p></div></div>
 <div className="category-filter-row"><div className="category-tabs">{categories.map(cat=><button key={cat} className={category===cat?"active":""} onClick={()=>setCategory(cat)}>{cat}</button>)}</div><span className="instrument-time">Η ανάθεση γίνεται από τον φάκελο ασθενούς</span></div><div className="psy-search category-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Αναζήτηση τεστ"/></div>
 <div className="psy-notice"><ShieldCheck size={17}/><div><strong>Κλινική χρήση με έλεγχο του ιατρού</strong><span>Τα αποτελέσματα είναι εργαλεία screening/παρακολούθησης και δεν αποτελούν αυτόνομη διάγνωση.</span></div></div>
 <section className="psy-grid">{visible.map(i=><article className="instrument-card" key={i.code}><div className="instrument-top"><span className="instrument-code">{i.code}</span><span className="instrument-time"><Clock3 size={13}/>{i.minutes}</span></div><div className="instrument-category">{i.area}</div><h2>{i.code}</h2><p>{i.title}</p><div className="instrument-meta"><span>{i.items.length} ερωτήσεις · {i.minutes}</span><span>{i.code==="PHQ-2"||i.code==="GAD-2"?"Σύντομο screening":i.code==="PHQ-4"?"Σύντομο screening κατάθλιψης & άγχους":i.code==="PCL-5"?"Αξιολόγηση συμπτωμάτων PTSD":"Πλήρης αξιολόγηση συμπτωμάτων"}</span><small>{i.source}</small></div><div className="instrument-actions"><button onClick={()=>open(i)}>Προεπισκόπηση <ChevronRight size={15}/></button><button onClick={()=>{setActive(i);setAnswers({});setTimeout(()=>window.print(),100)}}><Printer size={14}/> Εκτύπωση</button><Link href="/patients"><UserRound size={14}/> Ανάθεση από φάκελο</Link></div></article>)}</section>
 
 </div>
 {active&&<div className="instrument-overlay" onClick={()=>setActive(null)}><section className="instrument-sheet" onClick={e=>e.stopPropagation()}><header><div><span className="instrument-code">{active.code}</span><h2>{active.title}</h2><p>{active.period} — {active.code==="PCL-5"?"how much were you bothered by the following problems?":"πόσο συχνά σας ενόχλησαν τα παρακάτω προβλήματα;"}</p></div><button className="instrument-floating-close" onClick={()=>setActive(null)} aria-label="Κλείσιμο τεστ"><X size={19}/></button></header><div className="assessment-patient"><UserRound size={16}/><span>Προεπισκόπηση βιβλιοθήκης — δεν συνδέεται με ασθενή και δεν αποθηκεύεται. Για πραγματική ανάθεση ανοίξτε τον φάκελο ασθενούς.</span></div><div className="instrument-progress"><div style={{width:`${(Object.keys(answers).length/active.items.length)*100}%`}}/><span>{Object.keys(answers).length} / {active.items.length}</span></div><div className="instrument-questions">{active.items.map((q,idx)=><div className="instrument-question" key={q}><strong><span>{idx+1}</span>{q}</strong><div>{active.options.map(o=><button className={answers[idx]===o.score?"selected":""} key={o.score} onClick={()=>setAnswers(v=>({...v,[idx]:o.score}))}><i>{o.score}</i>{o.label}</button>)}</div>{active.code==="PHQ-9"&&idx===8&&answers[idx]!==undefined&&answers[idx]>0&&<div className="risk-answer-note"><ShieldCheck size={15}/> Θετική απάντηση στο λήμμα 9 — απαιτείται κλινική αξιολόγηση αυτοκτονικού κινδύνου.</div>}</div>)}</div><footer>{complete?<div className="score-result"><span>Συνολική βαθμολογία</span><strong>{score}</strong><b>{active.interpret(score)}</b></div>:<span>Απαντήστε σε όλες τις ερωτήσεις για υπολογισμό βαθμολογίας.</span>}<div className="assessment-footer-actions"><button className="print-result" onClick={()=>window.print()}><Printer size={14}/> Εκτύπωση</button><button disabled={!complete} onClick={()=>setActive(null)}>Κλείσιμο προεπισκόπησης</button></div></footer></section></div>}
 </div></section></main>
}