import {pilotClient} from '@/lib/pilot/server';import {withPilot} from '@/lib/pilot/route';
import {seal,unseal} from '@/lib/mail/crypto';import {send,tokens,validEmail,type Tokens,type Provider} from '@/lib/mail/providers';
export const dynamic='force-dynamic';
async function post(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Μη έγκυρη προέλευση.'},{status:403});const b=await req.json().catch(()=>({}));
 if(!validEmail(b.to)||typeof b.subject!=='string'||!b.subject.trim()||b.subject.length>200||/[\r\n]/.test(b.subject)||typeof b.body!=='string'||b.body.length>10000||typeof b.token!=='string'||!/^[a-f0-9]{64}$/.test(b.token)||typeof b.assessment_id!=='string'||!/^[a-f0-9-]{36}$/i.test(b.assessment_id))return Response.json({error:'Ελέγξτε τον παραλήπτη και το μήνυμα.'},{status:400});
 const link=new URL('/assessment',process.env.NOIMA_APP_ORIGIN||req.url).href+'#'+b.token;if(!b.body.includes(link))return Response.json({error:'Το μήνυμα πρέπει να περιλαμβάνει τον σύνδεσμο συμπλήρωσης.'},{status:400});
 const client=await pilotClient(),{data:{user}}=await client.auth.getUser();if(!user)return Response.json({error:'Συνδεθείτε.'},{status:401});const {data:mailbox,error:loadError}=await client.rpc('pilot_mailbox_get');if(loadError||!mailbox)return Response.json({error:'Συνδέστε πρώτα το email αποστολής σας από τον λογαριασμό.',code:'connect'},{status:409});
 let grant:Tokens;try{grant=unseal<Tokens>(mailbox.encrypted_tokens,user.id);if(grant.expires_at<Date.now()+60000){const updated=await tokens(mailbox.provider,{grant_type:'refresh_token',refresh_token:grant.refresh_token});grant={...updated,refresh_token:updated.refresh_token||grant.refresh_token};const {error}=await client.rpc('pilot_mailbox_save',{p_provider:mailbox.provider,p_email:mailbox.email,p_tokens:seal(grant,user.id)});if(error)throw new Error('save')}}catch{return Response.json({error:'Συνδέστε ξανά το email αποστολής σας.',code:'connect'},{status:409})}
 const {data:claim,error}=await client.rpc('pilot_mail_claim',{p_assessment:b.assessment_id,p_token:b.token,p_recipient:b.to});if(error)return Response.json({error:'Ο σύνδεσμος δεν είναι διαθέσιμος για αποστολή.'},{status:409});if(claim==='accepted')return Response.json({ok:true,status:'accepted'});if(claim!=='new')return Response.json({error:'Η προηγούμενη αποστολή δεν έχει επιβεβαιωθεί. Ελέγξτε τα απεσταλμένα πριν δημιουργήσετε νέο σύνδεσμο.',code:'unknown'},{status:409});
 try{const id=await send(mailbox.provider as Provider,grant.access_token,mailbox.email,b.to,b.subject,b.body);const {error:finishError}=await client.rpc('pilot_mail_finish',{p_assessment:b.assessment_id,p_status:'accepted',p_provider_id:id});if(finishError)return Response.json({error:'Το email έγινε δεκτό, αλλά δεν αποθηκεύτηκε η επιβεβαίωση. Ελέγξτε τα απεσταλμένα.',code:'unknown'},{status:503});return Response.json({ok:true,status:'accepted'});
 }catch(e){const known=e instanceof Error&&['mail_reconnect','mail_rejected'].includes(e.message);await client.rpc('pilot_mail_finish',{p_assessment:b.assessment_id,p_status:known?'failed':'unknown'});return Response.json({error:known?'Το email δεν έγινε δεκτό. Ελέγξτε τη σύνδεση email και δοκιμάστε ξανά.':'Δεν γνωρίζουμε αν το email στάλθηκε. Ελέγξτε τα απεσταλμένα πριν δημιουργήσετε νέο σύνδεσμο.',code:known?'failed':'unknown'},{status:502})}
}
export const POST=withPilot(post);
