create table if not exists public.demo_medication_side_effects(id uuid primary key default gen_random_uuid(),tester_id uuid not null,patient_id uuid not null references public.demo_patients(id) on delete cascade,medication_id uuid not null references public.demo_medications(id) on delete cascade,session_id uuid references public.demo_sessions(id) on delete set null,effect_text text not null,severity text not null default 'moderate' check(severity in ('mild','moderate','severe')),impact text not null default '',noted_on date not null default current_date,resolved_on date,note text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.demo_medication_side_effects enable row level security; drop policy if exists demo_read on public.demo_medication_side_effects; create policy demo_read on public.demo_medication_side_effects for select using(true); grant select on table public.demo_medication_side_effects to anon,authenticated; create index if not exists demo_side_effect_patient_idx on public.demo_medication_side_effects(tester_id,patient_id,noted_on desc);

create or replace function public.demo_apply_due_medication_events(p_tester uuid) returns void language plpgsql security definer set search_path=public as $$ declare m public.demo_medications; e public.demo_medication_events; begin for m in select * from public.demo_medications where tester_id=p_tester and status='active' loop select * into e from public.demo_medication_events where tester_id=p_tester and medication_id=m.id and event_type in ('changed','stopped') and effective_on<=current_date order by effective_on desc,created_at desc limit 1; if e.id is not null then if e.event_type='stopped' then update public.demo_medications set status='stopped',ended_at=e.effective_on,updated_at=now() where id=m.id and status='active'; elsif m.effective_from<e.effective_on or m.dose<>coalesce((e.new_state->>'dose')::numeric,m.dose) or m.frequency<>coalesce(e.new_state->>'frequency',m.frequency) then update public.demo_medications set dose=coalesce((e.new_state->>'dose')::numeric,m.dose),unit=coalesce(e.new_state->>'unit',m.unit),frequency=coalesce(e.new_state->>'frequency',m.frequency),effective_from=e.effective_on,updated_at=now() where id=m.id; end if; end if; end loop; end $$;

create or replace function public.demo_medication_change(p_tester uuid,p_medication uuid,p_session uuid,p_dose numeric,p_unit text,p_frequency text,p_effective date,p_reason text default '') returns public.demo_medications language plpgsql security definer set search_path=public as $$ declare r public.demo_medications; prev jsonb; next_state jsonb; begin select * into r from public.demo_medications where id=p_medication and tester_id=p_tester for update; if r.id is null or r.status<>'active' then raise exception 'medication_not_found'; end if; prev:=jsonb_build_object('dose',r.dose,'unit',r.unit,'frequency',r.frequency,'status',r.status); next_state:=jsonb_build_object('dose',p_dose,'unit',trim(p_unit),'frequency',trim(p_frequency),'status','active'); if p_effective<=current_date then update public.demo_medications set dose=p_dose,unit=trim(p_unit),frequency=trim(p_frequency),effective_from=p_effective,updated_at=now() where id=p_medication returning * into r; end if; insert into public.demo_medication_events(tester_id,patient_id,medication_id,session_id,event_type,previous_state,new_state,reason,effective_on) values(p_tester,r.patient_id,r.id,p_session,'changed',prev,next_state,trim(coalesce(p_reason,'')),p_effective); return r; end $$;

create or replace function public.demo_medication_stop(p_tester uuid,p_medication uuid,p_session uuid,p_effective date,p_reason text default '') returns public.demo_medications language plpgsql security definer set search_path=public as $$ declare r public.demo_medications; prev jsonb; begin select * into r from public.demo_medications where id=p_medication and tester_id=p_tester for update; if r.id is null or r.status<>'active' then raise exception 'medication_not_found'; end if; prev:=jsonb_build_object('dose',r.dose,'unit',r.unit,'frequency',r.frequency,'status',r.status); insert into public.demo_medication_events(tester_id,patient_id,medication_id,session_id,event_type,previous_state,new_state,reason,effective_on) values(p_tester,r.patient_id,r.id,p_session,'stopped',prev,prev||jsonb_build_object('status','stopped'),trim(coalesce(p_reason,'')),p_effective); if p_effective<=current_date then update public.demo_medications set status='stopped',ended_at=p_effective,updated_at=now() where id=p_medication returning * into r; end if; return r; end $$;

create or replace function public.demo_medication_side_effect_add(p_tester uuid,p_medication uuid,p_session uuid,p_effect text,p_severity text,p_impact text,p_noted_on date,p_note text default '') returns public.demo_medication_side_effects language plpgsql security definer set search_path=public as $$ declare m public.demo_medications; r public.demo_medication_side_effects; begin select * into m from public.demo_medications where id=p_medication and tester_id=p_tester; if m.id is null then raise exception 'medication_not_found'; end if; if length(trim(coalesce(p_effect,'')))<2 or p_severity not in ('mild','moderate','severe') then raise exception 'invalid_side_effect'; end if; insert into public.demo_medication_side_effects(tester_id,patient_id,medication_id,session_id,effect_text,severity,impact,noted_on,note) values(p_tester,m.patient_id,m.id,p_session,trim(p_effect),p_severity,trim(coalesce(p_impact,'')),p_noted_on,trim(coalesce(p_note,''))) returning * into r; return r; end $$;
grant execute on function public.demo_apply_due_medication_events(uuid),public.demo_medication_stop(uuid,uuid,uuid,date,text),public.demo_medication_side_effect_add(uuid,uuid,uuid,text,text,text,date,text) to anon,authenticated;
