'use client';
import Link from 'next/link';import {useState} from 'react';import {Camera,ChevronLeft,FileImage,Loader2} from 'lucide-react';
import PatientIntakeForm,{type IntakePayload} from '@/components/intake/PatientIntakeForm';
import {getDemoTesterId} from '@/lib/demo-tester';
import type {HistoryAnswers,IntakeIdentity} from '@/lib/intake/history';
type Extraction={intake:IntakePayload;identity:IntakeIdentity;history:HistoryAnswers;psychometrics:Record<string,number[]>;warnings:string[]};
async function imageData(file:File){const url=URL.createObjectURL(file);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Δεν διαβάστηκε η φωτογραφία.'));img.src=url});const max=1700,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',0.76)}finally{URL.revokeObjectURL(url)}}
export default function ScanPage(){const [images,setImages]=useState<string[]>([]),[extraction,setExtraction]=useState<Extraction|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function choose(files:FileList|null){if(!files)return;setError('');try{const selected=Array.from(files).slice(0,6);const values=[] as string[];for(const file of selected)values.push(await imageData(file));setImages(values)}catch(e){setError(e instanceof Error?e.message:'Δεν διαβάστηκαν οι εικόνες.')}}
 async function parse(){if(!images.length)return;setBusy(true);setError('');try{const r=await fetch('/api/intake/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'parse',tester:getDemoTesterId(),images})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Δεν αναγνωρίστηκε το έντυπο.');setExtraction(d)}catch(e){setError(e instanceof Error?e.message:'Δεν αναγνωρίστηκε το έντυπο.')}finally{setBusy(false)}}
 if(extraction)return <PatientIntakeForm payload={extraction.intake} initialIdentity={extraction.identity} initialHistory={extraction.history} initialPsychometrics={extraction.psychometrics} reviewMode reviewWarnings={extraction.warnings} onSubmit={async(identity,history,psychometrics)=>{const r=await fetch('/api/intake/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'commit',tester:getDemoTesterId(),intake_id:extraction.intake.id,identity,history,psychometrics})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Δεν καταχωρίστηκε η σάρωση.');return d}}/>;
 return <main className="scan-page"><header><Link href="/psychometrics"><ChevronLeft size={17}/> Βιβλιοθήκη</Link><div className="brand-mark">Ψ</div></header><section className="scan-card"><span className="kicker">ΕΙΣΑΓΩΓΗ ΑΠΟ ΕΝΤΥΠΟ</span><h1>Εισαγωγή συμπληρωμένου εντύπου</h1><p>Φωτογραφίστε ή ανεβάστε όλες τις σελίδες του εντύπου που εκτυπώθηκε από το Noima. Ο μοναδικός κωδικός της εκτύπωσης βρίσκει αυτόματα τον σωστό ασθενή ή ραντεβού. Θα δείτε πρώτα τις αναγνωρισμένες απαντήσεις και τον προορισμό πριν καταχωριστεί οτιδήποτε.</p><label className="scan-drop"><Camera size={27}/><strong>{images.length?images.length+' σελίδ'+(images.length===1?'α':'ες')+' έτοιμες':'Φωτογράφιση ή ανέβασμα σελίδων'}</strong><span>JPG / PNG · έως 6 σελίδες</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple capture="environment" onChange={e=>void choose(e.target.files)}/></label>{images.length>0&&<div className="scan-thumbs">{images.map((src,i)=><img key={i} src={src} alt={'Σελίδα '+(i+1)}/>)}</div>}{error&&<p className="intake-error" role="alert">{error}</p>}<button className="intake-primary scan-submit" disabled={!images.length||busy} onClick={()=>void parse()}>{busy?<><Loader2 className="scan-spin" size={17}/> Αναγνώριση…</>:<><FileImage size={17}/> Αναγνώριση εντύπου</>}</button><small>Υποστηρίζονται έντυπα που δημιουργήθηκαν από το Noima και περιέχουν κωδικό ανάθεσης. Η καταχώριση γίνεται μόνο μετά από έλεγχο.</small></section></main>}
